### ISSUE TITLE
Antergos Projectm for pulseaudio crashing at preset change.

### ISSUE THREAD

**Issue by michaelothing** [projectM-visualizer/projectm#100]
Title says it all. I am on Arch Based Antergos. Projectm for pulse audio starts I can go full screen, bring up the menu and the shortcuts, but, the first time presets change crash. I have tried other versions of projectm, both jack and alsa libvisual version, and can't figure out how to get them connected. Anyone else having problems or a possible solution?

**Comment by michaelothing** [comment]
I should have also mentioned that git versions on the AUR error out during building. Something about not being able to find a file to patch.

**Comment by revmischa** [comment]
May or may not be related to https://github.com/projectM-visualizer/projectm/issues/97
Maybe see if fixed in the `glsl` branch #26 ?

**Comment by michaelothing** [comment]
==> Starting prepare()...
can't find file to patch at input line 4
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff -rupN projectm.old/src/libprojectM/CMakeLists.txt projectm/src/libprojectM/CMakeLists.txt
|--- projectm.old/src/libprojectM/CMakeLists.txt	2012-06-30 02:21:45.134586637 -0300
|+++ projectm/src/libprojectM/CMakeLists.txt	2012-06-30 02:24:58.476872545 -0300
--------------------------
File to patch:

**Comment by michaelothing** [comment]
Either file causes build to fail. So I can't try the git version. Antergos is like Manjaro except it has all Arch repositories and the complete AUR. Still it is pretty much automated so I am spoiled and never had to build anything by hand. Not really sure what to do with the provided links if you are not just suggesting what the problem could be.

**Comment by michaelothing** [comment]
Okay I unchecked use first source and selected the correct one and the crash seems to have gone away on it's own, though I don't understand why that would have caused a crash and not simply not connected projectm and my audio. The build error in the git version in the AUR persists. Not sure who to report that to.

**Comment by revmischa** [comment]
The project moved away from CMake quite a long time ago, arch needs to update its build scripts. 
https://github.com/projectM-visualizer/projectm/issues/100#issuecomment-418169321

You can see the arch status here: https://aur.archlinux.org/pkgbase/projectm-git/

**Comment by michaelothing** [comment]
Thankfully the version in the official repository works fine.
