### ISSUE TITLE
Crash when run for a while at Renderer

### ISSUE THREAD

**Issue by eximpression** [projectM-visualizer/projectm#104]
![default](https://user-images.githubusercontent.com/2516598/45919107-59d79180-bec3-11e8-991d-4de930fdd568.png)
I got crash at same line several times.

**Comment by revmischa** [comment]
Everything is platform independent. What's preventing you from building on ARM?

**Comment by revmischa** [comment]
This may be fixed. Please try master and reopen if you continue to experience issues
