### ISSUE TITLE
please update sourceforge.net 

### ISSUE THREAD

**Issue by sergiomb2** [projectM-visualizer/projectm#108]
I'm astonished no distribution had updated projectm from 2.1.0 ( 2012-05-20 ) ! 
Take a look [1] , [2] .
I'm a Fedora packager [3] , since Fedora 28 projectM-pulseaudio start crashing [4] , another problem is to be with qt4 which is obsoleted .

So I suggest , drop a note on sourceforge.net that are new versions available on github ! . 

Thanks 

[1] 
https://pkgs.org/download/libprojectm-qt

[2]
https://repology.org/metapackage/libprojectm/versions

[3]
https://src.fedoraproject.org/rpms/libprojectM

 [4]
https://bugzilla.redhat.com/show_bug.cgi?id=1631104

**Comment by revmischa** [comment]
Only @psperl can update sourceforge.

**Comment by sergiomb2** [comment]
Hi, I tested this new release with autotools [1] and I think we need some work /usr/lib64/ don't have libprojectM-qt.so.1 and so version should be update to 3.1.0 still in 2.0.0 [2]

[1]
https://copr.fedorainfracloud.org/coprs/sergiomb/builds_for_Stable_Releases/package/libprojectM/

[2]
libprojectM.so        libprojectM.so.2      libprojectM.so.2.0.0  pkgconfig/

**Comment by hauntingEcho** [comment]
I'd also like to submit a bug report to Debian about this (their 'homepage' links are to SF and their [versions are 2.1](https://packages.debian.org/source/stretch/projectm), & are getting [qt4 EoL warnings](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=875112)), but will feel more comfortable doing so if there's a message on the old SF page to back me up.

**Comment by psperl** [comment]
I'll update it for real this time. Sorry for the delays.

**Comment by psperl** [comment]
I just updated the webpage to redirect here and also officially marked projectM development as "moved to github" in the project settings on github.  Here's hoping the website redirection doesn't work for 24 hours then revert like last time.

**Comment by sergiomb2** [comment]
redirect is working , thanks .

**Comment by hauntingEcho** [comment]
Thanks!  I've [submitted the move to debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=909977)
