### ISSUE TITLE
Preset subdirectories

### ISSUE THREAD

**Issue by revmischa** [projectM-visualizer/projectm#109]
It would be really useful for organizing presets if the presets directory could contain sub-directories.

**Comment by mancoast** [comment]
Do we need to find an alternative for dirent.h that uses recursive directory scan for presets path?

**Comment by revmischa** [comment]
Perhaps?

**Comment by mancoast** [comment]
This is a great task for someone new that wants to get involved and requires exact specifics for what needs done

**Comment by AlwinEsch** [comment]
Have added for Kodi a Patch to change prefix install way, see second commit here: https://github.com/xbmc/visualization.projectm/pull/36

But I'm not sure how this can be used on other systems.

Also, I noticed that some of the same file names were in different folders and then overwritten during installation to a previous folder.

**Comment by revmischa** [comment]
Agreed, so you would like a config option to enable recursively scanning the preset directory for all preset files? And deduplicating by filename?

**Comment by revmischa** [comment]
Done in #385
