### ISSUE TITLE
Daydream mode on Android pro version

### ISSUE THREAD

**Issue by yaronguez** [projectM-visualizer/projectm#116]
Hi there, this is a very interesting project. I purchased the pro version from the Google Play Store for $2.99 because of its purported daydream mode which I thought meant that it would work with Google Daydream VR headset. It doesn't look like that is the case. What is Daydream mode then? Is there any way you get this working on the Daydream / Cardboard VR headset?

**Comment by revmischa** [comment]
Hi, I'd love to help you but this is the open source project. The mobile version is maintained by someone else.
