### ISSUE TITLE
iTunes visualizer sometimes goes black

### ISSUE THREAD

**Issue by rothn** [projectM-visualizer/projectm#117]
Sometimes when I'm playing a song, the iTunes visualizer goes completely black for over 5 seconds using the default config file. I'm not sure why this happens, but it's annoying. Does anyone know why? I'd love to fix it if someone has any clue.

**Comment by rothn** [comment]
I still see 5-ish second-long black segments sometimes. Does this have to do with missing smooth transitions?

**Comment by revmischa** [comment]
It may be due to parsing errors or rendering issues or bad presets. We need a more curated set of default presets and to make some fixes to the parser and shaders.

**Comment by revmischa** [comment]
https://github.com/projectM-visualizer/projectm/issues/118

**Comment by revmischa** [comment]
This may be fixed now. Please reopen if it continues with the latest code

**Comment by rothn** [comment]
Built from source again and did a `sudo make install`. Restarted iTunes and the issue persists. I didn't have to fix ANY issues during build this time though, which was nice. Still happening as of "b92a283b d9df7c78 Merge pull request #182 from mancoast/appv" (latest is a merge commit).
