### ISSUE TITLE
iOS retail build crashes when I click Settings button

### ISSUE THREAD

**Issue by RoohBear** [projectM-visualizer/projectm#121]
I just bought the iOS version from the App Store. On my iPhone 8+, it crashes when I tap the Settings button.  Haven't been able to figure out how to make it play any music yet :-(

**Comment by revmischa** [comment]
This open source project is not the same projectM as in the app stores. That is maintained separately. Support cannot be found here, sorry.

cc @psperl

**Comment by ScubyUK** [comment]
Hi @revmischa @psperl 

I also have the same problem as @RoohBear on iOS 12.1 iPhone X and iPad 4.

iOS Link on this page takes me to the App Store for the App
Support Link on the App Store for the App brings me back to this Github Project.
If the app is maintained separately as you have stated then please update the iOS Links with the correct Support Information.

Thanks

**Comment by psperl** [comment]
Redirecting SF to github makes it look like there's only one organization.
I'm not sure what to do about that.
