### ISSUE TITLE
projectm is installed but wont open in ubuntu 18.04

### ISSUE THREAD

**Issue by bpuffz** [projectM-visualizer/projectm#126]
after upgrading to ubuntu 18.04 projectm pulse audio wont open.
i found it in software center so i uninstalled then reinstalled.
still wont open.

**Comment by MaybETree** [comment]
Try running projectM from the terminal:
`projectM-pulseaudio`
If it complains about fonts, you'll have to symlink some other font to the location where projectM's trying to load them from

**Comment by v6277** [comment]
I found this fix on the comment section of Ubuntu 18.04, I can't find it anymore so I can't give credits to the original author but basically it's a problem with the fonts. Here's the fix MaybETree is talking about. 

> Ive noticed I am not the only one who suffered from projectM failing to start after updating to Ubuntu 17.04.  I am now on 18.04 LTS and this fix is still working.  If you cannot get the preset menu to go away when you start the software, simply press the "M" key to toggle the menu on and off.
>
>There is an issue in the directory of the fonts that are being loaded by the software.  What needs to be done is that the /usr/share/projectM/config.inp needs to be changed so that the two  lines:
>
>Title Font = /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans.ttf
Menu Font = /usr/share/fonts/truetype/ttf-dejavu/DejaVuSansMono.ttf
>
>To fix the error change the above lines in config.inp to:
>
>Title Font = /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
Menu Font = /usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf
>
>You can confirm this by attempting to run projectM from a terminal by issuing the following command:  
>
>projectM-pulseaudio
>
>The output should give you some errors about the above font files.  Also when issuing commands "projectM" is case sensitive.
>
>To perform this:
>1) Open a terminal
>2) Enter the command:
>	sudo gedit /usr/share/projectM/config.inp
>3) Upon the prompt enter your password:
>4) Edit the two lines as above
>5) File save as and overwrite the file.  Note if you get an error read only try using Nano editor within the terminal to edit the two lines
>6)  I was also unable to start the program until I changed the config.inp located in the directory:
/home/"Your Username"/.projectM/config.inp
>7) In the terminal navigate to this file via:
>	sudo gedit /home/"Your Username"/.projectM/config.inp
>8)  Edit the same two lines as instructed above and overwrite the original file.
>
>This software is excellent.  I have found no better example of a responsive and mesmerizing visualizer.  
>
>Hope this helps.  Cheers.

**Comment by revmischa** [comment]
Debian has super old packages. A new release needs to be done
See: https://github.com/projectM-visualizer/projectm/issues/200

**Comment by horace-zontal** [comment]
I did:

sudo apt-get update
sudo apt-get install ttf-dejavu

and it works now.

**Comment by revmischa** [comment]
If you want to update the README with that package that'd be super appreciated! Just open a PR

**Comment by Naereen** [comment]
Hi,
Nothing to add here, but just to inform, I am on Ubuntu 18.04 and go into the same issue.
Applying the suggested fix by changing `/usr/share/projectM/config.inp` did *not* work for me, but I simply sim-linked the missing folder `/usr/share/fonts/truetype/ttf-dejavu/` to the existing `/usr/share/fonts/truetype/dejavu/`:
```bash
sudo ln -s /usr/share/fonts/truetype/dejavu/ /usr/share/fonts/truetype/ttf-dejavu
```
now I can launch ProjectM with no issue.
