### ISSUE TITLE
Can't figure out how to install as iTunes plugin

### ISSUE THREAD

**Issue by claytonhamshar** [projectM-visualizer/projectm#131]
The instructions for installing this are not clear to me. I am on Mac OS X.
I downloaded the .gz file, and both .pkg files. I installed both .pkg files and the .bundle appears in my Library > iTunes > Plugins folder. I attempted to add the code found under Mac OS X into terminal but it says invalid. What else do I need to do to install? The visualizer does not appear in iTunes...

**Comment by revmischa** [comment]
If you install the pkg and then restart iTunes, it should appear under view/visualizer. It doesn't?

**Comment by claytonhamshar** [comment]
No, it does not. I can't figure out why!

*Clayton Hamshar*
*Musician, Designer, Writer*

*www.claytonhamshar.com <http://www.claytonhamshar.com>*
*www.soundcloud.com/sunrizen <http://www.soundcloud.com/sunrizen>*

**Comment by revmischa** [comment]
dang, i'd like to help you but not sure what the issue is.. can you look in Console.app when starting iTunes after installing the plugin and see if it outputs any errors? do you have iProjectm.bundle in `/Library/iTunes/iTunes Plug-ins`?

**Comment by severitt** [comment]
Check to see if you have a file ~/Library/iTunes/iTunes Plug-ins/DisabledPlugins.plist. 

I had a problem with projectM not showing up in the iTunes visualisers menu before, and found that it had been added to this file after a crash.

The contents of the file were as follows:

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>biz.int80.iProjectM</key>
	<array>
		<string>1</string>
	</array>
</dict>
</plist>
`

I found deleting the file in question and restarting iTunes did the trick. ( I don't think deleting it will cause problems later, as the file creation date was the same as the last modified date, meaning iTunes appears to have created it when the crash first happened. However, you could backup or rename the file if you want, just to be sure).

**Comment by claytonhamshar** [comment]
Thank you for your help!

Yes, I have iProjectm.bundle in that folder.
No, I don't see a Disabledplugins.plist file.
The console shows a bunch of errors, but they all seem to be about VST
plugins (which I use with Ableton, no idea why they would have some sort of
iTunes association
*Clayton Hamshar*
*Musician, Designer, Writer*

*www.claytonhamshar.com <http://www.claytonhamshar.com>*
*www.soundcloud.com/sunrizen <http://www.soundcloud.com/sunrizen>*

**Comment by severitt** [comment]
Try the /Users/<your user name>/Library/iTunes/iTunes Plug-ins/ directory, not /Library/iTunes/iTunes Plug-ins/

**Comment by claytonhamshar** [comment]
I don't have a Library folder under /Users. Library is at the same top
level as Users.

Thank you for your patience!


*Clayton Hamshar*
*Musician, Designer, Writer*

*www.claytonhamshar.com <http://www.claytonhamshar.com>*
*www.soundcloud.com/sunrizen <http://www.soundcloud.com/sunrizen>*

**Comment by revmischa** [comment]
I'm sure they mean ~/Library/...

**Comment by severitt** [comment]
Sorry, part of the path got edited out. It should have been
`/Users/<your username>/Library/iTunes/iTunes Plug-ins/`

**Comment by sage-michaels** [comment]
Hey! I was having a similar issue... turns out I had a DisabledPlugins file in /Users/<your username>/Library/iTunes/iTunes Plug-ins/ and when I deleted it the projectM visualizer started showing up in my iTunes visualizer list. I'm new to this so I might have accidentally ruined something by deleting that file but ¯\_(ツ)_/¯
