### ISSUE TITLE
Settings and output resolution broken by iOS12

### ISSUE THREAD

**Issue by VonDeeper** [projectM-visualizer/projectm#136]
This program works flawlessly under iOS 11. When I upgrade to iOS 12 on two different devices it breaks the settings function, causing an immediate crash when I try to access my output resolution. I am an end user that was using this in a live performance setting so I would really appreciate it if this could get fixed. If I can do anything to help please respond. I’m not great at coding but am willing to assist in any way I can.  Interested in making this work again...

**Comment by revmischa** [comment]
The mobile apps are not maintained as part of this project. You'll have to contact the author. Sorry.

**Comment by VonDeeper** [comment]
Does anyone know the author?
