### ISSUE TITLE
projectm-pulseAudio : choosen sink is not remembered

### ISSUE THREAD

**Issue by Cyborgscode** [projectM-visualizer/projectm#139]
when i choose a different sink, projectM does recgonize the change, but it does not save it. 
Neither does it save it on purpose  ( config save ) nor on change. 

It's stuck with the first sink in the sink list, which in my case, will never hear music ;)

**Comment by struktured** [comment]
I can't reproduce this. I did notice though that saving only occurs when the program exits- perhaps you're experiencing an unclean shutdown. I could instead make the save step happen more aggressively if you're willing to test the patch.

Check `~/.config/projectM/qprojectM-pulseaudio.conf` to see if the config is even being cached at all.
