### ISSUE TITLE
No milkdrop on OSX these days?

### ISSUE THREAD

**Issue by thcpkn** [projectM-visualizer/projectm#14]
Not working on itunes 12.6.2, osx 10.9.5 over here. .bundle is installed but no projectm available in visualisers? 

Also tried installing projectm-Jackosx with Jack 0.92 and projectm app won't launch:

Dyld Error Message:
  Library not loaded: QtGui.framework/Versions/4/QtGui
  Referenced from: /Applications/projectM-jack.app/Contents/MacOS/projectM-jack
  Reason: image not found

Binary Images:
0x8feb7000 - 0x8fee9497  dyld (239.5) <86B9ED65-6A74-340B-A990-2E21CAF0BB21> /usr/lib/dyld
0x994f0000 - 0x994f0fff  com.apple.Carbon (154 - 157) <33457512-4EA2-373B-BB04-A6A7B6D4E54A> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon

help! =(

**Comment by revmischa** [comment]
I really don't know anything about the Jack app. 
iTunes support in recent OSX is known broken: #12 
Patches welcome!

**Comment by thcpkn** [comment]
Oh nooo! Thanks for current version btw, been a workhorse for years 'til update :)

**Comment by thcpkn** [comment]
Rolling back iTunes to 10.7 fixes it. Fixes a lot of things actually...

**Comment by revmischa** [comment]
Please feel free to contribute fixes 😄

**Comment by Sivat394** [comment]
Hey @revmischa is there a way to have projectM work with all sound for macOS instead of just itunes? 

Despite being on a macbook I try to avoid apples ecosystem like it has the plague and can't see any clear cut way of setting this up. 

If that feature hasn't been added at all I'd be willing to take a look at figuring out how to do it if you could just point me in the right direction.

**Comment by revmischa** [comment]
I looked into this before, I was going to use SDL2. Look in projectM-sdl, there's a function `selectAudioInput()` that says:
`too bad the libsdl2 audio capture support doesn't exist`
Well, they just added this capability! So do that.

The -sdl version works on OSX nicely as a standalone application. It just uses random audio data right now, needs capture ability. Which you can now do with libsdl2, as of very recently.

**Comment by revmischa** [comment]
@Sivat394 are you looking into SDL audio input at all? let me know if you do

**Comment by revmischa** [comment]
Audio input in the SDL2 version is now working https://github.com/projectM-visualizer/projectm/commit/83ca57979289cc6ef05c13d2f1c47f48efbe6729

**Comment by Sivat394** [comment]
Oh man I didn't even realize I had response to this. Is there anymore work that needs to be done with the SDL2 version? that seems like a solid jumping point for me vs trying to figure out audio units.

**Comment by revmischa** [comment]
It is in fact working, but yes there is a great deal of work to do. Check out the build or glsl branches. Happy to chat about it more. We just started a #projectm on freenode if you want to chat there.
As far as the SDL2 version - a major issue right now is that it just picks the first audio capture device. Some way to tell it to use a specific capture device/channel is needed (needs some sort of a UI)
Also building is all up in flux right now. Trying out autotools and https://github.com/c3d/build - welcome to help with that. cmake sux.
