### ISSUE TITLE
Fedora 28 : projectm-pulseaudio crashes directly under ltrace

### ISSUE THREAD

**Issue by Cyborgscode** [projectM-visualizer/projectm#140]
I was trying to find out more about the crash of projectm-pulseaudio, so i tried to start it with ltrace, but it crashed before the main window gets opened:

Version: projectM-pulseaudio.x86_64  2.1.0-7.fc28

due to the dbus communication(right ?) the ltrace output isn't helpful.

ltrace:
...
ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a89924670, 0x7ffebc3075a0, 2)                                                                            = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a89925b80, 0x7ffebc307580, 3 <unfinished ...>
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a89925b80, 0x7ffebc307160, 0x564a899259a0)                                                               = 1
<... _ZN12QApplication6notifyEP7QObjectP6QEvent resumed> )                                                                                                               = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a89924670, 0x7ffebc3075a0, 2)                                                                            = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a89921ee0, 0x7ffebc307630, 3)                                                                            = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a89920590, 0x7ffebc3076c0, 5)                                                                            = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a8991ee50, 0x7ffebc307750, 2)                                                                            = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a8991d240, 0x7ffebc3077e0, 3)                                                                            = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a8991c6d0, 0x7ffebc307870, 2)                                                                            = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a89916580, 0x7ffebc307840, 0x564a8979ed01)                                                               = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a89925490, 0x7ffebc307840, 0x564a89927490)                                                               = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a89925490, 0x7ffebc3078d0, 0x7f814a600660)                                                               = 0
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a89916580, 0x7ffebc307870, 0x564a89927601)                                                               = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a8991aab0, 0x7ffebc307870, 0x564a8991ab70)                                                               = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a8991aab0, 0x7ffebc307900, 0x7f814a600660)                                                               = 0
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a8991aab0, 0x7ffebc3078a0, 0)                                                                            = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a8991aab0, 0x7ffebc3078b0, 0)                                                                            = 0
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a8991aab0, 0x7ffebc307890, 0x564a89927610)                                                               = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a8991aab0, 0x7ffebc307890, 0x7f814a600660)                                                               = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a8991aab0, 0x7ffebc307890, 1)                                                                            = 0
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a89916580, 0x7ffebc307880, 0x564a898bd801)                                                               = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a899555d0, 0x7ffebc307880, 0x564a8994c2d0)                                                               = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a899555d0, 0x7ffebc307910, 0x7f814a600660)                                                               = 0
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a899555d0, 0x7ffebc307840, 0)                                                                            = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a899555d0, 0x7ffebc307890, 1)                                                                            = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a899555d0, 0x7ffebc307860, 0x564a8994c250)                                                               = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a899555d0, 0x7ffebc307760, 0x564a89800001)                                                               = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a89957350, 0x7ffebc307760, 0x564a89957350)                                                               = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a89957350, 0x7ffebc3077f0, 0x7f814a600660)                                                               = 0
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a89957350, 0x7ffebc307800, 0x564a89800000)                                                               = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a89957350, 0x7ffebc3077f0, 0x564a89800000)                                                               = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a899555d0, 0x7ffebc307760, 0x564a89810001)                                                               = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a89957170, 0x7ffebc307760, 0x564a89957170)                                                               = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a89957170, 0x7ffebc3077f0, 0x7f814a600660)                                                               = 0
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a89957170, 0x7ffebc307800, 0x564a89810000)                                                               = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a89957170, 0x7ffebc3077f0, 0x564a89810000)                                                               = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a89957350, 0x7ffebc307840, 0x564a89800000)                                                               = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a899555d0, 0x7ffebc307860, 0)                                                                            = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a89957350, 0x7ffebc3078d0, 0x564a89800000)                                                               = 0
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a89957170, 0x7ffebc3077d0, 0x564a89810000)                                                               = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a899555d0, 0x7ffebc3077f0, 0)                                                                            = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a89957170, 0x7ffebc307860, 0x564a89810000)                                                               = 0
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a89916580, 0x7ffebc307840, 0x564a89793501)                                                               = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a899571a0, 0x7ffebc307840, 0x564a89951bf0)                                                               = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a899571a0, 0x7ffebc3078d0, 0x7f814a600660)                                                               = 0
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a89916580, 0x7ffebc307880, 0x564a89834801)                                                               = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a89955770, 0x7ffebc307880, 0x564a89951cf0)                                                               = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a89955770, 0x7ffebc307910, 0x7f814a600660)                                                               = 0
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a89955770, 0x7ffebc307890, 0)                                                                            = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a8991b5a0, 0x7ffebc307970, 0)                                                                            = 0
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a8991b870, 0x7ffebc307970, 0)                                                                            = 0
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a8991b570, 0x7ffebc307970, 0)                                                                            = 0
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a8991bde0, 0x7ffebc307970, 0)                                                                            = 0
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a8991c080, 0x7ffebc307970, 0)                                                                            = 0
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a8991c420, 0x7ffebc307970, 0)                                                                            = 0
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a8991ba70, 0x7ffebc3078e0, 0x564a899ae440)                                                               = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a8991ba70, 0x7ffebc3078a0, 0x564a899e7810)                                                               = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a8991ba70, 0x7ffebc3078f0, 0x564a899e7810)                                                               = 1
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a8991ba70, 0x7ffebc307940, 7 <unfinished ...>
_ZN12QApplication6notifyEP7QObjectP6QEvent(0x7ffebc307c90, 0x564a8991ccc0, 0x7ffebc307570, 0x564a897caa00)                                                               = 0
<... _ZN12QApplication6notifyEP7QObjectP6QEvent resumed> )                                                                                                               = 1
+++ killed by SIGILL +++

**Comment by sergiomb2** [comment]
please report here: https://bugzilla.redhat.com/show_bug.cgi?id=1631104

you are using old version  2.1.0

**Comment by sergiomb2** [comment]
IMHO, we may close this issue this bug is about projectm 2.1.0 and Qt4 , now we are working on libprojectM 3.1.1 and Qt5

**Comment by revmischa** [comment]
Agreed, thanks for the report but please let us know what's broken with the latest code not old code because new and fun and exciting things are broken now!
