### ISSUE TITLE
Recommended workflow for preset development with mac

### ISSUE THREAD

**Issue by sage-michaels** [projectM-visualizer/projectm#145]
I'm very new to ProjectM and interested in tinkering around with presets, I'm using a mac and have the projectM SDL up and running. I've been looking around online and pressing "m" when the visualizer is open is supposed to bring up some sort of menu but this doesn't happen for me (neither do the F1,F2,F3 calls that should report info about current preset). 

My current fix is moving all presets to a new subfolder and tinkering with one in the main folder at a time but am curious if people have developed better workflows? Thanks so much.

**Comment by sage-michaels** [comment]
I found a similar question on another board with the response:

"I don't believe that the developers of projectM included that feature. It's easy to be idealistic and think of projectM as "Milkdrop for Mac"—but, sadly it isn't!"

is this true?

**Comment by revmischa** [comment]
SDL is a basic reference implementation. 
I can't speak for all the developers of projectM but the goal as I see it is to be a library that can be used in all sorts of media players and applications. It is up to the program using the library to add whatever features are desired. The SDL version is new and doesn't have anything fancy, but feel free to send in a patch adding a menu or preset info overlay.

**Comment by revmischa** [comment]
That is a good question. I think some people use the qt5/pulseaudio app. I use the iTunes plugin and don't edit presets.
There is a need for better preset editing tools for sure. I hope people contribute some!

**Comment by sage-michaels** [comment]
I'm interested in trying to solve the issue of building a preset editing menu into the SDL, I have some questions/confusions though.

In [projectm/src/libprojectM/KeyHandler.cpp](https://github.com/projectM-visualizer/projectm/blob/fb53ca9e176526e143295d411d86e92a608d44de/src/libprojectM/KeyHandler.cpp) I can see that the Menu Interface and Editor Interface are unimplemented, yet when reading through [this article](https://www.maketecheasier.com/power-music-visualizations-with-projectm/) I see that the author has no issue pressing 'm' and pulling up the menu. Is it that the menu interface is implemented somewhere in one of the projectM-jack apps or is it that I'm on a mac rather than linux?

I'd love to implement some interfaces myself, but if there is somewhere in the code that it's already implemented I'd like to use that as a template since I'm only a beginner.

**Comment by revmischa** [comment]
Sure, look in the pulseaudio and jack directories. 
It would be cool if some of the desired functionality was in libprojectM rather than the applications

**Comment by sage-michaels** [comment]
Will do, I guess I'm having difficulty understanding the following:

a.) I understand Jack and PulseAudio to both connect an audio source (such as Itunes) to the projectM SDL display window, if this is the case then why would there be a difference in the way the SDL manages keyboard input (like the 'm') key when receiving 'fake audio' as a default in the SDL vs when receiving audio through Jack/PulseAudio?

b.)  I'm having difficulty finding where the Menu Interface is implemented in the apps, does anyone have any insight as to what the pop-up preset menu might be referred to as? I see calls to the 'preset factory', 'preset loader' or 'preset chooser' but am having difficulty figuring out what these things do.


Any insight will be much appreciated. Thanks!

**Comment by revmischa** [comment]
a)
projectM-sdl reads from an audio capture source with SDL. As far as it's concerned it just reads via SDL, jack/pulseaudio aren't involved in any way from its point of view

b)
Preset factory is for loading and parsing and instantiating the presets. I don't know about loader or chooser.

**Comment by revmischa** [comment]
Consolidating some issues into: #204
