### ISSUE TITLE
Nothing clear on how to use the software on Linux MX

### ISSUE THREAD

**Issue by CodeKraft** [projectM-visualizer/projectm#146]
I have tried following your instructions, I get various things reported back to me, the ./config does not exist, yet its a file off this site.

I have a Linux MX install.

Firstly, do I continue? Is this going to make a plugin that OpenShot or KdenLive can use?

Secondly, if so, how? How do I make it when the instructions on making the file fail?

Really frustrated because I was sold the ease of use of Linux and how creativity is more free yet EVERYTHING so far has held me back. Even the OS went through a period of it not working properly.

So if anyone knows what I need to do, I'd appreciate the input because I did the 

cd /navigate to my home DIR where files folder is/
cd /in to that folder...
typed ./config at the commandline as instructed and got ... No such file or directory
Can you consider using .deb package installers and a GUI that at least shows the settings and what is possible built in instructions that the user can follow on how to use with external software, etc... 

I will be moving to Arch at some point, so I hope you're supported on that platform or you support that platform...

**Comment by revmischa** [comment]
Where is `./config` documented? The file is called `./configure`. Where do you see "./config"?

.deb is a packaging system for a particular type of linux distribution. Hopefully maintainers of those distros will update their debian packages sometime soon.
projectM is supported on any system with openGL, Arch included.

**Comment by CodeKraft** [comment]
All it says is, change directory to... the specified location... *check*

Then it says type ./congie

which I do... 

Then I get an error message saying that it does not exist.

not that it matters really as most items that require "building" on the user system fails to produce an execrable.

All I want to do is use the software, not make it or build it or anything to it to make it work, really do not have the time to waste on that kind of thing, if you happen to be technically minded and want to play with the code, fair enough but please, build a package that will install. has a GUI to set up rather than convoluted lists of settings with mind boggling terms for setting, really am getting fed up of this myth that linux is easy to use for creativity,.
 
So please please please, an installer is needed to do the job automatically for the non technical heads using linux.

regards,
Mark.


|o|
~~~~
Respect Water, an average of 250 deaths occur each year from drowning.

--------------------------------------------
On Fri, 11/1/19, Mischa Spiegelmock <notifications@github.com> wrote:

 Subject: Re: [projectM-visualizer/projectm] Nothing clear on how to use the software on Linux MX (#146)
 To: "projectM-visualizer/projectm" <projectm@noreply.github.com>
 Cc: "Mark" <mark.giblin@yahoo.co.uk>, "Author" <author@noreply.github.com>
 Date: Friday, 11 January, 2019, 6:39
 
 Where is ./config
 documented? The file is called ./configure.
 Where do you see "./config"?
 .deb is a packaging system for a particular type of linux
 distribution. Hopefully maintainers of those distros will
 update their debian packages sometime soon.
 
 projectM is supported on any system with openGL, Arch
 included.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by revmischa** [comment]
I asked you:
> Where is ./config documented? The file is called ./configure. Where do you see "./config"?

**Comment by CodeKraft** [comment]
I have no idea.

I navigated to the place in the instructions, its not there and I have checked I am in the correct folder.

I will deal with the missing package over the weekend.

Thanks.




--------------------------------------------
On Tue, 15/1/19, Mischa Spiegelmock <notifications@github.com> wrote:

 Subject: Re: [projectM-visualizer/projectm] Nothing clear on how to use the software on Linux MX (#146)
 To: "projectM-visualizer/projectm" <projectm@noreply.github.com>
 Cc: "Mark" <mark.giblin@yahoo.co.uk>, "Author" <author@noreply.github.com>
 Date: Tuesday, 15 January, 2019, 8:53
 
 I asked you:
 
 Where is ./config documented? The file is called
 ./configure. Where do you see "./config"?
 
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by revmischa** [comment]
I'd be happy to update or correct the existing instructions if you can tell me where you are seeing that. You have no idea where the instructions you were following were? How is such a thing possible on God's green Earth?
