### ISSUE TITLE
ProjectM on ARM?

### ISSUE THREAD

**Issue by Sivat394** [projectM-visualizer/projectm#15]
Seeing as projectM has been ported to both android and iOS is there any chance of it getting ported to ARM linux based distros? I think the rpi 3 should be strong enough to support it

**Comment by revmischa** [comment]
Those ports are proprietary and I don't have the source. @psperl maintains them.
I'm sure projectM will _build_ on ARM, but most ARM devices don't support OpenGL immediate mode. Embedded devices and SoCs like the rpi use OpenGL ES instead.
There's a ticket for GLES support (#11). Feel free to do it!

**Comment by revmischa** [comment]
ARM will work when GLES works - #11
