### ISSUE TITLE
Cannot load music picker on iOS 12

### ISSUE THREAD

**Issue by kalafalas** [projectM-visualizer/projectm#157]
When tapping the music icon in iOS 12 the app crashes to the home screen, rendering it useless.

**Comment by einsteinx2** [comment]
The iOS app is not maintained by this project, it was created by the original (I think) projectM developer using a closed source rewrite in OpenGL ES for mobile devices. This project now has it's own ES support, but the currently released iOS app is unrelated.

**Comment by revmischa** [comment]
Correct, the iOS and android versions are not a part of this project. Sorry but we can't help.
cc @struktured
