### ISSUE TITLE
projectM Visualizer.xcodeproj  Shadow Developer Private Dir...

### ISSUE THREAD

**Issue by pehohlva** [projectM-visualizer/projectm#16]
Hi,   I would also like to know how my code is run on other box/machines.
.... best regards
This is error code from Xcode...
ld: warning: directory not found for option '-L/Users/snooz/dev/projectm/src/libprojectM'
ld: warning: directory not found for option '-L/Users/snooz/dev/projectm/src/libprojectM/Renderer'
ld: warning: directory not found for option '-L/Users/snooz/dev/projectm/src/libprojectM/MilkdropPresetFactory'
ld: warning: directory not found for option '-L/Users/snooz/dev/projectm/src/libprojectM/NativePresetFactory'

**Comment by revmischa** [comment]
hm those should be relative not absolute paths :(
what commands did you run to get that?

**Comment by revmischa** [comment]
Those files are relative to project paths, I think xcode is telling you you haven't compiled libprojectM. You need to build that first. it should build libRenderer, libMilkdropPresetFactory etc
Once those are built (by building src/libprojectM) you should be able to build the xcode project

**Comment by revmischa** [comment]
Also you need https://developer.nvidia.com/cg-toolkit-download but I hope to get rid of this

**Comment by pehohlva** [comment]
Hi is line 324 |  from https://raw.githubusercontent.com/projectM-visualizer/projectm/eafa3251c3af3a801950d588c3b531fbc7cba317/src/projectM-emscripten/emprojectM.xcodeproj/project.pbxproj

/Users/bobo/ && /Users/snooz/ is not my path ...  is hardlink.. 
I wand only to play audiobook file mp4 e mp4b...

**Comment by revmischa** [comment]
Okay well the emscripten project doesn't work. It depends on openGL ES support ( #11 ) for WebGL. Try the iTunes or SDL version (I'm working on the SDL one right now)
Patches always welcome!

**Comment by pehohlva** [comment]
Hi..
Ok tanks.. i try to coreaudio..  to play mp4 audiobook...
last night i try  https://github.com/wang-bin/QtAV i have build on mac e
cmake..  but is nice and  very large...
You work on Linux?

grüsse aus dem schwarzwald...
https://sourceforge.net/projects/wysiwyg-edit/
https://sourceforge.net/projects/oasidoc/
p.k


............................
Peter Hohl
Mail pehohlva@gmail.com
............................

2017-09-18 0:51 GMT+02:00 Mischa Spiegelmock <notifications@github.com>:

**Comment by revmischa** [comment]
I have the SDL2 (cross-platform: mac, windows, linux, etc) version working with audio input and building with just `Make` (no cmake) on the [build](../tree/build) branch

**Comment by revmischa** [comment]
check out the build branch, projectm-sdl. it works with linux. got rid of cmake. #17
