### ISSUE TITLE
projectM-pulseaudio cannot add presets

### ISSUE THREAD

**Issue by tomporter518** [projectM-visualizer/projectm#165]
I have pulled the latest from GitHub, built (successfully), deployed and run without issue. I cannot, however, click on the buttons or choose from the menu bar, Open Playlist or Add Preset. The main window 'dims' as if a modal is present but no file chooser dialog appears. I don't see any output/failures when executing via a command line. Any suggestions on next steps to diagnose?

**Comment by tomporter518** [comment]
I did a bit more digging and searching online. It seems that it maybe QT theme related and how that interacts with the system file chooser and my distro (Fedora 29). I can get a proper file chooser if I start projectM-pulseaudio with this: env QT_QPA_PLATFORMTHEME=flatpak. Thought I would post it here for anyone searching for a similar issue. I don't know 'why' it works exactly and they the gnome or gtk3 themes do NOT work...but I can at least get by using the 'flatpak' theme.

**Comment by revmischa** [comment]
What OS?
Maybe add a note to the README or something?

**Comment by tomporter518** [comment]
I have had a bit more time to research and experiment with this. The workaround I posted above is clunky, at best, and results in oddly-styled 'portal' dialogs. It appears that the QT native dialogs hang when trying to open for the playlist and preset dialogs. I noticed the mouse changed to resize and move handles as I passed over the non-visible borders. Using this link: [Code freezes on trying to open QDialog](https://stackoverflow.com/questions/31983412/code-freezes-on-trying-to-open-qdialog), I found that adding this->setOption(QFileDialog::DontUseNativeDialog); to both src/projectM-qt/qplaylistfiledialog.hpp and src/projectM-qt/qpresetfiledialog.hpp allowed the dialogs to completely render AND has the added benefit that they now match the other non-native dialogs. Here is what the patch would look like:
```
diff --git a/src/projectM-qt/qplaylistfiledialog.hpp b/src/projectM-qt/qplaylistfiledialog.hpp
index 265f8d85..7754f06f 100644
--- a/src/projectM-qt/qplaylistfiledialog.hpp
+++ b/src/projectM-qt/qplaylistfiledialog.hpp
@@ -40,6 +40,8 @@
      inline QPlaylistFileDialog(QWidget * parent = 0): 
                QFileDialog(parent, OPEN_PLAYLIST_OR_DIRECTORY_TITLE, QString()), m_directorySelectAllowed(true), m_fileSelectAllowed(true) {
 
+            this->setOption(QFileDialog::DontUseNativeDialog);
+
             updateFileMode(selectedFiles());
             
             //connect(this, SIGNAL(filesSelected(const QStringList&)),
diff --git a/src/projectM-qt/qpresetfiledialog.hpp b/src/projectM-qt/qpresetfiledialog.hpp
index 06abe67c..aece7416 100644
--- a/src/projectM-qt/qpresetfiledialog.hpp
+++ b/src/projectM-qt/qpresetfiledialog.hpp
@@ -41,6 +41,8 @@
      QPresetFileDialog(QWidget * parent = 0): 
                QFileDialog(parent, "Add preset files", QString(), "Presets (*.prjm *.milk *.so)" ) {
 
+               this->setOption(QFileDialog::DontUseNativeDialog);
+
                this->setFileMode(QFileDialog::ExistingFiles);
        }
```

**Comment by revmischa** [comment]
Great, feel free to open a PR
