### ISSUE TITLE
List of "good" default presets needed

### ISSUE THREAD

**Issue by revmischa** [projectM-visualizer/projectm#169]
Want to help make projectM a lot better? No coding required!

Task: make a new directory of curated presets that are known to work well and look good with projectM. 

Some shader-based presets that run well and are tested are in `presets/presets_mischa_collection/` - can use this as a starting point

I asked for some suggestions [here](http://forums.shoutcast.com/showthread.php?p=3167918) - found some great presets there but unfortunately many of them are broken with projectM due to requiring specific shader features. There is a ticket to try to figure out what's wrong and fix it (#118)

**Comment by srs231198** [comment]
what exactly do you need help with?

**Comment by revmischa** [comment]
1. try to fix whatever is breaking those presets in #118 and any others people may find, may help us find bugs to compare the output to milkdrop

2. a directory full of decent presets, the more the better

**Comment by sedago** [comment]
I know the bug tracker is the wrong place to ask this. I am throwing a party in two weeks and was wondering which preset folder would be the best choice for me right now?

**Comment by revmischa** [comment]
Try mine maybe? Not so many in there

**Comment by sedago** [comment]
First of all thanks to you, I have been using milkdrop and your presets since early 2k.
From my calculations you preset folder would start to loop after about 25min, that might just get too repetitive but I will definitely try it out.

I would love to help make a list of good plugins, not sure how accessible contributing is though. The easiest way for us would be if we could just press a key if a preset looks good to save it. Atm I am not even getting an overlay when using projectM-pulseaudio (F keys, menu works though).

**Comment by mancoast** [comment]
It would definitely be helpful for someone to curate the presets.

**Comment by revmischa** [comment]
A streamlined way to mark good presets and then collect them would be great. There is a "presetRating" system already built in but I don't believe it's hooked up to any UI

**Comment by mancoast** [comment]
Is it possible to render the same sample of audio, and record video output for each preset for comparable visual inspection against baseline input? I suggest some public domain audio source that everyone can freely access. What are your thoughts?

**Comment by revmischa** [comment]
happy to donate some audio of my own but there needs to be something to run the input. should be relatively straightforward to pipe in PCM data from a WAV file - not sure how to render to a video but such a feature would be nice

**Comment by sedago** [comment]
The question is if it is even really necessary. Would just listening to music and enjoying the experience while categorizing everything be easier and more enjoyable?

Just a key input to mark it  in an exportable list, or directly copy the preset to a good/bad folder. This could be expanded for tags, but I think just getting a "good/not broken" list would be the first step.

**Comment by sedago** [comment]
I went through all presets and removed most/all:
- Nothing showing
- Looks bad / to broken
- Can't keep a steady 60 FPS with a ryzen 2700x (~2193 single core passmark performance)
- A lot of broken presets are still in there, but If they still showed something interested I did not delete them

This list is obviously far from perfect, but it removes also cleans up the presets quite a lot. I have it saved as playlist, should I upload it in the repo? If so where and what should I name it?

**Comment by mancoast** [comment]
Share list here

**Comment by revmischa** [comment]
wonderful, make a PR that deletes the presets from the repo

**Comment by revmischa** [comment]
and upload the presets to #118 so we can investigate why they don't work and maybe fix some bugs

**Comment by sedago** [comment]
> PR

What do you mean with this? I guess I would have to write a script first which moves the presets inside the playlist.

I can share the list here, just thought it might be helpful if we could edit it. I renamed it to *.txt to allow the upload.

[projectM - evermind - cleaned V1.txt](https://github.com/projectM-visualizer/projectm/files/3077655/projectM.-.evermind.-.cleaned.V1.txt)

**Comment by Purukitto** [comment]
> > PR
> 
> What do you mean with this? I guess I would have to write a script first which moves the presets inside the playlist.

@sedago PR refers to a Pull Request. [This ](https://yangsu.github.io/pull-request-tutorial/ ) is a good read to get started.
