### ISSUE TITLE
VLC Shader Compilation Errors

### ISSUE THREAD

**Issue by voncloft** [projectM-visualizer/projectm#179]
I attached a pastebin

When VLC tries to use projectM it crashes with the following:

https://pastebin.com/Gin7VJ1R

projectM compiles correctly enabling gles and qt as well...any ideas?

**Comment by revmischa** [comment]
What OS and OpenGL drivers are you using? What GLSL version is supported on your system?

**Comment by voncloft** [comment]
3.3

**Comment by voncloft** [comment]
Linux from scratch

**Comment by voncloft** [comment]
Any ideas?
