### ISSUE TITLE
[Suggestion] projectM IRC channel?

### ISSUE THREAD

**Issue by prg318** [projectM-visualizer/projectm#18]
Hi,
A lot of open source projects have IRC channels that help people follow the project and provide a community for people interested in the project.  I don't see any IRC channels for projectM or milkdrop development, but I think there are people interested - as projectM is the most capable and portable milkdrop compatible visualizer out there.

IRC Channels can also be a great place for potential contributors to ask questions that may not necessarily warrant a github issue or hunting down developer email addresses.

It's pretty simple to register a channel on freenode and post something in the README.  I know I would /join if there was an official channel.

Just wanted to pass this suggestion along - I'd love to see a #projectM on freenode or somewhere!

**Comment by revmischa** [comment]
Done: https://github.com/projectM-visualizer/projectm/commit/a07db7969be840f2b661ab1cc8022f50da9ef504#diff-04c6e90faac2675aa89e2176d2eec7d8R82
