### ISSUE TITLE
monitor audio data being played

### ISSUE THREAD

**Issue by mancoast** [projectM-visualizer/projectm#180]
Hello!

I am requesting that the SDL implementation support visualization of the audio being played on my computer.  I do not want to play my tunes with projectm, and I do not want to use any microphone.  Is it possible to addpcm data from the OS aka visualize a streaming video in the background?

Thanks,
coast

**Comment by revmischa** [comment]
I'm unsure exactly how that would work with SDL to be honest. That would be nice but likely requires something platform-specific. What OS are you talking about here?

**Comment by mancoast** [comment]
Greetings, I am trying to get a stand-alone visualization for windows audio output channel.

**Comment by revmischa** [comment]
I highly doubt SDL is able to do such a thing on its own. Normally on macOS or windows I believe usually one uses a system extension that lets you route audio to virtual audio devices.

SDL docs on audio capture are here FWIW: https://wiki.libsdl.org/SDL_OpenAudioDevice but all you can do is select an audio capture device.

**Comment by mancoast** [comment]
I agree that SDL might not be optimal here.  I am currently cleaning up the windows build and getting ready for a PR upstream, however, it feels incomplete. The QT5 and SDL projects both compile for windows, would do you think if we pursue a QT5 option instead of SDL?  The docs: https://doc.qt.io/qt-5.9/audiooverview.html 

The goal is to interoperate with the operating system: and visualize using audio output channel to provide the visual for any audio.

**Comment by revmischa** [comment]
It looks like you won’t get any better support with Qt; the QIODevices you can open will probably be the same as the SDL audio capture devices. 
Sadly on Windows and macOS doing what you want may require the user to set up virtual audio devices or use something like JACK. I’m not sure this can be solved in projectM without creating a virtual audio device with a system extension on Windows or macOS but I welcome being proved wrong.

**Comment by mancoast** [comment]
I agree, thanks! with respect to sdl, this issue can be closed
