### ISSUE TITLE
fix qt build for windows

### ISSUE THREAD

**Issue by ghost** [projectM-visualizer/projectm#183]
the QT build is broken for msvc build, it requires some additional rework

**Comment by teotigraphix** [comment]
Have you been working on this? I am trying to get a x86/64 build for the Android emulator, is this even possible?

I have to be honest, I can add a lot to this project but the builds are driving me nuts and I am so confused. :)

**Comment by revmischa** [comment]
Qt has some very particular way it likes to be built. See: #173

**Comment by mancoast** [comment]
I have got projectM-qt5 building on windows, but the frame rate is unusable? Any suggestions as to why?
