### ISSUE TITLE
Re-open #177

### ISSUE THREAD

**Issue by rothn** [projectM-visualizer/projectm#185]
The maintainer @revmischa said to re-open my report #117 if this still happens with the latest version. Since I can't reopen, I am posting a new issue. Here is the comment I made today on #117 :

Built from source again and did a `sudo make install`. Restarted iTunes and the issue persists. I didn't have to fix ANY issues during build this time though, which was nice. Still happening as of "b92a283b d9df7c7 Merge pull request #182 from mancoast/appv" (latest is a merge commit).

**Comment by rothn** [comment]
Also, there's a new preset that shows nothing but pixelated clouds... They don't move, it's just a bad background image...

**Comment by revmischa** [comment]
I assume it's issues with particular presets. There are open related issues: #169 #118. Probably not related to iTunes specifically.
Basically we need to clean out some presets that don't work and also do some code fixes.

**Comment by rothn** [comment]
Here are some to clean out, from what I observed in logs while watching the pretty pictures (I turned on PRESET_DEBUG or some macro like that):

martin - volcano.milk : Stuck on yellow screen
Zylot & Krash - Snowflake Halo (Ice Cube mix).milk : Black
AdamFX 2 Geiss - Mash-Up - Angelic  Staine Glass Chapters 6_1.milk : Black

=== CRASH ===
[Preset] loading file "/usr/local/share/projectM/presets/martin - adrift on a dead planet - lard mix.milk"...
Failed to compile shader 'Fragment: Warp'. Error: ERROR: 0:111: Return type in redeclared function 'noise4' differs from previous declaration
ERROR: 0:123: Return type in redeclared function 'noise2' differs from previous declaration
ERROR: 0:171: Incompatible types (float and vec2) in assignment (and no available implicit conversion)
ERROR: 0:174: Incompatible types (float and vec2) in assignment (and no available implicit conversion)
ERROR: 0:177: Incompatible types (float and vec2) in assignment (and no available implicit conversion)
ERROR: 0:179: No matching function for call to pow(vec4, float)

Failed to link program: ERROR: One or more attached shaders not successfully compiled

Compilation error (step3) of Warp
Source:
#version 330
vec2 matrix_row0(mat2 m, int i) { return vec2( m[0][i], m[1][i] ); }
vec3 matrix_row0(mat3 m, int i) { return vec3( m[0][i], m[1][i], m[2][i] ); }
vec4 matrix_row0(mat4 m, int i) { return vec4( m[0][i], m[1][i], m[2][i], m[3][i] ); }
vec2  m_scalar_swizzle20(float x) { return  vec2(x, x); }
ivec2 m_scalar_swizzle20(int   x) { return ivec2(x, x); }
vec3  m_scalar_swizzle30(float x) { return  vec3(x, x, x); }
ivec3 m_scalar_swizzle30(int   x) { return ivec3(x, x, x); }
vec4  m_scalar_swizzle40(float x) { return  vec4(x, x, x, x); }
ivec4 m_scalar_swizzle40(int   x) { return ivec4(x, x, x, x); }
uvec2 m_scalar_swizzle20(uint  x) { return uvec2(x, x); }
uvec3 m_scalar_swizzle30(uint  x) { return uvec3(x, x, x); }
uvec4 m_scalar_swizzle40(uint  x) { return uvec4(x, x, x, x); }
vec2 bvecTernary0(bvec2 cond, vec2 trueExpr, vec2 falseExpr) { vec2 ret; ret.x = cond.x ? trueExpr.x : falseExpr.x; ret.y = cond.y ? trueExpr.y : falseExpr.y; return ret; }
vec3 bvecTernary0(bvec3 cond, vec3 trueExpr, vec3 falseExpr) { vec3 ret; ret.x = cond.x ? trueExpr.x : falseExpr.x; ret.y = cond.y ? trueExpr.y : falseExpr.y; ret.z = cond.z ? trueExpr.z : falseExpr.z; return ret; }
vec4 bvecTernary0(bvec4 cond, vec4 trueExpr, vec4 falseExpr) { vec4 ret; ret.x = cond.x ? trueExpr.x : falseExpr.x; ret.y = cond.y ? trueExpr.y : falseExpr.y; ret.z = cond.z ? trueExpr.z : falseExpr.z; ret.w = cond.w ? trueExpr.w : falseExpr.w; return ret; }
mat2 mat2_from_float_float_float_float(float a, float b, float c, float d) { return mat2(a,c,b,d); }
in vec4 frag_COLOR;
in vec4 frag_TEXCOORD0;
in vec2 frag_TEXCOORD1;
out vec4 rast_FragData[1];
uniform vec4 texsize_pw_noise_lq;
uniform vec4 texsize_pw_main;
uniform vec4 texsize_pc_main;
uniform vec4 texsize_noisevol_lq;
uniform vec4 texsize_noisevol_hq;
uniform vec4 texsize_noise_mq;
uniform vec4 texsize_noise_lq_lite;
uniform vec4 texsize_noise_lq;
uniform vec4 texsize_noise_hq;
uniform vec4 texsize_main;
uniform vec4 texsize_fw_main;
uniform vec4 texsize_fc_main;
uniform sampler2D sampler_pw_noise_lq;
uniform sampler2D sampler_pw_main;
uniform sampler2D sampler_pc_main;
uniform sampler3D sampler_noisevol_lq;
uniform sampler3D sampler_noisevol_hq;
uniform sampler2D sampler_noise_mq;
uniform sampler2D sampler_noise_lq_lite;
uniform sampler2D sampler_noise_lq;
uniform sampler2D sampler_noise_hq;
uniform sampler2D sampler_main;
uniform sampler2D sampler_fw_main;
uniform sampler2D sampler_fc_main;
uniform vec4 rand_frame;
uniform vec4 rand_preset;
uniform vec4 _c0;
uniform vec4 _c1, _c2, _c3, _c4;
uniform vec4 _c5;
uniform vec4 _c6;
uniform vec4 _c7;
uniform vec4 _c8;
uniform vec4 _c9;
uniform vec4 _c10;
uniform vec4 _c11;
uniform vec4 _c12;
uniform vec4 _c13;
uniform vec4 _qa;
uniform vec4 _qb;
uniform vec4 _qc;
uniform vec4 _qd;
uniform vec4 _qe;
uniform vec4 _qf;
uniform vec4 _qg;
uniform vec4 _qh;
uniform mat3x4 rot_s1;
uniform mat3x4 rot_s2;
uniform mat3x4 rot_s3;
uniform mat3x4 rot_s4;
uniform mat3x4 rot_d1;
uniform mat3x4 rot_d2;
uniform mat3x4 rot_d3;
uniform mat3x4 rot_d4;
uniform mat3x4 rot_f1;
uniform mat3x4 rot_f2;
uniform mat3x4 rot_f3;
uniform mat3x4 rot_f4;
uniform mat3x4 rot_vf1;
uniform mat3x4 rot_vf2;
uniform mat3x4 rot_vf3;
uniform mat3x4 rot_vf4;
uniform mat3x4 rot_uf1;
uniform mat3x4 rot_uf2;
uniform mat3x4 rot_uf3;
uniform mat3x4 rot_uf4;
uniform mat3x4 rot_rand1;
uniform mat3x4 rot_rand2;
uniform mat3x4 rot_rand3;
uniform mat3x4 rot_rand4;
float quality, depth;
vec3 rsl, rsl2, rss, ret1, rs2, rs3;
vec2 dz, uv0, uv1, uv2, uv3, uv4, dz1, tmp2, ditch2;
float ditch, lprof, lprof2, sprof, sprof2, n, noise, stone, stone_lit, sun, cloud, sky, lava, hor;
float flashmask, hormask, lavmask, ilavmask, lavmask_s, cldmask, lavmod;
float lav_gnd, hordist, tele, sky_gnd;
vec2 mov, sunpos, planpos;
vec3 skycol;
vec3 lavcol(float t) {
    return smoothstep(vec3 (0), vec3 (0.800000), vec3(t, pow(t, 2.200000), pow(t, float (5))));
}
float nmod(vec2 uvi) {
    return float (mix(vec4 (0.700000), texture(sampler_noise_hq, uvi), vec4 ((_qd).y)));
}
float flash(vec2 uvi) {
    return (0.500000 / pow(abs((uvi).x), 0.500000));
}
float hq_n(vec3 uvi) {
    return dot(texture(sampler_noisevol_hq, uvi), vec4 (vec3(0.320000, 0.490000, 0.290000), 0));
}
float noise4(vec3 uvi) {
    float tmp, k1, k2, k3, k4, z;
    (z = ((uvi).z / float (2048)));
    (k1 = clamp((float (1) - (z / float (2))), 0.0, 1.0));
    (k2 = (clamp((float (1) - (z * float (2))), 0.0, 1.0) / float (2)));
    (k3 = (clamp((float (1) - (z * float (4))), 0.0, 1.0) / float (4)));
    (k4 = ((clamp((float (1) - (z * float (8))), 0.0, 1.0) / float (4)) * float (0)));
    float mean = float( (((k1 + k2) + k3) + k4) );
    ((uvi).z = (0.010000 * (_c2).x));
    (tmp2 = vec2 ((((((hq_n((uvi * vec3 ((k1 >= float (0))))) * k1) + (hq_n(((uvi * vec3 (2)) * vec3 ((k2 >= float (0))))) * k2)) + (hq_n(((uvi * vec3 (4)) * vec3 ((k3 >= float (0))))) * k3)) + (hq_n(((uvi * vec3 (8)) * vec3 ((k4 >= float (0))))) * k4)) - (mean / float (2)))));
    return float (tmp2);
}
float noise2(vec3 uvi) {
    ((uvi).z = float (0));
    return clamp((mix(hq_n(uvi), hq_n((uvi * vec3 (4))), (_qh).z) - (_qc).y), 0.0, 1.0);
}
vec3 rs_lav(vec2 uvi, float berg) {
    float z;
    vec2 rs;
    (z = ((float (2) / (uvi).y) * ((_qb).w - (float (4) * berg))));
    (z = clamp(z, (-0.100000), (float (32) * hordist)));
    ((rs).x = (((uvi).x * float (2)) * z));
    ((rs).y = z);
    (rs = ((rs)*(mat2_from_float_float_float_float((_qa).z, (_qa).w, (-(_qa).w), (_qa).z))));
    return vec3(((rs / vec2 (64)) + mov), z);
}
vec3 rs_sky(vec2 uvi, float berg) {
    float z;
    vec2 rs;
    (z = ((float (10) - (_qb).w) / ((uvi).y - berg)));
    (z = clamp(z, float ((-150)), float (16)));
    ((rs).x = (((uvi).x * float (2)) * z));
    ((rs).y = z);
    (rs = ((rs)*(mat2_from_float_float_float_float((_qa).z, (_qa).w, (-(_qa).w), (_qa).z))));
    return vec3((((-rs) / vec2 (64)) + (mov / vec2 (4))), z);
}
void PS(vec4 _vDiffuse, vec4 _uv, vec2 _rad_ang, out vec4 _return_value) {
    vec3 ret = vec3( 0 );
    (uv1 = (_uv).xy);
    (uv0 = (_uv).xy);
    (uv2 = ((uv1 * (_c0).xy) * vec2 (tele)));
    (rsl = rs_lav((vec2 (tele) * vec2(((uv1).x * float (0)), (-0.200000))), (-(_qb).w)));
    (lav_gnd = float ((((texture(sampler_noise_hq, vec2 ((rsl / vec3 (4)))) * vec4 (0.200000)) / vec4 ((_qb).w)) - vec4 (0.150000))));
    for ((n = float (1)); (n <= quality); (n++)) {
        (rsl = rs_lav((vec2 (tele) * uv1), lav_gnd));
        (lprof = float ((texture(sampler_noise_hq, ((rsl).xy / vec2 (4))) - vec4 (0.750000))));
        (lprof += float ((texture(sampler_noise_hq, ((rsl).xy / vec2 (2))) / vec4 (2))));
        (ditch = (clamp(((float (6) * length(sin((((rsl).xy / vec2 (2)) + vec2 ((lprof * 0.000000)))))) - float (7)), 0.0, 1.0) * float (0)));
        (lprof = mix(lprof, float (1), ditch));
        (lav_gnd -= ((lprof / quality) * depth));
    }
    (lavmod = float ((texture(sampler_noise_hq, vec2 (((rsl).x / float (16)))) - vec4 (0.500000))));
    float lavmod2 = float( texture(sampler_noise_hq, vec2 ((rsl / vec3 (16)))) );
    (lprof += lavmod);
    (rsl2 = (rsl + vec3(0, 0.030000, 0)));
    (lprof2 = float ((texture(sampler_noise_hq, ((rsl2).xy / vec2 (4))) - vec4 (0.750000))));
    (lprof2 += float ((texture(sampler_noise_hq, ((rsl2).xy / vec2 (2))) / vec4 (2))));
    (lprof2 += lavmod);
    (sun = clamp((0.020000 / length((uv2 - sunpos))), 0.0, 1.0));
    (rss = rs_sky((vec2 (tele) * uv1), sky_gnd));
    (sprof = noise2(rss));
    (sky_gnd -= ((sprof / (rss).z) * float (2)));
    (rss = rs_sky((vec2 (tele) * uv1), sky_gnd));
    (sprof = noise2(rss));
    (sky_gnd -= ((sprof / (rss).z) * float (2)));
    vec3 rss2 = vec3( (rss + vec3(0, 0.010000, 0)) );
    (sprof2 = noise2(rss2));
    (rsl = (vec3 (8) * rs_lav((vec2 (tele) * uv1), lav_gnd)));
    (noise = ((pow(noise4((rsl + vec3 ((ditch * lprof)))), (_qc).z) / (_qb).w) * float (2)));
    (lava = (nmod(vec2 ((((rsl + vec3 ((noise / float (2)))) * vec3 ((rand_preset).x)) / vec3 (2)))) + (ditch * float (0))));
    (lava *= mix(lprof, float (1), (_qd).x));
    float layers = float( ((pow(texture(sampler_noise_hq, vec2 ((vec3 (lprof) + (rsl / vec3 (4))))), vec4 (6)) * vec4 (0.250000)) * vec4 ((float (1) - ditch))) );
    (lava *= (float (1) + (layers * lavmod2)));
    (stone = ((float (1) - lava) * noise));
    (stone_lit = (lprof2 - lprof));
    (lavmask = (clamp((hordist - ((rsl).z / float (200))), 0.0, 1.0) * float (((rsl).z >= float (0)))));
    (ilavmask = clamp((float (1) - lavmask), 0.0, 1.0));
    (cldmask = clamp(((float ((-16)) / (rss).z) - 0.100000), 0.0, 1.0));
    (hormask = (clamp((abs((rss).z) / float (64)), 0.0, 1.0) * clamp((float (2) - (float (512) / (rsl).z)), 0.0, 1.0)));
    (hormask = (clamp((float (1) - (float (8) * abs(((uv1).y - 0.040000)))), 0.0, 1.0) / (_qh).x));
    (flashmask = float (clamp((vec4 ((hormask * float (4))) - (vec4 (2) * (vec4 (1) + rand_frame))), 0.0, 1.0)));
    (cloud = (((float (1) - sprof) * cldmask) * ilavmask));
    float ncloud = float( clamp((float (1) - (float (5) * cloud)), 0.0, 1.0) );
    float k1 = float( (clamp((_qd).z, 0.0, 1.0) + 0.010000) );
    float daylight = float( clamp(((k1 * (0.200000 + (_qh).y)) * float (3)), 0.0, 1.0) );
    float asym = float( (_qh).y );
    (hor = (daylight / length((uv2 - vec2((_qe).x, 0.100000)))));
    (sky = (ncloud * k1));
    vec2 rsk = vec2( (uv2 - planpos) );
    vec2 dz1 = vec2( normalize(rsk) );
    float rad3 = float( (float (12) * length(rsk)) );
    vec2 uv4 = vec2( (vec2 (tan(rad3)) * dz1) );
    vec2 noise = vec2( abs((texture(sampler_noise_hq, (uv4 / vec2 (2))) - vec4 (0.500000))) );
    float mask3 = float( clamp((float (32) - (float (22) * rad3)), 0.0, 1.0) );
    vec2 Planet = vec2( ((uv4 * vec2 ((float (1) + (noise).x))) * vec2 (mask3)) );
    vec3 col_hor = vec3( ((vec4 (1) + _c10) / vec4 (2)) );
    (ret1 = (vec3 (hor) * col_hor));
    (ret1 += vec3 ((sun * ncloud)));
    (ret1 *= vec3 (ilavmask));
    vec3 shine = vec3( (lavcol((0.100000 + (_qd).x)) + vec3 (0.100000)) );
    (ret1 += ((((col_hor * vec3 (cloud)) * vec3 (daylight)) * vec3 ((float (1) - (_qc).y))) + (shine * vec3 (cloud))));
    (ret1 += (lavcol(clamp((lava - (daylight * (float (1) - ditch))), 0.0, 1.0)) * vec3 (lavmask)));
    (ret1 += (vec3 ((stone * lavmask)) * (shine + vec3 ((0.500000 * daylight)))));
    (ret1 += ((vec3 ((((((0.500000 + stone) * (float (1) - ditch)) * stone_lit) * lavmask) * clamp((k1 * float (4)), 0.0, 1.0))) * (vec3 (1) + col_hor)) / vec3 (2)));
    float fl = float( 0 );
    (fl += ((float (8) * clamp(stone, 0.0, 1.0)) * lavmask));
    (fl += ((float (4) * clamp((float (1) - sprof), 0.0, 1.0)) * cldmask));
    (ret1 += ((vec3 (fl) * vec3(0.700000, 0.400000, 1)) * vec3 ((_qf).x)));
    ((ret1).b += (((lavmask * clamp((-(_qd).z), 0.0, 1.0)) * clamp(((-(_qd).x) * float (2)), 0.0, 1.0)) * (uv1).y));
    (ret1 = (ret1 + vec3 ((((((ilavmask * clamp((float ((-1)) + (float (1) * dot(Planet, normalize((sunpos - planpos))))), (-0.100000), float (4))) * mask3) / float (2)) * ncloud) * (float (1) - daylight)))));
    vec3 fogcol = vec3( mix(shine, vec3 (1), vec3 (daylight)) );
    (ret1 = mix(ret1, (vec3 (1) * fogcol), vec3 ((hormask * (_qc).w))));
    (k1 = (((_qh).x - float (1)) / float (6)));
    (ret = (vec3 (1) - exp(((-ret1) * vec3 (2)))));
    (_return_value = vec4((ret).xyz, 1.000000));
}
void main() {
    vec4 _vDiffuse;
    _vDiffuse = frag_COLOR;
    vec4 _uv;
    _uv = frag_TEXCOORD0;
    vec2 _rad_ang;
    _rad_ang = frag_TEXCOORD1;
    vec4 _return_value;
    quality = float( 3 );
    depth = float( 0.200000 );
    lav_gnd = float( 0 );
    hordist = float( (float (3) + (_qb).w) );
    tele = float( (_qh).x );
    sky_gnd = float( (_qd).w );
    mov = vec2( vec2((_qb).x, (_qb).y) );
    sunpos = vec2( vec2((_qe).x, (_qe).y) );
    planpos = vec2( vec2(((_qe).x + 0.500000), (_qh).w) );
    skycol = vec3( vec3(0.100000, 0.100000, 0.200000) );
    PS(_vDiffuse, _uv, _rad_ang, _return_value);
    rast_FragData[0] = _return_value;
}

Successfull compilation of Comp

======

beta106ain-roto-mix3.milk : Black screen

Geiss - Blasto.milk : Extremely pixelated

Goody + martin - crystal palace - Schizotoxin - The Wild Iris Bloom - mess2 nz+ i have no character and feel entitled to one.milk : Black screen with occasional orange flicker

Rovastar + Geiss - Hurricane Nightmare.milk : Black screen

Unchained - French Clothing.milk : Black screen (but with graceful transition)

**Comment by rothn** [comment]
If I can kill off presets in a PR by just removing them, I will issue such a PR if you'd like. Going to track what I see here... This has been bugging me too long

**Comment by rothn** [comment]
Can I make a PR without being p

**Comment by revmischa** [comment]
Yes please just open a PR. No process. Thanks!

**Comment by revmischa** [comment]
rm martin - adrift on a dead planet - lard mix.milk
