### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by revmischa** [projectM-visualizer/projectm#19]
Try to get projectM building on windows, most likely with visual studio but whatever works.

Use the `glsl` branch

To build projectM you need to build in libprojectM:
* Renderer
* NativePresetFactory
* MilkdropPresetFactory
* libprojectM
as libraries.

Then build projectM-sdl and link it against those libraries. You'll need libsdl2
Most likely you will need a few other libraries too, like libftgl and libz, and need to link against OpenGL.

Make sure the proper windows define is set for all the header `#ifdef`s to work right

**Comment by korfuri** [comment]
Did you mean to close this? AFAICT this has not been solved yet.

**Comment by revmischa** [comment]
I haven't personally built it on windows, but @mancoast has and it's in the windows app store and also in the latest release.
