### ISSUE TITLE
Windows 10 Audio Output Support (stand alone)

### ISSUE THREAD

**Issue by leminsc8er** [projectM-visualizer/projectm#192]
i think a Audio Output for windows 10 (stand alone) Multicross App are easy to install and use for some apps on OS like 
VLC,  Firefox (Soundcloud, Radio,...), Aimp, Spotfy, Skype,  and many more!

**Comment by mancoast** [comment]
Windows system audio is captured in the new windows store app, see here https://github.com/projectM-visualizer/projectm/issues/199

**Comment by mancoast** [comment]
complete
https://github.com/projectM-visualizer/projectm/commit/213d2507a7234c201b10411a1ab54edf9bf6ef98
