### ISSUE TITLE
Android Pie Dark Theme not on when set as Live Wallpaper

### ISSUE THREAD

**Issue by coltaku** [projectM-visualizer/projectm#195]
The issue is that even with Dark Theme on no matter what, when setting this as the wallpaper it defaults to the white theme instead. Other Live Wallpapers work with keeping the dark theme but not Project M. The notification bar and app drawer stay white. Please fix this so I can have this as my background!

**Comment by kblaschke** [comment]
Old issue, but sound like it's about the Google Play Store app, which is developed as closed-source by Peter Sperl. Not much we can do about it, please ask the author directly via the contact means provided in the app or in the store.
