### ISSUE TITLE
Overlay track / song data / information

### ISSUE THREAD

**Issue by SimonDedman** [projectM-visualizer/projectm#2]
Hi. Is there a way to have ProjectM overlay information about the currently playing track? From what I understand about the way PM works, I suspect this isn't a no-brainer?

Cheers

**Comment by revmischa** [comment]
Sure, I believe it's up to the application to do that though. Which version of projectM are you using?

**Comment by SimonDedman** [comment]
Sorry Rev, dunno why I didn't get a notification email for your reply!
My version is: projectm-pulseaudio 2.1.0+dfsg-3build1 (any chance you could put this in the 'about' box in future? cheers!). I've downloaded the latest version from github but I've scoured github and sourceforge and the files and can find no reference to what the latest version is.... am I being a complete dumbass or is it not written anywhere?
Currently using banshee which gives me the option of popping up a notification when the track changes (I think? I know Rhythmbox does/did), but I don't use it and
1. I think it's hidden if projectM is fullscreen?, and
2. often enough I'll have PM on fullscreen when I'm entertaining and don't want the screen showing, but will occasionally want to see what a track is.
Cheers for your reply and your awesome work!!!

**Comment by revmischa** [comment]
Okay, honestly I don't know anything about the pulseaudio version, the PA app is a wrapper around projectM. I believe the overlay stuff is all implemented by the derivative applications, not the core projectM library (though I may be wrong?). I think if you want overlay info in the PA version, whoever maintains that might be the person to bug. Or you can try building that version yourself. Let me know if you need assistance because cmake is a pile of garbage.

**Comment by SimonDedman** [comment]
Haha no worries - I reckon if I need it I'll just try to work out how to
have banshee post notifications on track changes or something similar. Not
a life-ending problem!

One thing, since we're chatting, it would be cool to be able to customise
keyboard shortcuts. I just can't program my brain to remember that
everything's ctrl+?, since  figure there are so few hotkeys it would just
be F for fullscreen, left & right arrows to change viz patterns, space to
pause, etc..

Cheers!

**Comment by revmischa** [comment]
Sure, but again, this is up to the application not the core projectM library. projectM is not dependent on any particular event handling system. If you want to modify one of the applications, like the osx iTunes plugin or the SDL version I may be able to help.

**Comment by SimonDedman** [comment]
Huh. I guess I don't have a strong understanding of which bit projectM
actually *is*!
I'm using the linux version; I launch it as a standalone separate from
banshee (or rhythmbox or whatever, I suppose) and the window's entitled
"projectM" and 'help > hotkey reference' brings up the dialogue box which
tells you what the keyboard shortcuts are.

Again, no worries if this isn't an easy fix. Thanks again.

**Comment by revmischa** [comment]
There is libprojectM which is a library that takes raw PCM audio samples as input and then draws visualizations to an openGL surface or texture as output. There are many other applications that USE libprojectM but provide the more plugin- or OS-specific interfaces to audio, keyboard events, openGL context creation, etc.
