### ISSUE TITLE
What's your relation to projectM on SourceForge?

### ISSUE THREAD

**Issue by yurivict** [projectM-visualizer/projectm#20]
https://sourceforge.net/projects/projectm/

**Comment by revmischa** [comment]
Same project, the code here is newer. The sourceforge page is supposed to be shut down but the admin is not very responsive.

**Comment by yurivict** [comment]
So is your v0.9.2-beta newer than 2.1.0 on SourceForge?

**Comment by revmischa** [comment]
I've been releasing binary builds for OSX/iTunes and recently a semi-working SDL2 version. The version on sourceforge is more about libprojectM than particular binaries. The library code is more up to date here but there's no "release" of it.
The latest stuff is in branches.

**Comment by revmischa** [comment]
sourceforge is redirected here now yay
