### ISSUE TITLE
macOS Standalone not working? 

### ISSUE THREAD

**Issue by itsdoreiku** [projectM-visualizer/projectm#202]
I'm probably just missing an obvious step but I can't seem to figure out how to get the projectM SDL app to capture audio.  The iTunes plugin works fine but I'd much rather use this with other audio sources.  Do I need to install any other components/dependencies as in previous releases or am I missing something else?

I was attempting to search around and remedy this myself; Aside from reading that libsdl2 audio capture **has** indeed been implemented, I was struggling to find much coverage over this version of the app, which I guess makes sense considering that it's still pre-release.

If there's any straightforward documentation that covers how to configure the current version of the macOS standalone app (which is 3.1.1-rc3 at the time of writing this) that I just happened to overlook, I would greatly appreciate a link.

Thank you! :)

**Comment by mancoast** [comment]
I think you seek audio loop back on the os audio render device.

**Comment by itsdoreiku** [comment]
So I DO need something external like Soundflower then?  Even so, I'm not really sure what to do from there.  Pretty sure I've already got Soundflower set up and configured anyway.  Here's what my audio settings look like.  "Onyx Blackjack" is my lil 2x2 audio interface.  The aggregate device I've created is set to be the default for output, input, and sound effects.

![Screen Shot 2019-05-02 at 12 10 56 PM](https://user-images.githubusercontent.com/50214062/57100328-83675f80-6cd3-11e9-9ef9-3c1a94c1a638.png)

**Comment by revmischa** [comment]
I'm pretty sure you want soundflower yes. You need to select the audio input device you want the SDL app to read from. There is a ticket to make this easier: #30

**Comment by itsdoreiku** [comment]
Cool!  So from here I need to actually go edit the code to specify the audio input device?  I read that this specific bit of code is supposed to be in pmSDL.cpp but I'm unable to locate it.

Would you rather me continue to discuss this in ticket #30 so this seemingly unnecessary ticket can be closed?

**Comment by revmischa** [comment]
Sure let's
