### ISSUE TITLE
include mic input for windows store app

### ISSUE THREAD

**Issue by ghost** [projectM-visualizer/projectm#206]
enable uwp mic capture using wasapi
enable option to select audio source

**Comment by karlthepagan** [comment]
Selecting the audio source would be extremely useful. I utilize Voicemeeter in order to route my audio for livestreaming, to apply VST/EQ, and correct defects in some applications.

With an input selection (using Windows' Sound Settings) I could mix my applications with my voice for visualization.

**Comment by revmischa** [comment]
Ctl-I lets you select the source on pmSDL now
