### ISSUE TITLE
LGPL and these libraries

### ISSUE THREAD

**Issue by teotigraphix** [projectM-visualizer/projectm#209]
Hi,

Reading through a lot of the older writing and things. You mention an Android/iOS app that is available commercially using project m or derivative / altered code?

If so, I really want to know if this is a violation of a license or is the dev using some other framework version/iteration that doe not have to publish changes of the open source framework he is using.

If this dev is in violation, I want to do something about it, if not, sorry for the noise.

**Comment by teotigraphix** [comment]
BTW I am working on iOS/Android and should have some contributions to get iOS going as well.

**Comment by revmischa** [comment]
See: https://github.com/projectM-visualizer/projectm/pull/70#issuecomment-481523500

I think LGPL is more permissive than GPL about such things. I don't know if it is a violation or not.

**Comment by teotigraphix** [comment]
Alright, that thread gives a bit more context, thanks.
