### ISSUE TITLE
configure breaks in Bourne shell: Syntax error: redirection unexpected (expecting word)

### ISSUE THREAD

**Issue by yurivict** [projectM-visualizer/projectm#210]
```
checking for a sed that does not truncate output... (cached) /usr/bin/sed
./configure: 18835: Syntax error: redirection unexpected (expecting word)
===>  Script "configure" failed unexpectedly.
```

Offending line:
```
if grep android <<< ${host}; then :
```

By the definition of GNU tools ```configure``` should be Bourne shell compatible, otherwise it isn't compatible with many systems, ex. BSDs.

**Comment by v0idkr4ft** [comment]
having same issue, any resolutions?

**Comment by revmischa** [comment]
what's a more portable way to write it?

**Comment by yurivict** [comment]
```if grep android <<< ${host}; then```
should be
```if grep ${host} android > /dev/null 2>/dev/null ; then```

**Comment by revmischa** [comment]
I believe now it's
`AS_IF([echo ${host} | grep -Fq android], [],`
https://github.com/projectM-visualizer/projectm/blob/master/configure.ac#L152
