### ISSUE TITLE
moc fails: Unknown option 'isystem'.

### ISSUE THREAD

**Issue by yurivict** [projectM-visualizer/projectm#211]
I'm getting this on FreeBSD 12 with qt5-buildtools-5.12.2, projectm-3.1.1-rc4:
```
/usr/local/bin/moc -oqpresettextedit_moc.cpp -DHAVE_CONFIG_H -I. -I../..  -fno-omit-frame-pointer -isystem /usr/local/include qpresettextedit.hpp
Unknown option 'isystem'.
Unknown option 'isystem'.
```

**Comment by yurivict** [comment]
I think moc doesn't want CFLAGS/CXFLAGS passed to it.

**Comment by mancoast** [comment]
Have you tried qt meta object compiler without the system includes flag? The other flags might be required.

**Comment by yurivict** [comment]
No, I do build in a default way.

**Comment by revmischa** [comment]
Is this resolved? please reopen if not
