### ISSUE TITLE
Project Structure and Building

### ISSUE THREAD

**Issue by teotigraphix** [projectM-visualizer/projectm#213]
Alright, I have many ideas to add to this project but I am lost on the building.

I have no experience with Linux, only server side work in the past.

I just need a bit of guidance to get the libraries building. So it's not that I "need" a certain project to work, I want to get libraries compiled that I can use in the external projects for Windows and Android (iOS eventually).

I have the .so from the example Android project but @PeterMalkin built that before he committed the project. (I am guessing)

I use Android Studio and Visual Studio on Windows.

Newbie build help. :) (I have never built a C/C++ project that was setup like this)

**Comment by PeterMalkin** [comment]
@teotigraphix 

Building the library for Android is described here:https://github.com/projectM-visualizer/projectm/blob/master/BUILDING.md

In particular, you need to:
1) git clone this project
2) Install Android Studio
3) Launch SDK Manager and install NDK
4) start a shell, change directory into the forlder of the porject and then run `./autogen.sh`. Many lines will be printed. Look for errors and try to fix. YOu may need to install some libraries or dependencies
5) run `./configure-ndk`
6) run `make && make install-strip` the library will be copied into the folder with android app

**Comment by teotigraphix** [comment]
Alright, I am looking at way too much stuff, I did not see that build info for Android, I am blind. 

4, 5 and 6 is what I was missing. :) Thank You!

**Comment by teotigraphix** [comment]
Ah, ok I am lazy eye or ape trained, usually I am used to reading the Build instructions in the README, and that was not the place to look, and thus I totally glossed over the BUILDING.md file. My bad.

**Comment by teotigraphix** [comment]
For others, I feel really dumb for creating an issue when there is a BUILDING.md file. But it happens. :)

**Comment by revmischa** [comment]
Link to it in the README!

**Comment by teotigraphix** [comment]
@revmischa Yeah I know(pull request), it's been a while since I have worked on OS projects, but I have a lot. Just need to get back into the swing of things.

**Comment by teotigraphix** [comment]
I cannot get this to build using the build instructions; It fails; 

I am running this in MSYS264 shell.

First run after clone.

```
Mike@DESKTOP-BINJH6B MINGW64 /c/dev/osprojects/projectM
$ ./configure
configure: loading site script /mingw64/etc/config.site
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking how to create a pax tar archive... gnutar
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for ar... ar
checking the archiver (ar) interface... ar
checking build system type... x86_64-w64-mingw32
checking host system type... x86_64-w64-mingw32
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... C:/msys64/mingw64/x86_64-w64-mingw32/bin/ld.exe
checking if the linker (C:/msys64/mingw64/x86_64-w64-mingw32/bin/ld.exe) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /mingw64/bin/nm -B
checking the name lister (/mingw64/bin/nm -B) interface... BSD nm
checking whether ln -s works... no, using cp -pR
checking the maximum length of command line arguments... 8192
checking how to convert x86_64-w64-mingw32 file names to x86_64-w64-mingw32 format... func_convert_file_msys_to_w32
checking how to convert x86_64-w64-mingw32 file names to toolchain format... func_convert_file_msys_to_w32
checking for C:/msys64/mingw64/x86_64-w64-mingw32/bin/ld.exe option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... file_magic ^x86 archive import|^x86 DLL
checking for dlltool... dlltool
checking how to associate runtime and link libraries... func_cygming_dll_for_implib
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /mingw64/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... no
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -DDLL_EXPORT -DPIC
checking if gcc PIC flag -DDLL_EXPORT -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (C:/msys64/mingw64/x86_64-w64-mingw32/bin/ld.exe) supports shared libraries... yes
checking whether -lc should be explicitly linked in... yes
checking dynamic linker characteristics... Win32 ld.exe
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking whether to use rpath... yes
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... C:/msys64/mingw64/x86_64-w64-mingw32/bin/ld.exe
checking if the linker (C:/msys64/mingw64/x86_64-w64-mingw32/bin/ld.exe) is GNU ld... yes
checking whether the g++ linker (C:/msys64/mingw64/x86_64-w64-mingw32/bin/ld.exe) supports shared libraries... yes
checking for g++ option to produce PIC... -DDLL_EXPORT -DPIC
checking if g++ PIC flag -DDLL_EXPORT -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (C:/msys64/mingw64/x86_64-w64-mingw32/bin/ld.exe) supports shared libraries... yes
checking dynamic linker characteristics... Win32 ld.exe
checking how to hardcode library paths into programs... immediate
./configure: line 16302: PKG_PROG_PKG_CONFIG: command not found
./configure: line 16485: syntax error near unexpected token `GL,gl,'
./configure: line 16485: `          PKG_CHECK_MODULES(GL,gl,'
```

Next;


```
Mike@DESKTOP-BINJH6B MINGW64 /c/dev/osprojects/projectM
$ ./configure-ndk
configure: loading site script /mingw64/etc/config.site
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for arm-linux-androideabi-strip... /home/Mike/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking how to create a pax tar archive... gnutar
checking whether make supports the include directive... yes (GNU style)
checking for arm-linux-androideabi-gcc... /home/Mike/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi19-clang
checking whether the C compiler works... no
configure: error: in `/c/dev/osprojects/projectM':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

Where is the `config.log`?

**Comment by PeterMalkin** [comment]
It seems like you are using cygwin? I am sorry, I have not tried this. I built natively on Linux.

"checking for arm-linux-androideabi-gcc... /home/Mike/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi19-clang
checking whether the C compiler works... no
configure: error: in `/c/dev/osprojects/projectM':
configure: error: C compiler cannot create executables"

This basically means that your installed toolchain cannot produce executables. 
If you want to cross compile the library for Android under windows - you may need to do some digging on your own. I dont have a windows machine I could try it on.

**Comment by teotigraphix** [comment]
Hi @PeterMalkin, I was using MSYS2 MinGW 64 shell.

Alright, and you can now see why I made this issue since this is a foreign language to me atm(toolchain). I will do research and hope to report back on how to compile this with windows.

**Comment by PeterMalkin** [comment]
Sorry, I could not have been of more help. Dont have a windows machine (actually havent had one for over a decade now).
One thing you could also try - Docker should run on Windows. So you could avoid to use Windows cross compiler and use normal Android toolchain (albeit still a cross compilation one)

**Comment by teotigraphix** [comment]
Just FYI, I could not even get close to building this on Windows. I just don't know enough Linux crossover to Windows to even understand how to get it working. (Never used Docker either)

**Comment by PeterMalkin** [comment]
@teotigraphix 
I guess I do not quite understand why do you care so much about building the library for Android on Windows. All you do is to add the .so into the resources of your apk. And then you can develop your Android app in java on any system you want, including Windows.

So can you may be explain more - what are you trying to accomplish?

**Comment by teotigraphix** [comment]
I don't like working on things I can't build. What I am trying to do is be able to build the platforms I use so I can add functionality to the framework or fix bugs.

If I add API or functionality, I need to be able to add the C decl hooks, this work needs a recompiled .so (library). I am doing this to try and get dirty with this code, so if I cannot add or compile a library, what is the point.

I am interested in the mechanics of the project, not the surface API as much right now. So adding things is how I learn, right now I can't add anything at the bare metal level and test it.

**Comment by teotigraphix** [comment]
@mancoast Thanks, I have projectm open in VS 2017 and see the commands in the yml file

I switched issues so not to spam the other preset thread.

**Comment by PeterMalkin** [comment]
@teotigraphix 
I see. Makes sense.
