### ISSUE TITLE
Reference for keybinds, command line parameters?

### ISSUE THREAD

**Issue by JPLeBreton** [projectM-visualizer/projectm#217]
I can launch the demo program in both Windows and Linux, but it doesn't seem to respond to any keyboard input, and I can't tell which command line parameters, if any, the program accepts. Is this documented anywhere?

**Comment by mancoast** [comment]
This is something that needs attention as many users, including yourself @JPLeBreton, have brought up in the short time ive been involved here. There is a key handler at the library level of projectm thats common to all the applications that make use  of the library (projectm-sdl, etc..)  It would be excellent to update the readme with these keys.  I think N is next, P is previous and other miscellaneous key bindings. 

Would you like to get involved and help us by contributing to the readme file?

**Comment by nttan2805** [comment]
> I can launch the demo program in both Windows and Linux, but it doesn't seem to respond to any keyboard input, and I can't tell which command line parameters, if any, the program accepts. Is this documented anywhere?

**Comment by kblaschke** [comment]
Keyboard shortcuts for the already released SDL frontend can now be found in the Wiki.

The rewritten SDL app will support more configuration settings and also command line parameters.

Closing the issue.
