### ISSUE TITLE
0.9.1 seems to have stopped working (itunes 12.7 on osx 10.12.5)

### ISSUE THREAD

**Issue by tobeamplified** [projectM-visualizer/projectm#22]
...and I am unable to test the new version as I am no programmer, never built any software from binaries - is there some guide to it - or are you planning on putting a build (pkg) up?

**Comment by revmischa** [comment]
https://github.com/projectM-visualizer/projectm/issues/12
https://github.com/projectM-visualizer/projectm/issues/7

Re-building won't help. Someone needs to find out what's wrong. I tried and couldn't figure it out. Sorry :(

**Comment by tobeamplified** [comment]
hopefully this helps to get apple's attention - I'm pretty annoyed they keep breaking things and won't release documentation

https://www.reddit.com/r/apple/comments/7fqhcn/projectm_the_best_visualizer_for_itunes_127_has/

**Comment by revmischa** [comment]
I wrote something a while ago https://spiegelmock.com/2014/10/30/apple-treats-developers-like-dogs/

There IS a semi-working SDL2 version that is standalone. It renders audio input, not iTunes. Runs on OSX. Give it a try if you want.

**Comment by revmischa** [comment]
Tracking this in #7
