### ISSUE TITLE
Render visualisation to file?

### ISSUE THREAD

**Issue by POMATu** [projectM-visualizer/projectm#221]
Hi, I want to use visualisations as background for my video.

Is it possible to render all that cool stuff to videofile without developing software from scratch? When I googled any possible solution to this issue I found only instructions how to record a screencast. When I am recording screen I get laggy result. I was thinking even about buying a HDMI recorder, however my PC can't render smoothly 2048x2048 35 fps even without screencasting

So I wonder is it possible to just render it over wav file like in any video editor, even if it take 2 hours, but get clear smooth detailed result without lags?

Thanks

**Comment by revmischa** [comment]
A question several have asked: #205 
Hopefully someone implements it!

**Comment by POMATu** [comment]
Thanks for fast response!
:( ordering HDMI recorder then and searching for hi-end PC...

**Comment by POMATu** [comment]
btw tried fraps on w1nd0ws to catch opengl frames it was even worse than on linux with kazam, HDMI recorder gonna be really useful
