### ISSUE TITLE
Pop!_OS ProjectM for pulseaudio crashes consistently and at preset change

### ISSUE THREAD

**Issue by maegitech** [projectM-visualizer/projectm#222]
Title summarizes my issue; I am using an Ubuntu-based Linux distro, Pop!_OS. I installed it from the app store of my distro (Pop!_Shop), it's hosting v2.1.0. ProjectM starts, can go full screen, open preset menu, and open settings menu. If I attempt to change presets, it crashes. If the program runs for up to 60 seconds, it crashes. I'm not sure why this is happening.

**Comment by revmischa** [comment]
Ubuntu/debian has a very old version sadly. Maybe try building something more recent?

**Comment by maegitech** [comment]
I just built v3.1.0 from source but I'm not sure how to open ProjectM now. I normally install via the app store or `apt-get`, which automatically adds shortcuts to my start menu.

**Comment by revmischa** [comment]
Look for an executable in src/projectm-sdl

**Comment by maegitech** [comment]
I can change presets without crashing. ProjectM doesn't crash after 60 seconds anymore. Thank You, issues have been resolved!
