### ISSUE TITLE
Presets mega pack by m.talbot @xdva

### ISSUE THREAD

**Issue by bebop210** [projectM-visualizer/projectm#223]
Any chance we will see the monsiourtalbot mega pack of presets for android or any device really? This has been thrown around for years and the Talbot pack download link has gone dark for months.  Please help

**Comment by mancoast** [comment]
Greetings @bebop210 
Do you have a cached copy of these presets to contribute?
Would you like to add them to the repo here so we can further investigate and you can become a member of our team?

Thanks,
Coast

**Comment by bebop210** [comment]
I posted the super zip of 52,000 presets I’ve kept in my Dropbox.. these are for milkdrop2 but as per monsiourtalbot’s notes a lot work with projectm with no editing or conversion needed.
