### ISSUE TITLE
Is there a way with root to visualize music playing from internal audio?

### ISSUE THREAD

**Issue by POTOFGREED** [projectM-visualizer/projectm#231]
Is there a way with root to visualize music playing from internal audio rather than what the microphone is listening, so you can use headphones and visualize what you are listening in the headphones and not pickup input from the microphone?

**Comment by coast77777777777** [comment]
Root? Are you talking about android?

**Comment by POTOFGREED** [comment]
Oh shit yeah should have specified android pie rooted with latest stable magisk 19.3, i want to visualize music that is being played on my earbuds without microphone access, somehow for the phone audio to be streamed to the microphone input.
