### ISSUE TITLE
What are the System Requirements?

### ISSUE THREAD

**Issue by DJPlaya** [projectM-visualizer/projectm#236]
I am an Lighting Professional and i am planning to use ProjectM with many Screens and Projectors.
To build an Computer with many Video Ports i first need to know what System Requirements ProjectM has.
There are many cheap Matrox GPU´s on the Web, but most of them with only a slow Clockrate and 128mb Memory. If its not about the CPU and RAM + Recource sharing beeing disabled, what would be the minimum Requirements for ProjectM per Viewport?
I know this depends on the Visualization running, but it would be good to have at least an Idea of it before buying multiple GPUs.

**Comment by coast77777777777** [comment]
What Operating system are you running on your computer? welcome and this sounds interesting, how many monitors total are you considering?

**Comment by DJPlaya** [comment]
Win 10 or Server 2019 propably
Ime planning to use 4-8 all in a 4:3 Ratio at XGA

**Comment by revmischa** [comment]
Some of the visualizations are CPU-based and some are GPU-based. You need something that supports either OpenGL 4 or OpenGL ES 3. The more CPU clockspeed the better.
