### ISSUE TITLE
Tried to build, no executable to be found

### ISSUE THREAD

**Issue by fvdfgrgtg42etgfw** [projectM-visualizer/projectm#237]
Ubuntu only hosts 2.1.0, which crashes on 19.04. Downloaded one of the newer versions, followed the Linux build instructions (not a git clone), looked in the recommended binary folder from issue #222 (src/projectm-sdl in extracted tarball's folder), binary does not exist, tried moving the folder and recompiling, difference in time taken and output implies it's already compiled and in a most-likely-user-inaccessible (based on my speculation) folder.

Only saved the second ("""recompile""") log.

**Comment by revmischa** [comment]
When you run `./configure` does it say at the end that it will build the "SDL" version? it will only build the binary in src/projectm-sdl/ if you have the appropriate libsdl2-dev (i think?) library installed before running `./configure`

**Comment by fvdfgrgtg42etgfw** [comment]
Update, forgot to post at that time and it's too late, but anyway, I read an issue by another person who had the same problem and it turns out the ""latest"" version in the repository is very old, so I downloaded and compiled the real latest version. It initially had no sound, but I looked into the PulseAudio settings and found ProjectM tried to listen to the mic (input) while it's disabled, so I switched it to the system sound (output) and now the visualizations respond to the music..

**Comment by fvdfgrgtg42etgfw** [comment]
Reopening because tried compiling again on a new Xubuntu install and first, stumped about which package is the "which" dependency because it's mentioned nowhere in this repo or the Internet outside the readme.md. When I try compiling it with all the **available** dependencies referenced, it returns no obvious errors but creates no binary in the system binary folder or projectM-sdl.
