### ISSUE TITLE
Feature request: ability to enable/disable presets and/or add custom ones on Android TV

### ISSUE THREAD

**Issue by honestbleeps** [projectM-visualizer/projectm#242]
I've only tried this on Android TV, but I am gathering based on reading other issues that the other versions may already have this.

More extensive configuration options on Android TV would be much appreciated.  Right now, the settings available are quite minimal.  I'd absolutely love to be able to disable presets I don't care for (e.g. the stick figure one), and/or add new ones!

**Comment by coast77777777777** [comment]
we have no control over the android store app
