### ISSUE TITLE
How in christ do i get the command keys to work.

### ISSUE THREAD

**Issue by RainbowShadow98** [projectM-visualizer/projectm#244]
i can't use any of the command keys to control what the system does

**Comment by revmischa** [comment]
Which ones are you referring to?
I added cmd/ctrl - Q to quit recently for SDL - https://github.com/projectM-visualizer/projectm/commit/0996a06b4c3acf563f9448953ff26d3d8904d583#diff-09d1c7e1b1880dddbb7b928c96c28b2bR176

Can you please elaborate?

**Comment by RainbowShadow98** [comment]
Like m for menu and all those

**Comment by revmischa** [comment]
projectM is a library, which application are you using? i don't know if any have a menu. 
the README could use updating: https://github.com/projectM-visualizer/projectm/issues/217
