### ISSUE TITLE
Compiled projectMSDL references src in ELF rpath

### ISSUE THREAD

**Issue by Anton-Latukha** [projectM-visualizer/projectm#245]
I am a NixOS maintainer working on packaging projectM updatating it from pretty old version to today.

Current master, build d1314d0512a343a120e09d76795550da8e1fab42, doind it with `configure` flags: `--enable-qt`, `--enable-sdl`.

Resulting are binaries `projectMSDL` and `projectM-unittest` that are referencing in the run-time search path the:
```fish
patchelf --print-rpath projectMSDL | tr ':' '\n'
...
/build/source/src/libprojectM/.libs
```

**Comment by Anton-Latukha** [comment]
In other words, during the compilation process binary decides to save a reference to the build-time path in the contained environment on CI build cluster, or another build environment.

This may be a slip, or it may be a dev hack that included in the compiled package.

NixOS atomic functional packaging relies on proper `rpath`s and at the same time very strict to ironing-out all out of order cases, so `rpath` references are checked by build system, and build tool-chain reports (and indeed not package) when compiled binary references to resources that do not exist in the shipment package, during installation and usage of the project. Because the build system detects run-time lib dependencies through ELF `rpath`s and automatically supplies them. In the case when project references it's own source directory as a resource - then a) build system must automatically assume it as a resource & package & ship the source code with compiled binaries b) assume that it is a strange case of self-reference that should be resolved. 

`rpath` referencing the source is an infriquent case.

The "peoples" solution for "maintainer" is to just add automatic `patchelf --set-rpath ` with automatic autodetected set of paths and never report about it upstream, because it can be argumented and argued for a long time that this is just a thing that works and should work in default Linux distributions and environments, and NixOS just happens to be pedantic case with requirements to have a pure & reproducible builds.

But I also think that you should be informed that project binaries have hard-coded ELF paths to source folder it was built from. And that is what I was required to troubleshoot to provide the `projectM` to NixOS, or what would be picked-up also in `Guix` or `Dhall` functional package languages/managers.

**Comment by coast77777777777** [comment]
Thank you for your contributions here. Do you need anything for support to complete the package maintenance?

**Comment by Anton-Latukha** [comment]
Referencign herem, since I always document the special code for the future generations.

If reader interested, it is something in these lines:
```shell
for entry in $out/bin/* ; do
  patchelf --set-rpath "$(patchelf --print-rpath $entry | tr ':' '\n' | grep -v 'src/libprojectM' | tr '\n' ':')" "$entry"
done
```

PR should be merged. Everything resulted successfully.

**Comment by revmischa** [comment]
Thanks for the info and your maintainership in Nix - yes that rpath is incorrect. If you want to submit a PR to fix it here it would be greatly appreciated. I don't think it will break anything if you do.
