### ISSUE TITLE
osx build fails, ftgl not found

### ISSUE THREAD

**Issue by conciousweb** [projectM-visualizer/projectm#25]
Followed your instructions, also tried to install a different ftgl from github in the regular way and still get this:

[ 83%] Linking CXX executable projectMSDL
ld: library not found for -lftgl
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/projectM-sdl/projectMSDL] Error 1
make[1]: *** [src/projectM-sdl/CMakeFiles/projectMSDL.dir/all] Error 2
make: *** [all] Error 2

Also, your most recent app installer fails to appear in itunes 12.6.2.20 / osx 10.9.5

**Comment by revmischa** [comment]
Hm, I'm not sure what the problem is but maybe try grabbing the libs from projectM-iTunes/macos/contrib and see if they work? Probably a cmake issue. Try the `build` branch that uses `make` perhaps?

**Comment by revmischa** [comment]
Okay you're right, I just tried to do a cmake build on master and encountered the same thing. The main problem is that cmake sucks. I've been trying to replace it with normal `make` and another person was taking a shot at setting up autotools.

To get it to build, do `ccmake .`, disable `USE_FTGL`,   hit `c`, then `q` and then build. It should compile.

<img width="647" alt="screen shot 2018-01-25 at 15 30 01" src="https://user-images.githubusercontent.com/245131/35376193-dc1bbcbc-01e4-11e8-9f39-4c735c39f416.png">

Maybe try disabling USE_FTGL by default so others don't run into this?

We're on #projectM on freenode if you want to chat. Cheers!

**Comment by revmischa** [comment]
Thanks to #27 now you can use autotools to build. Try out projectM-sdl
