### ISSUE TITLE
Visual Studio linker error due to multiply defined definitions.

### ISSUE THREAD

**Issue by r-hackett** [projectM-visualizer/projectm#254]
Using Visual Studio 2017, when compiling projectMSDL the linker complains of multiple definitions.

Output:
`1>pmSDL.obj : error LNK2005: "struct std::_Distance_unknown __cdecl std::_Idl_dist_add(struct std::_Distance_unknown,struct std::_Distance_unknown)" (?_Idl_dist_add@std@@YA?AU_Distance_unknown@1@U21@0@Z) already defined in projectM_SDL_main.obj
1>pmSDL.obj : error LNK2005: "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl parseExtension(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?parseExtension@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV12@@Z) already defined in projectM_SDL_main.obj
1>pmSDL.obj : error LNK2005: "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl parseFilename(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?parseFilename@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV12@@Z) already defined in projectM_SDL_main.obj
1>pmSDL.obj : error LNK2005: "double __cdecl meanSquaredError(double const &,double const &)" (?meanSquaredError@@YANAEBN0@Z) already defined in projectM_SDL_main.obj
1>pmSDL.obj : error LNK2005: "enum projectMEvent __cdecl sdl2pmEvent(union SDL_Event *)" (?sdl2pmEvent@@YA?AW4projectMEvent@@PEATSDL_Event@@@Z) already defined in projectM_SDL_main.obj
1>pmSDL.obj : error LNK2005: "enum projectMKeycode __cdecl sdl2pmKeycode(int)" (?sdl2pmKeycode@@YA?AW4projectMKeycode@@H@Z) already defined in projectM_SDL_main.obj
1>pmSDL.obj : error LNK2005: "enum projectMModifier __cdecl sdl2pmModifier(enum SDL_Keymod)" (?sdl2pmModifier@@YA?AW4projectMModifier@@W4SDL_Keymod@@@Z) already defined in projectM_SDL_main.obj
1>pmSDL.obj : error LNK2005: "enum GETPROPERTYSTOREFLAGS & __cdecl operator|=(enum GETPROPERTYSTOREFLAGS &,enum GETPROPERTYSTOREFLAGS)" (??_5@YAAEAW4GETPROPERTYSTOREFLAGS@@AEAW40@W40@@Z) already defined in projectM_SDL_main.obj
1>pmSDL.obj : error LNK2005: "enum GETPROPERTYSTOREFLAGS & __cdecl operator&=(enum GETPROPERTYSTOREFLAGS &,enum GETPROPERTYSTOREFLAGS)" (??_4@YAAEAW4GETPROPERTYSTOREFLAGS@@AEAW40@W40@@Z) already defined in projectM_SDL_main.obj
1>pmSDL.obj : error LNK2005: "enum GETPROPERTYSTOREFLAGS & __cdecl operator^=(enum GETPROPERTYSTOREFLAGS &,enum GETPROPERTYSTOREFLAGS)" (??_6@YAAEAW4GETPROPERTYSTOREFLAGS@@AEAW40@W40@@Z) already defined in projectM_SDL_main.obj
1>pmSDL.obj : error LNK2005: "enum PROPDESC_TYPE_FLAGS & __cdecl operator|=(enum PROPDESC_TYPE_FLAGS &,enum PROPDESC_TYPE_FLAGS)" (??_5@YAAEAW4PROPDESC_TYPE_FLAGS@@AEAW40@W40@@Z) already defined in projectM_SDL_main.obj
1>pmSDL.obj : error LNK2005: "enum PROPDESC_TYPE_FLAGS & __cdecl operator&=(enum PROPDESC_TYPE_FLAGS &,enum PROPDESC_TYPE_FLAGS)" (??_4@YAAEAW4PROPDESC_TYPE_FLAGS@@AEAW40@W40@@Z) already defined in projectM_SDL_main.obj
1>pmSDL.obj : error LNK2005: "enum PROPDESC_TYPE_FLAGS & __cdecl operator^=(enum PROPDESC_TYPE_FLAGS &,enum PROPDESC_TYPE_FLAGS)" (??_6@YAAEAW4PROPDESC_TYPE_FLAGS@@AEAW40@W40@@Z) already defined in projectM_SDL_main.obj
1>pmSDL.obj : error LNK2005: "enum PROPDESC_VIEW_FLAGS & __cdecl operator|=(enum PROPDESC_VIEW_FLAGS &,enum PROPDESC_VIEW_FLAGS)" (??_5@YAAEAW4PROPDESC_VIEW_FLAGS@@AEAW40@W40@@Z) already defined in projectM_SDL_main.obj
1>pmSDL.obj : error LNK2005: "enum PROPDESC_VIEW_FLAGS & __cdecl operator&=(enum PROPDESC_VIEW_FLAGS &,enum PROPDESC_VIEW_FLAGS)" (??_4@YAAEAW4PROPDESC_VIEW_FLAGS@@AEAW40@W40@@Z) already defined in projectM_SDL_main.obj
1>pmSDL.obj : error LNK2005: "enum PROPDESC_VIEW_FLAGS & __cdecl operator^=(enum PROPDESC_VIEW_FLAGS &,enum PROPDESC_VIEW_FLAGS)" (??_6@YAAEAW4PROPDESC_VIEW_FLAGS@@AEAW40@W40@@Z) already defined in projectM_SDL_main.obj
1>pmSDL.obj : error LNK2005: "enum PROPDESC_FORMAT_FLAGS & __cdecl operator|=(enum PROPDESC_FORMAT_FLAGS &,enum PROPDESC_FORMAT_FLAGS)" (??_5@YAAEAW4PROPDESC_FORMAT_FLAGS@@AEAW40@W40@@Z) already defined in projectM_SDL_main.obj
1>pmSDL.obj : error LNK2005: "enum PROPDESC_FORMAT_FLAGS & __cdecl operator&=(enum PROPDESC_FORMAT_FLAGS &,enum PROPDESC_FORMAT_FLAGS)" (??_4@YAAEAW4PROPDESC_FORMAT_FLAGS@@AEAW40@W40@@Z) already defined in projectM_SDL_main.obj
1>pmSDL.obj : error LNK2005: "enum PROPDESC_FORMAT_FLAGS & __cdecl operator^=(enum PROPDESC_FORMAT_FLAGS &,enum PROPDESC_FORMAT_FLAGS)" (??_6@YAAEAW4PROPDESC_FORMAT_FLAGS@@AEAW40@W40@@Z) already defined in projectM_SDL_main.obj
1>pmSDL.obj : error LNK2005: "enum PROPDESC_SEARCHINFO_FLAGS & __cdecl operator|=(enum PROPDESC_SEARCHINFO_FLAGS &,enum PROPDESC_SEARCHINFO_FLAGS)" (??_5@YAAEAW4PROPDESC_SEARCHINFO_FLAGS@@AEAW40@W40@@Z) already defined in projectM_SDL_main.obj
1>pmSDL.obj : error LNK2005: "enum PROPDESC_SEARCHINFO_FLAGS & __cdecl operator&=(enum PROPDESC_SEARCHINFO_FLAGS &,enum PROPDESC_SEARCHINFO_FLAGS)" (??_4@YAAEAW4PROPDESC_SEARCHINFO_FLAGS@@AEAW40@W40@@Z) already defined in projectM_SDL_main.obj
1>pmSDL.obj : error LNK2005: "enum PROPDESC_SEARCHINFO_FLAGS & __cdecl operator^=(enum PROPDESC_SEARCHINFO_FLAGS &,enum PROPDESC_SEARCHINFO_FLAGS)" (??_6@YAAEAW4PROPDESC_SEARCHINFO_FLAGS@@AEAW40@W40@@Z) already defined in projectM_SDL_main.obj
1>pmSDL.obj : error LNK2005: "enum AUDCLNT_STREAMOPTIONS & __cdecl operator|=(enum AUDCLNT_STREAMOPTIONS &,enum AUDCLNT_STREAMOPTIONS)" (??_5@YAAEAW4AUDCLNT_STREAMOPTIONS@@AEAW40@W40@@Z) already defined in projectM_SDL_main.obj
1>pmSDL.obj : error LNK2005: "enum AUDCLNT_STREAMOPTIONS & __cdecl operator&=(enum AUDCLNT_STREAMOPTIONS &,enum AUDCLNT_STREAMOPTIONS)" (??_4@YAAEAW4AUDCLNT_STREAMOPTIONS@@AEAW40@W40@@Z) already defined in projectM_SDL_main.obj
1>pmSDL.obj : error LNK2005: "enum AUDCLNT_STREAMOPTIONS & __cdecl operator^=(enum AUDCLNT_STREAMOPTIONS &,enum AUDCLNT_STREAMOPTIONS)" (??_6@YAAEAW4AUDCLNT_STREAMOPTIONS@@AEAW40@W40@@Z) already defined in projectM_SDL_main.obj
1>projectM.lib(projectM.obj) : error LNK2005: "double __cdecl meanSquaredError(double const &,double const &)" (?meanSquaredError@@YANAEBN0@Z) already defined in projectM_SDL_main.obj
1>projectM.lib(PresetLoader.obj) : error LNK2005: "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl parseExtension(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?parseExtension@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV12@@Z) already defined in projectM_SDL_main.obj
1>projectM.lib(ConfigFile.obj) : error LNK2005: "bool __cdecl std::_Fgetc<char>(char &,struct _iobuf *)" (??$_Fgetc@D@std@@YA_NAEADPEAU_iobuf@@@Z) already defined in projectM.lib(projectM.obj)
1>projectM.lib(ConfigFile.obj) : error LNK2005: "bool __cdecl std::_Fputc<char>(char,struct _iobuf *)" (??$_Fputc@D@std@@YA_NDPEAU_iobuf@@@Z) already defined in projectM.lib(projectM.obj)
1>projectM.lib(ConfigFile.obj) : error LNK2005: "bool __cdecl std::_Ungetc<char>(char const &,struct _iobuf *)" (??$_Ungetc@D@std@@YA_NAEBDPEAU_iobuf@@@Z) already defined in projectM.lib(projectM.obj)
1>projectM.lib(PresetFactoryManager.obj) : error LNK2005: "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl parseExtension(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?parseExtension@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV12@@Z) already defined in projectM_SDL_main.obj
1>MilkdropPresetFactory.lib(MilkdropPreset.obj) : error LNK2005: "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl parseFilename(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?parseFilename@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV12@@Z) already defined in projectM_SDL_main.obj
1>MilkdropPresetFactory.lib(MilkdropPreset.obj) : error LNK2005: "bool __cdecl std::_Fgetc<char>(char &,struct _iobuf *)" (??$_Fgetc@D@std@@YA_NAEADPEAU_iobuf@@@Z) already defined in projectM.lib(projectM.obj)
1>MilkdropPresetFactory.lib(MilkdropPreset.obj) : error LNK2005: "bool __cdecl std::_Fputc<char>(char,struct _iobuf *)" (??$_Fputc@D@std@@YA_NDPEAU_iobuf@@@Z) already defined in projectM.lib(projectM.obj)
1>MilkdropPresetFactory.lib(MilkdropPreset.obj) : error LNK2005: "bool __cdecl std::_Ungetc<char>(char const &,struct _iobuf *)" (??$_Ungetc@D@std@@YA_NAEBDPEAU_iobuf@@@Z) already defined in projectM.lib(projectM.obj)
1>MilkdropPresetFactory.lib(BuiltinFuncs.obj) : error LNK2005: "unsigned __int64 __cdecl RandomNumberGenerators::uniformInteger(unsigned __int64)" (?uniformInteger@RandomNumberGenerators@@YA_K_K@Z) already defined in projectM.lib(projectM.obj)
1>MilkdropPresetFactory.lib(Expr.obj) : error LNK2005: "unsigned __int64 __cdecl RandomNumberGenerators::uniformInteger(unsigned __int64)" (?uniformInteger@RandomNumberGenerators@@YA_K_K@Z) already defined in projectM.lib(projectM.obj)
1>   Creating library projectM-sdl/Debug/projectMSDL.lib and object projectM-sdl/Debug/projectMSDL.exp`

Seems Common.hpp is causing at least some of those but there's quite a few i'm having a hard time tracing.

I've been working on creating a UI on linux for projectMSDL and plan to make a pull request but thought it important to check my changes compile on windows too (i see no reason they shouldn't). Excited to show you guys the progress! I'll try to hang out on IRC to share some details.

**Comment by coast77777777777** [comment]
yes, I will fix this ASAP

**Comment by coast77777777777** [comment]
https://github.com/projectM-visualizer/projectm/commit/d1314d0512a343a120e09d76795550da8e1fab42

there exists new classes and some new extern C references

**Comment by r-hackett** [comment]
> [d1314d0](https://github.com/projectM-visualizer/projectm/commit/d1314d0512a343a120e09d76795550da8e1fab42)
> 
> there exists new classes and some new extern C references

Is that when the build issue on Windows started? In IRC wooster mentioned it was working up until recently.

**Comment by revmischa** [comment]
Appveyor builds have been failing for some time. Still are

**Comment by coast77777777777** [comment]
That is commit that broke appveyor. I will fix, but have limited time. Didn’t know others needed fix for forks so I will prioritize

**Comment by r-hackett** [comment]
Limited time, i know the feeling. I can pretty much guarantee the changes I made to the SDL project and additional library (ImGui) in libProjectM work on Windows, and the GLES android build compiles and runs fine. Haven't been able to test on MacOS but should be the same deal.

Really appreciate your attention to it but probably best to just submit the PR and get feedback as a starting point.

**Comment by coast77777777777** [comment]
fixed https://github.com/projectM-visualizer/projectm/commit/727b489bcf3e1ef4c8a2de817ac9358d06523ed1
