### ISSUE TITLE
Does anybody use (FTGL) font support?

### ISSUE THREAD

**Issue by rhyskoedijk** [projectM-visualizer/projectm#261]
I've noticed that FTGL/font support is not actually possible to enable using the standard build script since `libftgl` is not check and `USE_FTGL` is never defined.

If I do manually define `USE_FTGL`, then the project doesn't compile anymore, which hints to me that nobody must have used this for some time?
e.g. `/src/libprojectM/Renderer/Renderer.cpp::draw_stats()` has a undefined variable `renderTarget` which is nowhere in sight.

Checking old issues, I can see that FTGL was once enabled in PR https://github.com/projectM-visualizer/projectm/pull/48 but was then later disabled again in commit 1cecc14298d7b95b68d398ea9ff44651f95fb249. Does anybody know the latest word on this situation?

**Comment by revmischa** [comment]
It's quite possible that it was removed as part of the shader rework and GLES compatibility stuff. Does FTGL work with OpenGL ES?

**Comment by rhyskoedijk** [comment]
I'm not 100% sure if I understand what you mean, but I have managed to build FTGL against EGL successfully.

My main stumbling block is that the projectM source code has non-compiling code behind some  `#ifdef USE_FTGL` macros as mentioned above. All the text/font rendering functionality is locked behind these `#ifdefs` and it seems like this code hasn't been maintained with the rest of the project and almost fallen out of date since it is normally disabled in a standard build.

**Comment by rhyskoedijk** [comment]
Just for added context, I'm porting this to the Nintendo Switch. Currently it works fine, but font support is disabled and I therefore can't see the preset name when switching presets. I'd like to try find a way to re-enable font support if possible, but maybe this is not realistic and/or not worth the effort to revive. 

My port has some patches to re-enable FTGL but also has to nerf the `draw_stats()` function due to the non-compiling code I mentioned (see: https://github.com/devkitPro/pacman-packages/pull/120).

**Comment by revmischa** [comment]
Okay, the change to disabling Cg was definitely part of the shader and GLES work. I don't know why FTGL was a part of that but if it still builds with ES and FTGL then that is wonderful.

**Comment by coast77777777777** [comment]
Rebuild with ftgl is VERY smart design approach moving forward. We can use a new lib if it doesn’t work with gles, but the text based code library needs to operate with unification across all implementations. 

How do we fix FPS?

**Comment by coast77777777777** [comment]
ftgl has too much bitrot to operate with windows store
