### ISSUE TITLE
How to build for iOS?

### ISSUE THREAD

**Issue by AlwinEsch** [projectM-visualizer/projectm#265]
On https://github.com/projectM-visualizer/projectm/blob/master/README.md is sayed that iOS is supported.

How becomes this build done? 

I know iOS need it like this https://github.com/xbmc/xbmc/blob/master/xbmc/addons/kodi-addon-dev-kit/include/kodi/gui/gl/GL.h#L90-L98, but the configure search for `GLES/gl.h` and code use always `#include <GLES3/gl3.h>` where not available there.

Here the Log on iOS by Kodi's addon build: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Fvisualization.projectm/detail/PR-39/5/pipeline/15#step-219-log-935

**Comment by revmischa** [comment]
The iOS app is not maintained by the community. It is privately maintained and sadly not open source. I don't know how OpenGL would even work on there.
