### ISSUE TITLE
Windows (7) SDL doesn't use desktop audio (spotify) as input

### ISSUE THREAD

**Issue by reenenlaurie** [projectM-visualizer/projectm#268]
I've been trying to get ProjectM running with Spotify on windows 7.  Running spotify via the app and via browser.

Here are the steps I took to get where I am:

Be on a windows 7 machine. (I also have Conexant audio, not Realtek, which is the tutorials I found for on-line).

Download the SDL Release: https://github.com/projectM-visualizer/projectm/releases/download/3.1.1-rc4/projectM-sdl-Release-x64-windows.zip

This release is very minimalistic, as it only includes:
- SDL2.dll
- projectMSDL.lib
- projectMSDL.exp
- projectMSDL.exe

I then added a presets folder, where I copied a bunch of my old favourites from early 2000s in there.

````
INFO: GL_VERSION: 3.2.0 - Build 21.20.16.4627
INFO: GL_SHADING_LANGUAGE_VERSION: 1.50 - Build 21.20.16.4627
INFO: GL_VENDOR: Intel
INFO: Config file not found, using development settings
[PresetFactory] url is idle://Geiss & Sperl - Feedback (projectM idle HDR mix).milk
No Textures Loaded from ./textures
No Textures Loaded from ./textures
INFO: Using audio driver: wasapi
INFO: Found audio capture device 0: Stereo Mix (Conexant HD Audio)
INFO: Opened audio capture device 2: Stereo Mix (Conexant HD Audio)
INFO: Sample rate: 512, frequency: 48000, channels: 2, format: 33056
fps: 60
No Textures Loaded from ./textures
[PresetFactory] url is D:\projectM-sdl\Release\presets\Reenen - CD Colourwheel 2.milk
INFO: Displaying preset: Reenen - CD Colourwheel 2.milk
No Textures Loaded from ./textures
[PresetFactory] url is D:\projectM-sdl\Release\presets\Reenen - Redlock.milk
INFO: Displaying preset: Reenen - Redlock.milk
````

From the output, I notice that it doesn't find a config file, though it's successfully finding my presets (and showing them).

The presets would just sit there, unless I really talked load and my mic caught some stuff.  It was clearly not using the spotify music as an input, but rather my mic.

I haven't tested this on a Win10 machine install from the MS Store. (I assume this will work fine)

**Comment by capellavacancies** [comment]
works here with windows 10, try messing with your mixer settings and audio settings for each app
