### ISSUE TITLE
3.1.1-rc6 creates a package to large for kodi to install

### ISSUE THREAD

**Issue by Albinoman887** [projectM-visualizer/projectm#270]
basically the community folder in the presets dir is so big that the final product is well over 100 MB. kodi ships all there addons in zip format and it then installs and extracts them i dont know if there is any hard limit on the zip file size but currently when tyou attempt to install the addon it never installs. no error or anything. i checked the debug log and the last thing it said was it was unpacking the zip. I waited like 20 mins to no avail. as soon as i removed that folder from the zip it installed as usual. 

maybe make it a build option?

**Comment by revmischa** [comment]
Yeah, this is almost certainly #272

**Comment by revmischa** [comment]
Dealt with
