### ISSUE TITLE
Remove 41k presets from git and git history

### ISSUE THREAD

**Issue by revmischa** [projectM-visualizer/projectm#272]
It's not okay to add 41k files to the repo. It breaks a lot of things. For example [building the test times out](https://travis-ci.org/projectM-visualizer/projectm/jobs/610457947?utm_medium=notification&utm_source=email) and multiple people have been reporting issues.

I have added a link to the 41k presets you added, @coast77777777777 in the README in master. They are still available. They just shouldn't be in source control.

I propose to remove the `presets_community` from history.

**Comment by Albinoman887** [comment]
+1

**Comment by coast77777777777** [comment]
Please notice these presets are not mine; do not associate the communities' content with me. I will reset the GIT history, but this will break recent merges and release tags.

**Comment by Albinoman887** [comment]
Dude . What the fuck. You totally broke the source. This guy needs his push
tights revoked. All you had to do was revert it. Now there are missing
patches . Wow dude learn git

**Comment by revmischa** [comment]
I am force pushing master with the presets_community directory removed from history with git filter-branch.  I don't normally condone force pushing but it's too late for that I guess.

**Comment by nuess0r** [comment]
As a note: Yes there is no sense bringing 41k presets under version control, at least not together with the software to run it.

archive.org is also preserving MilkDrop presets, so there is already a good place where they are hosted: https://archive.org/details/milkdrops

**Comment by einsteinx2** [comment]
Yes a separate repo or even just archive for this makes a lot more sense.
