### ISSUE TITLE
how to use the presets ?

### ISSUE THREAD

**Issue by daslicht** [projectM-visualizer/projectm#28]
how to use the presets ? please?

~ Marc

**Comment by revmischa** [comment]
How are you running projectM?
Copy or symlink the presets dir to the application directory, if using projectMSDL. Otherwise, I believe it lives in /usr/local/share/projectM?

**Comment by daslicht** [comment]
i have installed the itunes visualizer pkg

**Comment by revmischa** [comment]
It should install presets in /usr/local/share/projectM. It has issues though on recent iTunes versions: https://github.com/projectM-visualizer/projectm/issues/7

**Comment by revmischa** [comment]
If you only want a particular set of presets, just leave only those in the presets directory

**Comment by revmischa** [comment]
I think pressing 'r' skips to the next random preset in the iTunes visualizer
