### ISSUE TITLE
Compile still fails on Ubuntu 19.10 (QGLWidget)

### ISSUE THREAD

**Issue by Russ-Holmes** [projectM-visualizer/projectm#280]
Sorry for late response to rc7 fix.
Just attempted to compile release 3.1.1-rc7 and still fails on the widget module.

[projectm-comp-err.txt](https://github.com/projectM-visualizer/projectm/files/3870961/projectm-comp-err.txt)

**Comment by revmischa** [comment]
Sorry, why close the issue?

**Comment by Russ-Holmes** [comment]
I suspect the problem might be me not passing the correct library name when running the configure script (as for the Debian). I will try this evening and report back.

**Comment by carsayao** [comment]
I'm new to building projects, but I'm having the same issue. I'm following `BUILDING.md` on Ubuntu 19.04. I ran:

    ./configure --enable-qt
    make

[comp-err.txt](https://github.com/projectM-visualizer/projectm/files/3900453/comp-err.txt)
