### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by xioren** [projectM-visualizer/projectm#281]
I don't see an uninstall script; what is the correct way to uninstall/remove everything? (on Linux)

**Comment by sukovec** [comment]
Basically, there's no implicit uninstall make target, but you can do 
`make install DESTDIR=/tmp/something` and get a list of files to delete by using 
`find /tmp/something -type f | sed 's/\/tmp\/something//' `

Hovewer, the standard way how to do correct install and uninstall is by using your package manager and you will find it in your OS manual.
