### ISSUE TITLE
3.1.1-rc7 Compile fatal error: QGLWidget: No such file or directory

### ISSUE THREAD

**Issue by carsayao** [projectM-visualizer/projectm#283]
I'm new to building projects, but I'm having the same issue [#280](https://github.com/projectM-visualizer/projectm/issues/280#issue-526049987) compiling projectm-pulseaudio. I'm following `BUILDING.md` on Ubuntu 19.04. I ran: 

    ./configure --enable-pulseaudio --enable-qt
    make

Then:

`fatal error: QGLWidget: No such file or directory`

[comp-err.txt](https://github.com/projectM-visualizer/projectm/files/3906747/comp-err.txt)

I might try some older releases. Thanks!

**Comment by revmischa** [comment]
I would love to know why this build passes on Travis on ubuntu https://travis-ci.org/projectM-visualizer/projectm/jobs/624274159

**Comment by nuess0r** [comment]
same on debian unstable.

QGLWidget headers are provided by the packet "libqt5opengl5-dev" which is installed on my system.

They end up in "/usr/include/x86_64-linux-gnu/qt5/QtOpenGL/"

The file QGLWidget contains only one line, to include qgl.h which is in the same folder.

**Comment by carsayao** [comment]
@revmischa I'm not sure what I did differently, but this build is now stable for me. I know I experimented with different package dependencies, and followed the same instructions I posted above on the same system. Thanks.
