### ISSUE TITLE
SDL requires vcdist

### ISSUE THREAD

**Issue by ghost** [projectM-visualizer/projectm#288]
![image](https://user-images.githubusercontent.com/58450015/70082904-61bbb700-15d9-11ea-9e14-7887f7880cb3.png)

**Comment by wrip0001** [comment]
Download the 2019 runtime environments, for anybody else that got this error.

**Comment by kblaschke** [comment]
Not an issue with projectM itself and no further information which build caused this error. As suggested above, install [the Visual C 2019 Runtime Libraries](https://www.visualstudio.com/downloads/) released by Microsoft.
