### ISSUE TITLE
Fullscreen on Android 10 - Pixel 4 XL

### ISSUE THREAD

**Issue by RandomArray** [projectM-visualizer/projectm#289]
On Android 10 fullscreen mode does not utilize the bottom portion of the screen where the soft buttons would usually go. The black bar looks to be twice the height of soft buttons.

Android 10 uses swipe gestures and removes the soft buttons by default. The gestures can be disabled and soft buttons used instead of desired. 

When soft buttons are re-enabled and gestures disabled, the app still does not utilize the bottom portion of the screen.

![Screenshot_20191210-233010](https://user-images.githubusercontent.com/13847525/70600669-1e4ae500-1ba5-11ea-94f6-95d23075d5de.png)
![Screenshot_20191210-232940](https://user-images.githubusercontent.com/13847525/70600671-1e4ae500-1ba5-11ea-9271-44986d4a052b.png)

**Comment by revmischa** [comment]
Is this on the version in the app store? That version is not a part of this project or maintained by the community.

**Comment by psperl** [comment]
I'm working on an update for android. It should fix this unless I misunderstand the problem. ETA one week. I also need to set up somewhere else for people to file tickets for the commercial version of projectM

**Comment by psperl** [comment]
@RandomArray Shoot me an email at peter@sperl.com and I'll send you a test build.
