### ISSUE TITLE
High Sierra - Symbol not found: ____chkstk_darwin

### ISSUE THREAD

**Issue by thedoger82** [projectM-visualizer/projectm#296]
Hi, hope everything is good...
As the tittle says, projectM wont open in High Sierra... this is the report when open from terminal

Last login: Tue Dec 31 23:58:20 on console
Bbys-MacBook-Pro:~ bby$ /Applications/projectM\ SDL.app/Contents/MacOS/SDLprojectM ; exit;
2020-01-02 07:38:59.399 SDLprojectM[3264:3355216] INFO: GL_VERSION: 4.1 INTEL-10.36.26
2020-01-02 07:38:59.399 SDLprojectM[3264:3355216] INFO: GL_SHADING_LANGUAGE_VERSION: 4.10
2020-01-02 07:38:59.399 SDLprojectM[3264:3355216] INFO: GL_VENDOR: Intel Inc.
2020-01-02 07:38:59.402 SDLprojectM[3264:3355216] INFO: Using data directory: /usr/local/share/projectM
2020-01-02 07:38:59.402 SDLprojectM[3264:3355216] INFO: Looking for configuration file in data dir: /usr/local/share/projectM.
2020-01-02 07:38:59.403 SDLprojectM[3264:3355216] INFO: Config file not found, using built-in settings. Data directory=/Applications/projectM SDL.app/Contents/Resources/
[PresetFactory] url is idle://Geiss & Sperl - Feedback (projectM idle HDR mix).milk
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/projectM SDL.app/Contents/MacOS/SDLprojectM
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/projectM SDL.app/Contents/MacOS/SDLprojectM
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...1 completed.

Thanks!

**Comment by dbogdanov** [comment]
Same issue here.

**Comment by revmischa** [comment]
I think these are similar issues:
https://forums.developer.apple.com/thread/121887
https://github.com/bazelbuild/bazel/issues/10297

Maybe I can try doing a build with `-fno-stack-check`

**Comment by revmischa** [comment]
Just did a quick build with `-fno-stack-check` - want to tell me if this runs on macOS 10.13?

[projectM SDL.app.zip](https://github.com/projectM-visualizer/projectm/files/4061699/projectM.SDL.app.zip)

**Comment by jjdeprisco** [comment]
Tried revmischa's zip and got the attached error.
<img width="422" alt="projm" src="https://user-images.githubusercontent.com/35905062/72480631-0da21600-37c6-11ea-8a52-0975cc74be8a.png">

**Comment by thedoger82** [comment]
> Just did a quick build with `-fno-stack-check` - want to tell me if this runs on macOS 10.13?
> 
> [projectM SDL.app.zip](https://github.com/projectM-visualizer/projectm/files/4061699/projectM.SDL.app.zip)

It worked right away!!! this is awesome!!! thanks a lot man!!!

**Comment by revmischa** [comment]
lol those are two very different answers

**Comment by thedoger82** [comment]
> Tried revmischa's zip and got the attached error.
> <img alt="projm" width="422" src="https://user-images.githubusercontent.com/35905062/72480631-0da21600-37c6-11ea-8a52-0975cc74be8a.png">

Maybe it downloaded corrupt... i used keka to uncompress... when i got that kind of errors i use different compressors (keka, unarchiver, unrarx) till i get good files.

**Comment by kblaschke** [comment]
Closing because the build system was reworked in the meantime and macOS builds should run properly now, up to the latest macOS.
