### ISSUE TITLE
manual on how to import this to VLC on macOS 

### ISSUE THREAD

**Issue by g-uru** [projectM-visualizer/projectm#3]
So how do i import this to VLC on macOS?

**Comment by revmischa** [comment]
I'd love to help! I kept asking the same thing in #videolan and nobody would talk to me. The core libprojectm is pretty platform-agnostic, really you just need to give it an openGL context to draw into. Building it is mostly the hard part; dealing with all the cmake bullshit.
I'm happy to help VLC devs re-integrate libprojectM if any are interested!
