### ISSUE TITLE
Standalone not running on Mac OSX

### ISSUE THREAD

**Issue by jjdeprisco** [projectM-visualizer/projectm#301]
Tried installing standalone on my Macbook today. Immediately crashes. Details attached.

[crash.txt](https://github.com/projectM-visualizer/projectm/files/4057077/crash.txt)
[JD Mac Specs.txt](https://github.com/projectM-visualizer/projectm/files/4057078/JD.Mac.Specs.txt)

**Comment by revmischa** [comment]
Okay, looks like this is a duplicate of #296
