### ISSUE TITLE
Low FPS on many presets

### ISSUE THREAD

**Issue by milkdropper** [projectM-visualizer/projectm#304]
After implementing the FPS counter I noticed that on my machine many presets are getting bad FPS: with some as low as 10 frames per second.

I did some testing and I am able to get much better performance by changing the hard coded SDL configuration of value meshx, which is currently set to 400.  I suggest we change this value to something low so when people test releases they get the best performance possible. The visualizations are still beautiful at a much lower setting.

To those with more experience with Milkdrop: what would be an ideal meshx setting?

Notes:
* I have verified the accuracy of the FPS counter by using the onscreen Nvidia Geforce Experience FPS counter.
* My machine is a 2nd generation I7 with a GTX 980. So it's older hardware but not ancient.

**Comment by revmischa** [comment]
I don't know what the best setting is for the meshes, I think it matters much less for presets using shaders. But I believe the meshx/meshy values are directly responsible for most of the CPU usage. Definitely fine to lower the default. I think the meshy should be meshx * aspect ratio (16:9 these days)
