### ISSUE TITLE
Installation Guid on Windows 10 without Store

### ISSUE THREAD

**Issue by leminsc8er** [projectM-visualizer/projectm#308]
Need help to Install proectM on Windows 10...
i searching for a way without Windows Store.
i want install ProjectM for windows to play from any audio source like Firefox-Browser (youtube/soundcloud...)

**Comment by BadPsychoBoy** [comment]
Same here the store version fails to download

**Comment by revmischa** [comment]
@coast77777777777

**Comment by kblaschke** [comment]
If that's still an issue, either use [the free Steam version](https://store.steampowered.com/app/1358800/projectM_Music_Visualizer/), or download a development build from my fork:
https://github.com/kblaschke/projectm/releases/tag/v3.1.13-9e8ab88-win64

Will hopefully have some automated builds available that we can release regularly.
