### ISSUE TITLE
projectM-pulseaudio in elementary crashes at start

### ISSUE THREAD

**Issue by rooven** [projectM-visualizer/projectm#318]
I'm using the latest Elementary OS, I installed the projectM-pulseaudio version from the elementary app center but it crashes on start, I tried running it from the terminal and got some errors

```
No Textures Loaded from "/usr"/share/projectM/textures
Could not open font file: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans.ttf
```
So it turns out there isn't a `ttf-dejavu ` folder, instead the font is stored in  `/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf`, not sure if this issue is only on elementary os or ubuntu based distros.
After modifying the config file in `/usr/share/projectM/config.inp` I had to also modify the config file in my user folder and now is properly working

**Comment by Naereen** [comment]
Hi, see https://github.com/projectM-visualizer/projectm/issues/126 for more information.

**Comment by kblaschke** [comment]
If the issue is still present in current master builds, feel free to reopen.
