### ISSUE TITLE
bashism in configure

### ISSUE THREAD

**Issue by yurivict** [projectM-visualizer/projectm#319]
This line has a bash-specific syntax:
https://github.com/projectM-visualizer/projectm/blob/master/configure.ac#L166\

GNU configure is required to have Bourne shell syntax for portability: https://www.gnu.org/software/autoconf/manual/autoconf-2.66/html_node/Portable-Shell.html

**Comment by revmischa** [comment]
What should it be?

**Comment by yurivict** [comment]
Something like "cat $host | grep android"
