### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by senposage** [projectM-visualizer/projectm#32]
whats with the lack of windows support ?
is there some major roadblock ? 
id like to see a plugin for AIMP4 now that its mature

**Comment by revmischa** [comment]
The only roadblock is that nobody has contributed a windows build. If you'd like to, try building the projectM-sdl project on windows, or make a new frontend application. The SDL2 project code is cross-platform.

**Comment by revmischa** [comment]
There's an issue open for this #19 
This is an open source project, feel free to contribute!
