### ISSUE TITLE
projectm links to almost all Qt components

### ISSUE THREAD

**Issue by yurivict** [projectM-visualizer/projectm#322]
```
Warning: you need USES=qt:5 and USE_QT+=designer
Warning: you need USES=qt:5 and USE_QT+=help
Warning: you need USES=qt:5 and USE_QT+=multimedia
Warning: you need USES=qt:5 and USE_QT+=printsupport
Warning: you need USES=qt:5 and USE_QT+=declarative
Warning: you need USES=qt:5 and USE_QT+=svg
Warning: you need USES=qt:5 and USE_QT+=webkit
Warning: you need USES=qt:5 and USE_QT+=multimedia
Warning: you need USES=qt:5 and USE_QT+=x11extras
Warning: you need USES=qt:5 and USE_QT+=concurrent
Warning: you need USES=qt:5 and USE_QT+=dbus
Warning: you need USES=qt:5 and USE_QT+=sql
Warning: you need USES=qt:5 and USE_QT+=declarative
Warning: you need USES=qt:5 and USE_QT+=xmlpatterns
Warning: you need USES=qt:5 and USE_QT+=network
Warning: you need USES=qt:5 and USE_QT+=testlib
Warning: you need USES=qt:5 and USE_QT+=script
Warning: you need USES=qt:5 and USE_QT+=scripttools
Warning: you need USES=qt:5 and USE_QT+=sensors
Warning: you need USES=qt:5 and USE_QT+=serialport
```

Do you really need all of them? At least ```serialport```, ```sql``` don't seem reasonable.

**Comment by revmischa** [comment]
Feel free to open a PR with your desired changes! Happy to review/merge

**Comment by yurivict** [comment]
> Feel free to open a PR with your desired changes! Happy to review/merge

But I don't know what components are supposed to be used by the project. You are supposed to know this. -)

**Comment by revmischa** [comment]
I don't know nothin' lol
I think just openGL and widgets

**Comment by yurivict** [comment]
Something links binaries to all these Qt components in the project, I can't update the FreeBSD port with this problem because it would be broken without them, and they are obviously redundant.

**Comment by revmischa** [comment]
I think https://github.com/projectM-visualizer/projectm/blob/master/m4/autoconf-archive/ax_have_qt.m4 may be the likely culprit

**Comment by yurivict** [comment]
I think so too.

**Comment by kblaschke** [comment]
In the newly added CMake build scripts, only the GUI and OpenGL components are linked as well, so this should be fixed in current master.
