### ISSUE TITLE
Only a handful of presets

### ISSUE THREAD

**Issue by LucidObscurity** [projectM-visualizer/projectm#325]
this software only cycles through about a dozen presets and that's it. I don't see anywhere to add presets or change the priority of them once added. I can't even set it to full screen. this is pretty much crap compared to all the other ProjectM projects out there on other platforms.

**Comment by revmischa** [comment]
What exactly are you running? Git Master? Pulseaudio? SDL? Compiled yourself? Installed via package manager?
There are thousands of presets that come with it right now

**Comment by ezibit** [comment]
Not if you are just downloading the windows version from the app store....no more than 10-11 presets. no where to add the downloaded .milk files... its an issue. We arent all code monkeys.

**Comment by PhantomWatson** [comment]
The `presets_community.zip` file doesn't have accompanying instructions for where to put those files for a Windows installation, and neither does the link to it.

**Comment by milkdropper** [comment]
I recommend you grab the SDL windows zip from the releases page: https://github.com/projectM-visualizer/projectm/releases

**Comment by mitvitaminen** [comment]
@milkdropper Where is the SDL windows zip? I only see a source.zip and the linux tar.gz. Do I have to compile the source myself?greets Chris

**Comment by kblaschke** [comment]
The WindowsStore version is kinda sandboxed and can't access presets outside the app bundle. It's also quite old now, as the original author doesn't update the application anymore as it seems.

There hasn't been a recent binary release for Windows, but we'll build a proper Windows standalone installer upon the next release, containing about 4K presets (might even possibly add the big 40K+ pack as an optional component).
