### ISSUE TITLE
Reduce Processor Load

### ISSUE THREAD

**Issue by mbutz** [projectM-visualizer/projectm#326]
This is more of a question:

I have sucessvully compiled `projectM` with

```
./configure --enable-qt --enable-jack --enable-gles LIBS="-lQt5Gui -lQt5OpenGL" 
```
on my Linux Laptop (Lenovo Thinkpad x230, i7, 4-core, 16 MB RAM, Linux Mint 19.3). As I am live coding music while `projectM` is running I am trying to reduce processor load. I thought I would achieve that in tweaking some of the `projectM` settings such as 

* Texture size (2)
* Maximum FPS (12)

being aware that this should reduce the quality of the visualisation (which would be acceptable for me).

But my impression is that neither the quality seems to have declined, nor seems to be the processor load reduced which is constantly around 25% (value from Conky). Maybe I missinterpreted these options?

So I would be grateful to know if there is a way to run `projectM` with somehow reduces processor load.

**Comment by revmischa** [comment]
Try modifying meshSize - see https://github.com/projectM-visualizer/projectm/issues/304

**Comment by mbutz** [comment]
Hi @revmischa, thanks a lot for the feedback.

Please forgive my ignorance, but I don't know how to do that:

#304: 
> by changing the hard coded SDL configuration of value meshx

Is this something I have to do before compilation? And do I have to add `--enable-sdl` while compiling to do that? (The building doc mentions that, but I couldn't find out, what this is.)

#305:
What's `default SDL`?

**Comment by mbutz** [comment]
Ok, did what I asked (compiled with `--enable-sdl`) and found:

* search for `meshx`: downloads/projectm-3.1.2/src/projectM-sdl/projectM_SDL_main.cpp, line 335:        settings.meshX = 128; so I assumed that there is already a default setting for `meshx` lower than the mentioned 400 ...
* compiled with flag `enable-sdl`
* found new executable `projectMSDL which I started instead of `projectM-jack
* this one runs with much lesser CPU load (quality is fine for me)
* I can use shortcuts `n`, `p`, `r` aso. but I am not able to see the configuration or playlist settings (which was `m` when I used `projectM-jack`)

Grateful for any enligtenment of how I can choose a playlist with the `projectMSDL` executable. Thanks a lot for the help so far!

**Comment by revmischa** [comment]
Unfortunately this feature is not yet supported in projectMSDL. I wonder why CPU load would be so much lower in the jack version. There should be a configuration file, typically located at /usr/local/share/projectM where you can set meshX

**Comment by mbutz** [comment]
I suppose `meshx` = Mesh X, right. I assume that my local config file should overwrite the system config.

Actually `projectM-jack` constanty uses 25% of my cpu power whereas `projectMSDL` uses below 10%.

`/usr/local/share/projektM` says:

```
# config.inp
# Configuration File for projectM

#Texture Size = 1024			# Size of internal rendering texture

Mesh X  = 220            	# Width of PerPixel Equation mesh
Mesh Y  = 125          		# Height of PerPixel Equation mesh
FPS  = 35          		# Frames Per Second
Fullscreen  = false
Window Width  = 512  	       	# startup window width
Window Height = 512            	# startup window height

Smooth Transition Duration = 5  # in seconds
Preset Duration = 30 	     	# in seconds
Easter Egg Parameter = 1

Hard Cut Sensitivity = 10       # Lower to make hard cuts more frequent
Aspect Correction = true	# Custom Shape Aspect Correction

Preset Path = /usr/local/share/projectM/presets # preset location
Title Font = Vera.ttf
Menu Font = VeraMono.ttf
```
And the local user configuration says:
```
Aspect Correction = 1
Easter Egg Parameter = 0
Egg Parameter = 1
FPS = 12
Fullscreen = false
Hard Cut Sensitivity = 20
Height = 512
Menu Font = /usr/share/fonts/truetype/ttf-dejavu/DejaVuSansMono.ttf
Mesh X = 4
Mesh Y = 24
Preset Duration = 20
Preset Path = /home/marty/projects/sonicpi/playground/config/projectm/presets
Shuffle Enabled = 1
Smooth Preset Duration = 20
Smooth Transition Duration = 5
Soft Cut Ratings Enabled = 0
Texture Size = 2
Title Font = /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans.ttf
Window Height = 722
Window Width = 512
3



Window Width = 512
 # Lower to make hard cuts more frequent
Aspect Correction = true	# Custom Shape Aspect Correction

Preset Path = /home/marty/projects/sonicpi/playground/config/projectm/presets # preset location
Title Font = /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans.ttf
Menu Font = /usr/share/fonts/truetype/ttf-dejavu/DejaVuSansMono.ttf
```
I reduced everything I thought would make sense (I copied the file here _as it is on my harddisk_ after I tweaked the settings via the GUI).

**Comment by revmischa** [comment]
did changing Mesh X have any effect?

**Comment by mbutz** [comment]
Ok. I think, I know, what it is: `projectMSDL` does not seem to have a fullscreen mode (at least I don't know how to activate it). And `projectM-jack` has: As soon as I switch to it, it will go up from around 6-10% to 25%. So the fix for me is to skip the fullscreen mode and just adjust the window (which runs in the background of my live coding programm).

**Comment by revmischa** [comment]
I think cmd/ctl - f will fullscreen it

**Comment by mbutz** [comment]
Oh, yes. That's right. Now `projectMSDL` uses around 15%. So it seem to be a combination of fullscreen mode and programm version (at least so far I can see)... Thanks again for your help. I will further investigate tomorrow...
