### ISSUE TITLE
Sometimes stops for a few seconds

### ISSUE THREAD

**Issue by capellavacancies** [projectM-visualizer/projectm#328]
Hello I use projectM on win10 (and I love it). The audio signal comes from my external audio device, a Focusrite 4i4. I use the visualizations inside obs (streaming software) capturing projectm window. I record about 2 hours of show and I noticed that sometimes visualizations stop displaying at all for 20/30 seconds then appear again. If I click next preset they start instantly otherwise I have to wait for them to display on their own.
Did you encounter this bug ?
This happen like 20 times in two hour. 
Obviously it's not because the audio is missing, because the audio signal is there and gets constantly recorded by obs
Could it be a broken preset ? 
I had this problem using window store version and sdl version

thanks

**Comment by revmischa** [comment]
It's likely that individual presets cause this problem. Either the presets themselves have some issue that causes them to not show up, or projectM has some issue that they are triggering. I suggest getting a list of a few presets that may cause this issue and then we can debug further what's going on.

**Comment by quantugranola** [comment]
Do you think about a way to do it other than staring at project m for one hour and writing the name of the presets down ?

thanks

**Comment by revmischa** [comment]
lol good question. I believe the qt-based interfaces show you a nice GUI list of presets. also turn off shuffle maybe. i'm not sure what the best approach is here. comparing the milkdrop 2 source with projectm source for the waveforms etc would likely help.

**Comment by labkey-matthewb** [comment]
My guess is that after finding a few problem presets there will be a clear pattern, like using loop() or gmegabuf() or some other feature.

**Comment by quantugranola** [comment]
Geiss - Motion Blur 2 (Jelly V3).milk

**Comment by kblaschke** [comment]
Likely some yet unsupported preset features. A few issues have been fixed, but there's more to work out.

Next release version will be able to report back broken or unsupported presets so apps can skip them and load another one.

For the unsupported features, specific tickets exist in the tracker, so I'm closing this one to keep the list clean.
