### ISSUE TITLE
"cmake go away" not complete

### ISSUE THREAD

**Issue by themaddoctor** [projectM-visualizer/projectm#33]
When you removed cmake last month, you broke it. The library doesn't get installed, the headers don't get installed, and subprojects like pulse and jack aren't built.

**Comment by themaddoctor** [comment]
How do I get a snapshot of the Jan 4 sources?

**Comment by revmischa** [comment]
https://github.com/projectM-visualizer/projectm/tree/f29e73dd52f471e3dccf64c05acbc45aca200224

https://github.com/projectM-visualizer/projectm/archive/f29e73dd52f471e3dccf64c05acbc45aca200224.zip

**Comment by revmischa** [comment]
i'm happy to try to add those things to autotools.

**Comment by revmischa** [comment]
Do you know what headers were missing? Are there any besides projectM.hpp? in /usr/local/include?
And what libraries besides libprojectM?

**Comment by themaddoctor** [comment]
Only one header was installed, and it was
/usr/include/https:/github.com/revmischa/projectm/projectM.hpp

Yes, that's right, it had a URL in its name.

Two files were installed. The other was /usr/bin/projectmSDL


On 3/3/18, Mischa Spiegelmock <notifications@github.com> wrote:
> Do you know what headers were missing? Are there any besides projectM.hpp?
> in /usr/local/include?
> And what libraries besides libprojectM?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/projectM-visualizer/projectm/issues/33#issuecomment-370135414


-- 
Thomas Kaeding

my public key: http://pgp.mit.edu/pks/lookup?op=get&search=0x81B0FCA32599BE6F

**Comment by revmischa** [comment]
Sorry, I meant to ask, what files are not being installed that ought to be? /usr/local/include/projectM.hpp and /usr/local/lib/libprojectM.so? Anything else?

**Comment by revmischa** [comment]
https://github.com/projectM-visualizer/projectm/compare/autotools#diff-460afceacee0cbc2f49de54734b9825c

(I don't really know what I'm doing with automake)

**Comment by themaddoctor** [comment]
I said, only two files were installed.

The libraries were not installed.

The headers were not installed.

The presets were not installed.

projectM-pulseaudio and other executables were not installed.

I can't make it any more clear.

How do I get a snapshot from earlier, before this change?


On 3/3/18, Mischa Spiegelmock <notifications@github.com> wrote:
> https://github.com/projectM-visualizer/projectm/compare/autotools#diff-460afceacee0cbc2f49de54734b9825c
>
> (I don't really know what I'm doing with automake)
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/projectM-visualizer/projectm/issues/33#issuecomment-370138791


-- 
Thomas Kaeding

my public key: http://pgp.mit.edu/pks/lookup?op=get&search=0x81B0FCA32599BE6F

**Comment by revmischa** [comment]
I included the link to a snapshot from January above!

I just pushed support for installing the library and header file. I can work on pulseaudio and presets. Are you using the pulseaudio version?

**Comment by revmischa** [comment]
```
cyber@ubuntu:~/projectm$ ls /usr/local/lib/libprojectM.*
/usr/local/lib/libprojectM.a   /usr/local/lib/libprojectM.so    /usr/local/lib/libprojectM.so.0.0.2
/usr/local/lib/libprojectM.la  /usr/local/lib/libprojectM.so.0

cyber@ubuntu:~/projectm$ ls /usr/local/include/projectM.hpp 
/usr/local/include/projectM.hpp
```

**Comment by themaddoctor** [comment]
> Are you using the pulseaudio version?
I'm not using any version, until I can build it.
I'm trying to include it into my build of clementine.

Thank you.

**Comment by revmischa** [comment]
I'll work on the presets but go ahead and grab master and tell me if that's basically doing what you want. Patches welcome too!

**Comment by revmischa** [comment]
make install installs headers/libs/presets/config/shaders now. config file needs some stupid `sed` fix. i'll look into adding pulseaudio make support soon
