### ISSUE TITLE
Issue with Preset Path/presetURL

### ISSUE THREAD

**Issue by ajs124** [projectM-visualizer/projectm#334]
I'm currently trying to get projectM into a usable state in [nixpkgs](https://github.com/NixOS/nixpkgs/pull/82427) and ran into an issue with the Preset Path setting.

projectM(-pulseaudio) seems to copy the Preset Path from the global config, but only *once*.
This is an issue, because the path changes with every rebuild and old paths get garbage collected after a time.

I'm not sure what the right course of action here would be, so I thought I'd ask here.
I'm also not entirely clear on what this settings is used for. As in, if it would be a sensible option to always use the setting from the global config.

**Comment by revmischa** [comment]
What should the behavior be?

**Comment by ajs124** [comment]
Good question. I'm not sure. What does the value in the config actually get used for?

Always copying from the global config probably isn't sensible, if you want to set your own folder. Only copying once breaks setups where the install location changes, though.

Maybe something like checking if the folder exists and if not fall back to the global config might be reasonable?

**Comment by kblaschke** [comment]
The new SDL app handles configurations way better now. It ships with a default config, but also loads a user-defined configuration file on top from the home dir which will override any of the default settings if set explicitly.

The library itself doesn't bother with preset paths and config files anymore. The now outsourced playlist library supports adding any number of paths to search for presets.

The Qt frontend is still down the road to be fixed, but there are many issues that need addressing like audio capturing, rendering issues and general modernization. Not high prio right now, any help is greatly appreciated though.

For the core lib and SDL frontend, it's all sorted out now, so closing the issue.
