### ISSUE TITLE
Clarify required OpenGL profile

### ISSUE THREAD

**Issue by s09bQ5** [projectM-visualizer/projectm#336]
Our application needs an OpenGL context with support for the legacy OpenGL commands. I see that the current projectM_SDL_main.cpp creates a legacy free OpenGL 3.2 context. Which version of projectM broke compatibility with legacy contexts? Which version was the last one that still worked on OpenGL 2.1 hardware?

**Comment by revmischa** [comment]
Ooof.. that was pre-GLSL refactor
I believe that was roughly around this time: https://github.com/projectM-visualizer/projectm/pull/26

**Comment by s09bQ5** [comment]
If I had a table of projectM version vs. required OpenGL profile, I could check at runtime if the created context is suitable for running projectM and then disabling the option in the menu to use projectM if not. On macOS I could check at build time if the supplied projectM is too new since macOS will never return a 3.x context with compatibility for 2.1 if 2.1 is requested. 

Or maybe you could add a function that checks if the current context is suitable? But that won't help me with old versions of projectM...

Btw. you forgot to raise the version number in projectM.hpp. Only pkg-config will tell the version.

**Comment by revmischa** [comment]
Well it's easy - anything before version 3.0.0 used immediate-mode GL calls
https://github.com/projectM-visualizer/projectm/releases?after=v3.1.1-rc1

**Comment by revmischa** [comment]
> Btw. you forgot to raise the version number in projectM.hpp. Only pkg-config will tell the version.

Want to fix it :) ?

**Comment by s09bQ5** [comment]
> Well it's easy - anything before version 3.0.0 used immediate-mode GL calls

That just tells me that pre-3.0.0 will not work with legacy free OpenGL 3.x/4.x contexts.
Will 3.0.0 require anything that is not part of OpenGL 2.1?

**Comment by revmischa** [comment]
I don't think it will require anything newer. I can't promise anything but I believe yes

**Comment by s09bQ5** [comment]
Judging from the functions used by the library, it looks like
 - v2.2.1 is OpenGL 1.1
 - v3.0.0 is OpenGL 2.0 + GL_ARB_vertex_array_object (part of OpenGL 3.0)
 - v3.1.0 is OpenGL 2.1 (because of glUniformMatrix4x3fv) + GL_ARB_vertex_array_object + GL_ARB_sampler_objects (part of OpenGL 3.3)

So requesting a 3.2 context in projectM_SDL_main.cpp is not correct.

**Comment by revmischa** [comment]
I think the version of GLSL we transpile to for the shaders requires 3+ if I recall. I may be mistaken

**Comment by revmischa** [comment]
This PR may change things to use 2.1 https://github.com/projectM-visualizer/projectm/pull/399/files
