### ISSUE TITLE
Sholdn't install projectM-unittest

### ISSUE THREAD

**Issue by yurivict** [projectM-visualizer/projectm#340]
3.1.3 installs these two fines:
```
+bin/projectM-unittest
+bin/projectMSDL
```

```projectM-unittest``` shouldn't be installed. Not sure about ```projectMSDL```.

**Comment by kblaschke** [comment]
The new CMake-based build has an option to enable or disable the test applications, with a default of being disabled. So except if excplicitly enabled by the developer, the `projectM-unittest` application is no longer installed.

`projectMSDL` is the standalone visualization application that captures system audio to visualize it. The new build system also adds a switch to enable or disable it, but it's being built by default.

I'll close this ticket as the test application is no longer installed using CMake, and the old autotools build system will be removed soon.
