### ISSUE TITLE
How to set resolution?

### ISSUE THREAD

**Issue by craigmasonnc** [projectM-visualizer/projectm#341]
I'm trying to change what resolution Project M uses when in fullscreen mode (from 720p to 1080p).  Is there a way to do this?

I'm on windows 10, and using Project M as a standalone application (not inside any media player).

I see some settings in Setup.iss, but nothing that obviously adjusts resolution.  Please help!

**Comment by milkdropper** [comment]
It will take the resolution that your monitor is running at when you full screen it.

So make sure you're monitor is 1080p then you're good to go (take a screenshot and you will see it's 1080p).

**Comment by craigmasonnc** [comment]
My display resolution is currently 1920x1080.  When I use Ctrl+F to switch Project M to fullscreen mode, it changes to 720p.  When I exit fullscreen mode back to windowed mode with Esc, my screen resolution returns to normal.  Is there a setting to change this behavior?

**Comment by milkdropper** [comment]
This does not happen to me in Windows 10 using SDL. Are you positive? 

Can you use the PrintScreen key and paste that into MsPaint and save it? What is the resolution you see if you right click on the file and go to properties > details?

Do you have multiple monitors? Can you try Ctrl+M or Ctrl+S? Those keys might behave differently than Ctrl+F.

**Comment by milkdropper** [comment]
Resolution is now displayed in https://github.com/projectM-visualizer/projectm/commit/a24dcca4701474e94d7bffb6bda3a0c9160cbaf2

**Comment by milkdropper** [comment]
stale - can't reproduce - more stats provided.

**Comment by BonHammer** [comment]
I ran into the same issue on W10. The zoom feature on W10 seems to modify the recognition of the monitor native resolution. I have a 2160p monitor and it would only show up as 1080p in full screen. Removed the 225% back to 100%, restarted and it went full screen in 2160p.
