### ISSUE TITLE
Version 3.1.3 Complains of a incomplete QT installation, OpenSUSE Tumbleweed.

### ISSUE THREAD

**Issue by ukbeast** [projectM-visualizer/projectm#342]
My .spec file is on https://build.opensuse.org/package/view_file/home:ukbeast89:branches:multimedia:apps/projectM/projectM.spec

and my build log on https://build.opensuse.org/package/live_build_log/home:ukbeast89:branches:multimedia:apps/projectM/openSUSE_Tumbleweed/x86_64

It compiled properly prior on 3.1.0, so I don't know what extra modules  it's requiring.

**Comment by ukbeast** [comment]
Some chap created a patch to remove the unseeded QT5 modules
https://build.opensuse.org/package/view_file/multimedia:apps/projectM/0001-Reduce-dependencies.patch

Fixes build  and runs without any known issues.

**Comment by revmischa** [comment]
This fix should be merged now
