### ISSUE TITLE
Build fails with GLES and pulseaudio/qt

### ISSUE THREAD

**Issue by ggardet** [projectM-visualizer/projectm#356]
To fix build with GLES of pulseaudio/qt I need to add `#include <GL/gl.h>` in `src/projectM-qt/qprojectmwidget.hpp`.
Otherwise, I get errors on undefined GL functions.

**Comment by revmischa** [comment]
On what platform?
PR very welcome!

**Comment by ggardet** [comment]
aarch64, with GL ES.

**Comment by kblaschke** [comment]
Should be fixed in latest master, as the C API doesn't expose the projectM C++ header anymore, removing any need to include OpenGL headers in files calling projectM functions.

If this is still an issue in latest master, please reopen.
