### ISSUE TITLE
Fails to find GLuint

### ISSUE THREAD

**Issue by yurivict** [projectM-visualizer/projectm#36]
```
--- libRenderer_la-Renderer.lo ---
In file included from Renderer.cpp:1:
In file included from ./Renderer.hpp:4:
./FBO.hpp:78:3: error: unknown type name 'GLuint'
  GLuint initRenderToTexture();
  ^
```

```GL/gl.h``` is included only when ```EMSCRIPTEN``` is defined, and ```EMSCRIPTEN``` isn't defined. It seems that it is defunct, it isn't ever defined.

Version 2.2.0

**Comment by revmischa** [comment]
Odd, it's building for me on OSX and linux ok: https://travis-ci.org/projectM-visualizer/projectm/builds/350333601

Down below it should include:
```
#ifdef __linux__
#ifdef USE_GLES1
#include <GLES/gl.h>
#else
#include <GL/gl.h>
#include <GL/glx.h>
#endif
#endif
```

May I ask what system this is?

**Comment by yurivict** [comment]
> May I ask what system this is?

FreeBSD. I am trying to update the port.

**Comment by revmischa** [comment]
Okay, I'm assuming `#ifdef __linux__` isn't the best check for FreeBSD. What would be a better define to check? Does it need to be changed everywhere?
Also, do you know if Travis supports FreeBSD? Would be good to have CI for it.

**Comment by revmischa** [comment]
Also may need to add a BSD check in configure.ac under "Freedom":
https://github.com/projectM-visualizer/projectm/blob/master/configure.ac#L66

**Comment by revmischa** [comment]
Please let me know how I can assist!

**Comment by revmischa** [comment]
@yurivict peep https://github.com/projectM-visualizer/projectm/pull/37
Builds for me ok

**Comment by yurivict** [comment]
@revmischa The problem is gone with this patch.

One thing though is that I personally would've used:
```
#if defined(__linux__) || defined(__FreeBSD__) || defined(__OpenBSD__) || defined(__NetBSD__) || defined(__DragonFly__)
```

This catches all linuxes and all BSDs.

```__unix__``` might catch some systems like MacOS or CygWin where we don't know if this should be changed.

**Comment by yurivict** [comment]
Or maybe ```GL/gl.h``` should be included unconditionally, because the use is unconditional?

**Comment by revmischa** [comment]
It appears to build on OSX: https://travis-ci.org/projectM-visualizer/projectm/builds/351963692

They all have:
```
#ifdef __APPLE__
#include <OpenGL/gl.h>
#endif
```
However. Maybe it should be:
`#elseif __unix__ ...`?

**Comment by yurivict** [comment]
I would do:
```
#ifdef __APPLE__
#include <OpenGL/gl.h>
#endif

#if defined(__linux__) || defined(__FreeBSD__) || defined(__OpenBSD__) || defined(__NetBSD__) || defined(__DragonFly__)
#include <GL/gl.h>
#endif
```

It is easier to read (no elseifs), and doesn't make assumptions about systems we aren't sure about.

**Comment by splbio** [comment]
This could probably be cleaner, give me a minute to examine.

**Comment by revmischa** [comment]
is defined() a preprocessor keyword or something? i've never come across it before

**Comment by splbio** [comment]
yes it is, about to upload a patch with that as an example, but I can't build this today so maybe it can be improved upon.

**Comment by revmischa** [comment]
thanks! if one of you wants to open a new PR feel free.

**Comment by revmischa** [comment]
also see the configure.ac link i added earlier.. are there any flags needed for linking on freebsd? apple needs -framework CoreFoundation and limux needs -ldl. idk what bsd needs.

**Comment by yurivict** [comment]
There is no -ldl on BSDs.

**Comment by revmischa** [comment]
Closing in favour of https://github.com/projectM-visualizer/projectm/pull/41
