### ISSUE TITLE
Fedora 32: resolving dependencies

### ISSUE THREAD

**Issue by sckitt** [projectM-visualizer/projectm#362]
`sudo dnf install autotools autoconf libtool pkg-config which libglm-dev`
...
No match for argument: autotools
No match for argument: libglm-dev

All other packages installed successfully. Assuming I read [this](https://developer.fedoraproject.org/tech/languages/c/autotools.html) article correctly, autoconf & automake can be installed as substitute for autotools.

`autoreconf --install`
No issues

`./configure --enable-sdl`
...
configure: error: Could not find a valid OpenGL implementation

My main issue is libglm-dev, search results only show installation instructions for Ubuntu/Debian-based distros.

**Comment by autonarcosis** [comment]
It's not obvious.  Install these three for a start.

libglvnd-devel mesa-libGLU-devel freeglut

The projectm-pulseaudio fails to compile.  Only projectM-sdl works.

**Comment by revmischa** [comment]
If you figure it out please open a PR with documentation or configure fixes!

**Comment by sckitt** [comment]
Thank you @autonarcosis , I managed to compile projectMSDL but the program immediately closes.

`sudo dnf install libglvnd-devel mesa-libGLU-devel freeglut`
All packages installed successfully. Let's try this again.

`autoreconf --install`
No issues

`./configure --enable-sdl`
...
configure: error: *** libsdl2 not found!

`sudo yum install SDL2-devel` resolved the dependency.

`./configure --enable-sdl`
...
configure: error: libglm is required.

`sudo dnf install glm-devel` resolved the dependency.

`./configure --enable-sdl`
`make`
`sudo make install`
Successfully compiled but projectMSDL immediately closes

**Comment by kblaschke** [comment]
If you still have build issues, please try the CMake-based build scripts in the master branch. If the issue still persosts, feel free to reopen the issue!
