### ISSUE TITLE
discussion: compatibility of presets & implementation of shaders

### ISSUE THREAD

**Issue by auralarch** [projectM-visualizer/projectm#364]
I'm just curious…  

Has anyone experimented with doing side-by-side comparisons of presets?

One 'side' running the Milkdrop plugin in the final release of Winamp; the other 'side' running the sdl app on a Mac.  Use the same audio source for both, ensure that an identical set of presets is installed on both (including any textures or other required extras), set both apps to select presets in alphabetical order, configure as many of the other settings as possible to the same options…

This seems like an interesting & fun way to check for anomalies.  Compare performance; see if anything that may not be working or implemented in the same way;  discover how much of various presets is tightly controlled by the music and the parameters of the preset, and how much is left to chance.

**Comment by milkdropper** [comment]
It looks like https://github.com/mvsoft74/BeatDrop might be a good tool to test with. It seems to be completely based on the opensource Milkdrop2 and does loopback capture as well.

**Comment by milkdropper** [comment]
I grabbed two presets at random (I swear, no bias) and compared them side by side with BeatDrop.

The results are drastically different. 

**11.milk**
Video: https://streamable.com/w0gif1
This type of preset is always in motion. They look different.

**EoS - glowsticks v2 03 music shifter edit b (Jelly V2).milk**
Video: https://streamable.com/6g7bbz
This preset relies entirely on music. To get a really honest comparison I paused my music, reset both (hard transitions to it in both apps) then resumed the music while recording. They look different.

**Comment by revmischa** [comment]
Very interesting! I think it'd be a great project to look into the milkdrop source and compare https://sourceforge.net/projects/milkdrop2/files/milkdrop2_v2.25c_OPEN_SOURCED_20130514_orig_code.zip/download

**Comment by kblaschke** [comment]
With the above linked PR, most of the shader issues we had in the pst should be fixed. There will be a few remaining problems left, some which we probably can't solve due to differences between HLSL and GLSL. Only a few presets should be affected, so fixing the preset files might be a good approach (won't work for user-provided presets though).
