### ISSUE TITLE
REQUEST - look for .milk files anywhere in the presets folder

### ISSUE THREAD

**Issue by internetaddict40** [projectM-visualizer/projectm#367]
Or even better, anywhere in a .zip archive next to the executable! Because with tens of thousands of files in a folder it's slow to back up.

I downloaded a curated milkdrop preset pack from here: https://thefulldomeblog.com/2020/02/21/nestdrop-presets-collection-cream-of-the-crop/ and the files are organized in a folder structure.

ProjectM only looks for .milk files that are nested on the root of the preset folder. I can take all the .milk files and just drop them there (this is what I did right now), but with a folder structure it will be easier for me to know what to use for the occasion :)
![Capture](https://user-images.githubusercontent.com/13089641/83957304-c8af7680-a86f-11ea-85e5-03e7877a003e.PNG)

**Comment by revmischa** [comment]
Same as this request https://github.com/projectM-visualizer/projectm/issues/109

**Comment by revmischa** [comment]
Done in #385
