### ISSUE TITLE
Missing .dll error when opening

### ISSUE THREAD

**Issue by PhantomWatson** [projectM-visualizer/projectm#369]
For me, in Windows 10 (64 bit), opening `projectM.exe` from `projectM-sdl-win-x64.zip` of version 3.1.3 results in this error message:

> The code execution cannot proceed because VCRUNTIME140_1.dll was not found. Reinstalling the program may fix this problem.

Does the program have some other software dependency or have some other installation step that I'm overlooking or that needs to be documented?

**Comment by PhantomWatson** [comment]
The 64-bit version worked for me. Thanks! Could this advice be added to the documentation for installing the Windows release?

**Comment by milkdropper** [comment]
Thanks for confirming back.

Yes, I think that adding this to the readme makes sense.

**Comment by milkdropper** [comment]
Fiexd with steam release: https://store.steampowered.com/app/1358800/projectM_Music_Visualizer/

Fixed by adding requirement in documentation for binary release. https://github.com/projectM-visualizer/projectm/commit/c5533e3efeea2ce1a5624b14d7dbebc686ee6799#diff-04c6e90faac2675aa89e2176d2eec7d8
