### ISSUE TITLE
How to set x axis and y axis? 

### ISSUE THREAD

**Issue by osh67** [projectM-visualizer/projectm#373]
Hello, I’m trying to figure out how to set the x axis and y axis on this, not to sure what or how I figure out what it should be set for. 
I have the app on a xtrons android car radio with PX5 chip. 
Both are set to 24 at the moment, seams to be laggy on some visualizers.

**Comment by revmischa** [comment]
There should be a config file, probably in /usr/local/share/projectM
Unless you're using it from the app store; that is not maintained by this community.
