### ISSUE TITLE
Discussion: releasing projectM on Steam

### ISSUE THREAD

**Issue by milkdropper** [projectM-visualizer/projectm#375]
I had the idea to release projectM on [Steam](https://store.steampowered.com/). Steam is a video game distribution service but it also has sections for utilities and applications. 

My view is that benefits to releasing on Steam are:
- it reaches an audience of tech savvy PC owners (94 million monthly active users)
- it is cross platform: you can release builds in Windows, Mac, and Linux
- users can edit the presets (right now projectM on Windows Store is limited as you can't edit presets)
- updates can be pushed automatically using Steam: binary changes or preset updates can be pushed as an "update" that Steam handles in the background through their content delivery network.
- it might be possible to get metrics on downloads and monthly active users

I created the collateral (screenshots and descriptions) and published the SDL version of the [windows binary of projectM](https://store.steampowered.com/app/1358800/projectM_Music_Visualizer/). There is a requirement to wait two weeks before the binary can be downloaded, so it's in pre-release mode right now.

My goals are to: 
- push macOS and Linux builds in the near future [short term]
- provide binary updates for fixes and enhancements committed to github [ongoing]
- add VR support (Steam has built in SteamVR support which is compatible with multiple headset vendors, and is used by many PC VR users) [long-term]

So in this topic I would like to ask for comments and recommendations for the collateral (additional screenshots or videos would be welcome).

**Comment by revmischa** [comment]
Sounds super great. I believe Valve are actually the maintainers of SDL now? SDL and Steam should go together like vodka and pickles. We have macOS builds that I've been doing (`make dist-mac` is all you need to run on a mac to spit it out).
Linux builds should be very easy to automate, what do we need for that? Do they need to be statically built? Can we assume libsdl2 is available? I would assume so.

**Comment by milkdropper** [comment]
I'm glad to see your enthusiasm!

I did get a build working on macOS Catalina but I just need to familiarize myself with distributing macOS packages and how they work with Steam. I am not sure if they are bundles that get put into /Applications or something different. I only use macOS at work where I don't have Steam or even normal build tools.

For Linux it looks like [Valve recommends SDL](https://partner.steamgames.com/doc/store/application/platforms/linux#FAQ) and it should be available in SteamOS at least. 

Finally for Windows, when I prepared the package with Steam I was able to require the VC++ redistributable. This means it gets installed by Steam before you can run the binary (if it's not there already). See https://github.com/projectM-visualizer/projectm/issues/369

I think making cross-platform releases in the next two weeks before it's allowed to go live should be very possible. I will ask friends/the community here to test it in a setup where they don't have any prerequisites installed to make sure it works out of the box when downloaded from Steam.

**Comment by revmischa** [comment]
Sounds tremendous, thanks for doing this

**Comment by revmischa** [comment]
Are you imagining it would be free?

**Comment by milkdropper** [comment]
Yes for sure! 

I'm not sure if you can donate through Steam, but maybe that could be used to fund things for team requirements like hosting in the future.

**Comment by rullinoiz** [comment]
i third this, i think it would be amazing if it were on steam

**Comment by milkdropper** [comment]
projectM has been release for free on steam.

https://store.steampowered.com/app/1358800/projectM_Music_Visualizer/

**Comment by rullinoiz** [comment]
> projectM has been released for free on steam.
> 
> 
> 
> https://store.steampowered.com/app/1358800/projectM_Music_Visualizer/

yoo they actually did it
