### ISSUE TITLE
Autoreconf fails exit status 1

### ISSUE THREAD

**Issue by garageman2335** [projectM-visualizer/projectm#376]
automake fails on ubuntu 20.04

`autoreconf --install
src/NativePresets/Makefile.am:16: error: Libtool library used but 'LIBTOOL' is undefined
src/NativePresets/Makefile.am:16:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
src/NativePresets/Makefile.am:16:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
src/NativePresets/Makefile.am:16:   If 'LT_INIT' is in 'configure.ac', make sure
src/NativePresets/Makefile.am:16:   its definition is in aclocal's search path.
src/libprojectM/Makefile.am:14: error: Libtool library used but 'LIBTOOL' is undefined
src/libprojectM/Makefile.am:14:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
src/libprojectM/Makefile.am:14:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
src/libprojectM/Makefile.am:14:   If 'LT_INIT' is in 'configure.ac', make sure
src/libprojectM/Makefile.am:14:   its definition is in aclocal's search path.
src/libprojectM/MilkdropPresetFactory/Makefile.am:1: error: Libtool library used but 'LIBTOOL' is undefined
src/libprojectM/MilkdropPresetFactory/Makefile.am:1:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
src/libprojectM/MilkdropPresetFactory/Makefile.am:1:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
src/libprojectM/MilkdropPresetFactory/Makefile.am:1:   If 'LT_INIT' is in 'configure.ac', make sure
src/libprojectM/MilkdropPresetFactory/Makefile.am:1:   its definition is in aclocal's search path.
src/libprojectM/NativePresetFactory/Makefile.am:1: error: Libtool library used but 'LIBTOOL' is undefined
src/libprojectM/NativePresetFactory/Makefile.am:1:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
src/libprojectM/NativePresetFactory/Makefile.am:1:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
src/libprojectM/NativePresetFactory/Makefile.am:1:   If 'LT_INIT' is in 'configure.ac', make sure
src/libprojectM/NativePresetFactory/Makefile.am:1:   its definition is in aclocal's search path.
src/libprojectM/Renderer/Makefile.am:2: error: Libtool library used but 'LIBTOOL' is undefined
src/libprojectM/Renderer/Makefile.am:2:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
src/libprojectM/Renderer/Makefile.am:2:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
src/libprojectM/Renderer/Makefile.am:2:   If 'LT_INIT' is in 'configure.ac', make sure
src/libprojectM/Renderer/Makefile.am:2:   its definition is in aclocal's search path.
src/projectM-qt/Makefile.am:44: error: library used but 'RANLIB' is undefined
src/projectM-qt/Makefile.am:44:   The usual way to define 'RANLIB' is to add 'AC_PROG_RANLIB'
src/projectM-qt/Makefile.am:44:   to 'configure.ac' and run 'autoconf' again.
autoreconf: automake failed with exit status: 1`

**Comment by revmischa** [comment]
Do you by chance not have `libtool` installed?

**Comment by garageman2335** [comment]
could have sworn I installed it but that fixed it thanks.
