### ISSUE TITLE
Docs Needed: Keys, Config File Reference [ToDo]

### ISSUE THREAD

**Issue by revmischa** [projectM-visualizer/projectm#379]
If someone wants to update the README or otherwise this would be greatly useful as evidenced by comments in various issues here
And where to find config files is needed documenting

Keybindings can mostly be found here: https://github.com/projectM-visualizer/projectm/blob/master/src/libprojectM/KeyHandler.cpp#L115

Config file reference and paths should be nearby

**Comment by revmischa** [comment]
Also would be nice: help menu, text when opening projectMSDL

**Comment by milkdropper** [comment]
Can you accept https://github.com/projectM-visualizer/projectm/pull/284 so the config file has a proper home in Windows? I can then update the build process on projectMSDL on Windows so it pushes a config.inp into the package and update the documentation at the same time.

**Comment by Shrey-Dua** [comment]
Hi ! 
I am a beginner and i would like to contribute , could you help me out please ?

**Comment by revmischa** [comment]
@Shrey-Dua sure what do you need help with? https://docs.github.com/en/github

**Comment by KishkinJ10** [comment]
I am a beginner can i work on this ? can you please guide me from where should i start?

**Comment by revmischa** [comment]
Open a pull request with changes to README.md, create a new markdown file and link to it from the README.md, or set up a [wiki](https://github.com/projectM-visualizer/projectm/wiki). Your choice. Wiki might be friendliest.

**Comment by NoobMaster1999** [comment]
is this issue still open?

**Comment by revmischa** [comment]
Yes please just open a PR
