### ISSUE TITLE
3.1.7: Build fails: error: no matching function for call to 'fts_open'

### ISSUE THREAD

**Issue by yurivict** [projectM-visualizer/projectm#396]
```
FileScanner.cpp:144:18: error: no matching function for call to 'fts_open'
    fileSystem = fts_open(dirList, FTS_LOGICAL|FTS_NOCHDIR|FTS_NOSTAT, &fts_compare);
                 ^~~~~~~~
/usr/include/fts.h:131:6: note: candidate function not viable: no known conversion from 'int (*)(const FTSENT **, const FTSENT **)' (aka 'int (*)(const _ftsent **, const _ftsent **)') to 'int (*)(const FTSENT *const *, const FTSENT *const *)' (aka 'int (*)(const _ftsent *const *, const _ftsent *const *)') for 3rd argument
FTS     *fts_open(char * const *, int,
         ^
FileScanner.cpp:147:27: warning: comparison of integers of different signs: 'int' and 'std::__1::vector<std::__1::basic_string<char>, std::__1::allocator<std::__1::basic_string<char> > >::size_type' (aka 'unsigned long') [-Wsign-compare]
        for (int i = 0; i < _rootDirs.size(); i++)
                        ~ ^ ~~~~~~~~~~~~~~~~
1 warning and 1 error generated.
```

clang-9
FreeBSD 12.1

**Comment by revmischa** [comment]
Does this help? https://github.com/projectM-visualizer/projectm/pull/397
I knew this would be an issue ...

**Comment by yurivict** [comment]
The error still exists with patches from https://github.com/projectM-visualizer/projectm/pull/397

**Comment by revmischa** [comment]
Oh I guess I should have read closer
`/usr/include/fts.h:131:6: note: candidate function not viable: no known conversion from 'int (*)(const FTSENT **, const FTSENT **)' (aka 'int (*)(const _ftsent **, const _ftsent **)') to 'int (*)(const FTSENT *const *, const FTSENT *const *)' (aka 'int (*)(const _ftsent *const *, const _ftsent *const *)') for 3rd argument`

Weird, the compare function has a different signature on FreeBSD from macOS and Linux? What should it be?

**Comment by abenson** [comment]
The problem is fts.h isn't portable. glibc's is definitely broken.

**Comment by revmischa** [comment]
It compiles fine on macOS, I thought it should have a similar userspace interface to FreeBSD. It is definitely not glibc.
Any ideas? Suggestions?

**Comment by abenson** [comment]
Sorry, I wasn't saying this was a glibc issue. I was just saying that fts is not a portable library.

**Comment by yurivict** [comment]
There is a minor signature difference, and I patched it in the port.
