### ISSUE TITLE
Stand Alone Mac Version

### ISSUE THREAD

**Issue by gooddadmike** [projectM-visualizer/projectm#4]
I would love a stand alone version of this that would work with Mac OS. Also a version for (or instructions on how to use with ) VLC on Mac OS.

Thanks!

**Comment by revmischa** [comment]
I'd love one too! Patches welcome.

**Comment by revmischa** [comment]
See: #14

**Comment by revmischa** [comment]
There is a semi-working mac standalone version now - the SDL version. works on any platform actually. https://github.com/projectM-visualizer/projectm/commit/83ca57979289cc6ef05c13d2f1c47f48efbe6729
