### ISSUE TITLE
NSM support?

### ISSUE THREAD

**Issue by mxmilkiib** [projectM-visualizer/projectm#417]
NSM is a session management system, originally [this](http://non.tuxfamily.org/wiki/Non%20Session%20Manager), now [that](https://linuxaudio.github.io/new-session-manager/) (a #lad community led fork). It allows users to save the exact state of a session, close it, then later restore it. It has very much been an audio app thing so far but I think the fact that the "audio/visual" overlap is so big is argument enough to make the suggestion that a portion of projectM users would benefit from projectM also supporting NSM at some point.

**Comment by kblaschke** [comment]
Seems like NSM is no longer maintained, as the linked repo doesn't exist anymore. If there's some future development happening on this, feel free to reopen.

Plus, libprojectM has no dependency on any audio subsystem, it simply consumes audio data from any source.

**Comment by mxmilkiib** [comment]
There was a move of stewardship from https://github.com/linuxaudio to JACK https://github.com/jackaudio/new-session-manager after a complaint that LA org wasn't the right camp or flag or whatever for that.

Even with PipeWire, NSM is worth it for app level session saving. http://raysession.tuxfamily.org and https://laborejo.org/agordejo are the two main front-ends atm.
