### ISSUE TITLE
Screen Saver not working on 2017 Tegra SHIELD TV

### ISSUE THREAD

**Issue by pdschandler** [projectM-visualizer/projectm#418]
I just bought a 2017(?) SHIELD TV Pro (Model P2897), and the first thing I installed besides Plex was proejctM. Everything seems to work - except for the Screen Saver functionality, which is what I was really hoping to use.

projectM shows up as a screensaver selection, but selecting it closes (crashes?) the settings menu immediately. No slide-out animation; it just disappears. Upon opening the menu back up, there will be no change to the screensaver selection and it just remains on whatever the last one selected was (in this case, one of the three built-in options).

Would love to use projectM as a proper screensaver, as I have an OLED and this would be a great way to prevent burn-in while looking cool B-)

EDIT: Sorry for the edits on the title - I was unclear on what model I had for a moment.

**Comment by kblaschke** [comment]
If your support request is about the Play Store version of porjectM, we're sorry, but we cannot provide any support for this application as it's not being developed by the projectM open-source team. Please direct your request to the app developer, Peter Sperl, and contact him via the email address provided in the Play Store.
