### ISSUE TITLE
SOLVED! - ProjectM no longer working in Ubuntu 18.04.5 MATE 64bit on Clementine or Pulse Audio

### ISSUE THREAD

**Issue by leirbag28** [projectM-visualizer/projectm#425]
SOLVED Literally seconds after posting this.
I did "Force Version" on the package projectm-data from 3.1.1 to 2.1.0 in Synaptic Package manager, and rebooted! it worked!

Exactly a year ago Clementine and the Pulse audio version of ProjectM was working after I did that ttf font issue fix.....then I believe after I updated (Perhaps Pulse Audio Volume Control or the Pulse Effects app) it stopped going past the dancing ProjectM logo where it always stays now. Please Help!

leirbag28@yahoo.com

**Comment by mikewesten** [comment]
Hey thanks for that. Force Version in Synaptic did the trick for me. I'm still puzzled over the missing folder 'textures' in /usr/share/projectM/ that is supposedly being called upon according to the terminal readout. I think I botched the installation pretty badly but downgrading it to version 2 is at least giving me a serviceable app for now.

**Comment by leirbag28** [comment]
Hey Thanks for the Response! Yeah I Forced the older one and It worked. Now the missing textures may not be missing at all. I noticed there are 2 locations in ubuntu...ine for the stand alone ProjectM and one for Clementine...strangely both stopped working and then both were working when I forced the older version.

I have another question: therr is an awesome website called: butterchurnviz.com which is a fully working MilkDrop visualizer
Online...i downloaded the presets somewhere and added them to clementines presets...and ProjectM's but apparently it doesnt work that way...I had to revert back and leave the original presets..and just copy over the new extra ones...seems to work but some textures dont as they seem to require more CPU and GFX power.

**Comment by MeanAngryVeteran** [comment]
Thank you leirbag28 for posting this 
I'm running  Mint 19.3 Tricia Mate flavor, and your instructions worked like a charm.  I've been beating my head against the wall on this for months.

**Comment by MeanAngryVeteran** [comment]
leirbag28  Thanks for posting this
I  Forced  Version 2.1.0 projectm-data through Synaptic.
I'm running Mint 19.3 Tricia Mate flavor, and your instructions worked like a charm. I've been beating my head against the wall and wasting hours trying to fix this for months.
