### ISSUE TITLE
Save visualisation as video

### ISSUE THREAD

**Issue by swschilke** [projectM-visualizer/projectm#432]
Hallo,

it would be really nice to be able to save an audio visualisation as a video file.

Kind regards

.

**Comment by Iiridayn** [comment]
Possible duplicate of #205.

**Comment by revmischa** [comment]
PRs are very welcome!

**Comment by swschilke** [comment]
> PRs are very welcome!

Hallo, what is the meaning of that? Sorry the meaning of PR is unknown to me.

Kind regards 

.

**Comment by revmischa** [comment]
It is how one contributes changes or improvements to an open-source project
https://guides.github.com/activities/hello-world/
