### ISSUE TITLE
Microphone does not work on Android build

### ISSUE THREAD

**Issue by Piecho2** [projectM-visualizer/projectm#433]
Hello,
I have Android 9 TV https://www.displayspecifications.com/en/model/761e20ba
I sideloaded free build of the app. Works fine when audio is played from any other app in the TV, but does not work with microphone build in tv remote. I tried to remove access to mike and add it again, did not help.
Would like to try any beta build of AndroidTV version, I am afraid that this function will not work in paid version in GP and I know, how hard is get money back to card form GP.

**Comment by kblaschke** [comment]
Please contact the author (Peter Sperl) directly for any support on the Play Store/Amazon version of the projectM Android app. The app is closed-source and the projectM team cannot help with any issues regarding it.
