### ISSUE TITLE
Kodi build - add support for external microphone?

### ISSUE THREAD

**Issue by Piecho2** [projectM-visualizer/projectm#434]
Is there possibility to add support for external microphone for Kodi build, like in Android one? 
Would appreciate build where I could run app in full screen and it would take input from my TV remote mic - https://www.displayspecifications.com/en/model/761e20ba

**Comment by kblaschke** [comment]
Audio input in Kodi is handled by the host application, the projectM library only receives audio data via the integration API and knows nothing about any input devices.

I suggest you open a feature request [in the Kodi issue tracker](https://github.com/xbmc/xbmc/issues) instead, as this is not even directly related to the visualization plug-in, but rather a new Kodi feature.
