### ISSUE TITLE
Preset not change

### ISSUE THREAD

**Issue by lollita** [projectM-visualizer/projectm#437]
I'm not able to change preset in Windows standalone.
Every have "Geiss & Sperl - Feedback (projectM idle HDR mix)".
I trye "R" "N" "P" but not change

**Comment by lollita** [comment]
I understood immediately that because RamDisk.

**Comment by revmischa** [comment]
What?

**Comment by lollita** [comment]
When I use RamDisk the projectM not change preset.
I have to moe projectM to a real Hard disk location.
