### ISSUE TITLE
Chromecast TV 

### ISSUE THREAD

**Issue by Zepaly** [projectM-visualizer/projectm#439]
I have it on the phone and Chromecast TV, the phone looks aaaaaawwwwwssssssoooommmmmmeeeee, but the TV experience stutters, any way there could be a balanced preset for chromecast with google TV so it just works, I'm sure the chrome is way slower!

BTW, been a fan since R4!, or was it R2?!

**Comment by jimcarst** [comment]
Same, the chromecast visuals barely react to the music.

**Comment by kblaschke** [comment]
I'm assuming you're talking about the Android app that's available in the Google Play Store, right?

In this case, we're sorry, but we cannot provide support for this app as it's not being developed by the core projectM open-source team. Please request support from the author, Peter Sperl, via the contact means provided in the Play Store.
