### ISSUE TITLE
Intel Haswell incompatibility (GLSL 3.30 not supported)

### ISSUE THREAD

**Issue by IlgazC** [projectM-visualizer/projectm#448]
Hello
I have an Apple Mac Mini here (late 2014 I guess) with Intel Iris graphics. When I launch ProjectM under X11 (wayland doesn't work) I get the following messages and 2 white rectangles

projectM-pulseaudio 
Default config: /usr/share/projectM/config.inp
reading /home/ilgaz/.projectM/config.inp 
[projectM] config file: /home/ilgaz/.projectM/config.inp
Failed to compile shader 'Vertex: v2f_c4f'. Error: 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, and 3.10 ES

Failed to compile shader 'Fragment: v2f_c4f'. Error: 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, and 3.10 ES

Failed to link program: error: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shader
Failed to compile shader 'Vertex: v2f_c4f_t2f'. Error: 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, and 3.10 ES

Failed to compile shader 'Fragment: v2f_c4f_t2f'. Error: 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, and 3.10 ES

Failed to link program: error: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shader
Failed to compile shader 'Vertex: blur1'. Error: 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, and 3.10 ES

Failed to compile shader 'Fragment: blur1'. Error: 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, and 3.10 ES

Failed to link program: error: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shader
Failed to compile shader 'Vertex: blur2'. Error: 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, and 3.10 ES

Failed to compile shader 'Fragment: blur2'. Error: 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, and 3.10 ES

Failed to link program: error: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shader
device name is  "alsa_output.pci-0000_00_03.0.hdmi-stereo-extra1.monitor"
reconnecting with "alsa_output.pci-0000_00_03.0.hdmi-stereo-extra1.monitor"
unconnected: connecting...
connectHelper:  "alsa_output.pci-0000_00_03.0.hdmi-stereo-extra1.monitor"
CREATED
READY
TERMINATED

Output of inxi -G

inxi -G
Graphics:  Device-1: Intel Haswell-ULT Integrated Graphics driver: i915 v: kernel 
           Display: x11 server: X.org 1.20.10 driver: modesetting unloaded: fbdev,vesa 
           resolution: <xdpyinfo missing> 
           OpenGL: renderer: Mesa DRI Intel Iris Graphics 5100 (HSW GT3) v: 4.5 Mesa 20.3.3

**Comment by revmischa** [comment]
Have you tried compiling with GLES enabled?

**Comment by IlgazC** [comment]
Strangely enough "Steam" version of ProjectM works (opensuse TW here) although I can't set the audio input option.

**Comment by IlgazC** [comment]
> Have you tried compiling with GLES enabled?

I am using the openSUSE Tumbleweed binary package (distro's official one) https://software.opensuse.org/package/projectM

**Comment by IlgazC** [comment]
When I try to compile from source I get the following:

checking glm/glm.hpp presence... no
checking for glm/glm.hpp... no
configure: error: vendored libglm not found.

Perhaps it is related?

**Comment by revmischa** [comment]
Odd, are you building from master on github? That directory should exist - https://github.com/projectM-visualizer/projectm/tree/master/vendor/glm

**Comment by IlgazC** [comment]
> Odd, are you building from master on github? That directory should exist - https://github.com/projectM-visualizer/projectm/tree/master/vendor/glm

Strange really. Directory also exists here in source tree but it isn't "seen" anyhow. btrfs here (default on openSUSE TW)

**Comment by IlgazC** [comment]
I started to believe that there is a major incompatibility of projectM with this particular graphics processor. This is the most "working" thing I get from projectM from VLC built in version.
![Screenshot_20210210_083204](https://user-images.githubusercontent.com/19528613/107469334-9e3e5780-6b7a-11eb-9e6c-40620d4d89ea.png)

**Comment by kblaschke** [comment]
I don't really like to close this issue, but if the GPU or driver doesn't support a least shader language version 3.30, there's nothing we can do.

Reason is that version 3.30 introduced texture sampling support, which is a integral part of Milkdrop 2.0 presets (can't use data from the per-pixel equation output otherwise).

Sure enough we could only load presets that don't use comp/warp shaders (AKA Milkdrop 1.x presets), which might be a viable fallback option in the future, but that would require some major rewrite of the preset loader code to enable skipping and removing incompatible presets from the internal playlist.
