### ISSUE TITLE
PipeWire application

### ISSUE THREAD

**Issue by Be-ing** [projectM-visualizer/projectm#452]
[PipeWire](https://pipewire.org/) is going to replace PulseAudio and JACK soon. It will also handle routing video between applications. This could make it a great fit for projectM.

**Comment by alex-tee** [comment]
there's already a JACK application and pipewire replaces the jack library and implements the JACK API, so there's no need to write something specific for pipewire, the JACK app will work transparently over pipewire. the pipewire creators even advise against implementing the pipewire API

**Comment by Be-ing** [comment]
Yes, and PipeWire also handles video routing between applications. Exposing a PipeWire video feed would be awesome.

**Comment by alex-tee** [comment]
ok video feed is another story, then using pipewire makes sense

**Comment by kblaschke** [comment]
PulseAudio and JACK are currently only supported by the Qt fontend. There's discussion about replacing both specializations with a single PortAudio-based recording solution. As PipeWire provides both PulseAudio and JACK services, existing cross-platform libraries will work fine with it.

The projectM library itself only cares about visualization, not where the audio comes from, so it's generally up to the host application to supply audio data from whatever source. The example frontends (both Qt and SDL) are basically reference implementations that should work on multiple platforms - thus, using a cross-platform audio library is a better idea than using another platform-specific API.

**Comment by kblaschke** [comment]
Feeding video into it is another extra that isn't directly handled by projectM, but up to an application that specializes on this. Once PipeWire is a more wide-spread API, we might consider creating a sample application as a separate repository that demonstrates how to record audio from PipeWire and send video stream with the visualization back into it.

I'll close this issue for now, as this isn't anything we need to consider mid-term. Once PipeWire sees more use, please feel free to add a feature request for the mentioned example application.

**Comment by Be-ing** [comment]
On further thought, I don't know if there is anything projectM would need to do to provide a PipeWire video stream other than creating a Wayland window.

**Comment by kblaschke** [comment]
With the Qt Wayland output plugin, this should work out of the box without code changes then. SDL2 possibly also has Wayland support.
