### ISSUE TITLE
CMake build system

### ISSUE THREAD

**Issue by Be-ing** [projectM-visualizer/projectm#453]
Visual Studio project files are a hassle to use and maintain. Switching to CMake would make it easier to use libprojectM on Windows and package it in vcpkg.

**Comment by kblaschke** [comment]
Not only for Windows, using CMake makes it easier on other platforms as well and the devs have to maintain only a single set of build scripts for all platforms. It's also easier to use for devs working with other IDEs like CLion.

I've got some spare time in the next few days and could spend some of it creating a set of CMake build scripts, including proper package config files etc. and raise a PR for it.

**Comment by revmischa** [comment]
Okay. Is there anything newer/better than CMake? 
ProjectM was CMake, I found it really annoying but maybe it was set up wrong. I think I'm too dumb to understand the cmake docs (not that autotools docs are any better..). If you dig through the history you can find the old CMake configs (like https://github.com/projectM-visualizer/projectm/pull/17/commits/7828b8fe07bb1d8df658bb9eb60febdb71d95113)

**Comment by Be-ing** [comment]
> Okay. Is there anything newer/better than CMake?

Not AFAIK. There is Meson, but it's problematic for packagers because it is implemented in Python so it has to pull in a huge tree of build dependencies.

**Comment by Be-ing** [comment]
CMake has more and more momentum behind it now. Microsoft has integrated it into their development tools. Qt6 is now using CMake. Pretty much every IDE Just Works with CMake.

**Comment by Be-ing** [comment]
>  I think I'm too dumb to understand the cmake docs

The CMake documentation is abysmal.

**Comment by kblaschke** [comment]
CMake has evolved a lot in the past few years, so did the documentation (they've added a whole bunch of examples and explanations), but it still has its pitfalls for sure, especially when it comes to the policy/version magic. From my experience, if done properly, you can generate really well-structured VS solutions with CMake, and since VS also has quite good CMake support in the 2019 version, this should feel quite natural.

I'll do my best to provide a solid set of modern CMake files which work on all supported platforms and add documentation to BUILDING.md. I can test building on Windows, MacOS, Linux and with Emscripten.

**Comment by revmischa** [comment]
Hey if you wanna own it you have my blessing! 🙏🏻 
Moving to GitHub Actions would be nice too...

**Comment by revmischa** [comment]
I invite everyone to discuss on Discord if you wanna chat https://discord.gg/tpEuywB

**Comment by Be-ing** [comment]
>  Moving to GitHub Actions would be nice too...

Yes GitHub Actions' matrix feature and CMake is a good combination for cross platform CI.

**Comment by kblaschke** [comment]
Will join Discord later or tomorrow. I'll push my work as I progress to the [cmake-build-system](https://github.com/kblaschke/projectm/tree/cmake-build-system) branch, if you want to follow, but don't expect it to compile on every commit.

**Comment by Be-ing** [comment]
#487 implemented this. Will the other build systems be removed now? Supporting multiple build systems is maintenance nightmare that has a high probability of subtly inconsistent behavior between build systems.

**Comment by revmischa** [comment]
@Be-ing agreed we should have one build system.

It would be ideal if we could use cmake to generate VS/xcode/autotools to make life easier for downstream without the maintenance nightmare.

**Comment by kblaschke** [comment]
Also totally agree to only have a single build system. Should thoroughly test the CMake scripts on all systems to make sure all works as before, then remove the other files. After that, making changes to the codebase will also be easier.

@revmischa If you could look into adding automated builds with CMake in GitHub Actions, that'd be great!

**Comment by revmischa** [comment]
Sorry but I simply don't have time right now to do anything

**Comment by kblaschke** [comment]
No problem, local testing should do it for now.

Will make a new branch and clean up the no longer required project files. Some need to stay though like the EyeTunes app until there's a good way to port these to CMake as well.

**Comment by Be-ing** [comment]
I don't have much time now either, but take a look at the crossplatform GitHub Actions workflows using CMake that I wrote for [libkeyfinder](https://github.com/mixxxdj/libkeyfinder/blob/main/.github/workflows/build-and-test.yml) and [PortAudio](https://github.com/Be-ing/portaudio/blob/cmake_rewrite/.github/workflows/cmake.yml) for examples.
