### ISSUE TITLE
texture loading in apps

### ISSUE THREAD

**Issue by mbellew** [projectM-visualizer/projectm#466]
I noticed that textures are often broken in projectM-pulseaudio.  I tracked it down to the fact that project::readConfig("config.inp") calls projectM::projectM_init() which calls new Renderer(). This sets Render.presetURL.  This gets used in all subsequent calls to new TextureManager().

Render.presetURL never gets updated, so all texture lookup is happening based on the config.inp value of "Preset Path".  However, QProjectM_MainWindow::postProjectM_Initialize() goes on to load "PlaylistFile" from qSettings.  This changes what presets directory, but not where it is looking for textures.

Maybe we need a push/popTexturePath() thta the app can use, and/or add the directory of the current directory to the texture search  path.

**Comment by kblaschke** [comment]
Texture support in preset shaders is currently quite broken and requires some major work to match Milkdrop's implementation.

Just created a new issue #532 for these problems, which should also fix the path problems (looking only in the current preset's directory, which is what Milkdrop does). Will also reduce startup time and GPU memory consumption drastically if there are many images in the preset dir.
