### ISSUE TITLE
Can't compile applications using libprojectM due to missing header

### ISSUE THREAD

**Issue by ericonr** [projectM-visualizer/projectm#468]
Hi! f7f74b11e3d089b4fbf7163319317c4daf6ea1a5 seems to have reorganized a bunch of stuff, which included switching from using the `__SSE2__` macro to your own `_HAS_SSE2_` one, using a dedicated header to (I assume) avoid duplicating code.

Unfortunately, the new `Intrinsics.h` header was included directly in `Common.h`, but isn't installed, which lead to build failures for applications which can link to a system projectM (in our case, the clementine player and qmmp).

I don't know if the preferred course of action is installing the new header or making it internal only (which IMO would be better, since it seems to be only an implementation detail), so I'm not opening a PR for now.

**Comment by revmischa** [comment]
Thanks for the report, I just ran into this myself. You're entirely right. That file ended up being pointless anyway. I was trying to work around multi-arch compilation issues for amd64/aarch64 for macOS but this didn't help.
I've reverted the change and done away with `Intrinsics.h` - b3c3282e
I wasn't aware of qmmp, please add it to the README! 
Feel free to chat w/ us on Discord.
