### ISSUE TITLE
Android TV, new Chromecast: "media information" turned on but isn't displayed

### ISSUE THREAD

**Issue by SimonDedman** [projectM-visualizer/projectm#478]
Per title, new latest gen chromecast, android tv, music streaming to the chromecast via bubbleUPNP from android phone, playing fine. Then back out, start ProjectM, press play (which starts the music), all working well BUT the media information displayed is the visualiser plugin info, not the music info.

**Comment by kblaschke** [comment]
Please ask the author of the store version, Peter Sperl, directly for support on that issue.

The app is closed-source and we can't do anything about it.
