### ISSUE TITLE
Add rating system / favourite / never-again to android TV version

### ISSUE THREAD

**Issue by SimonDedman** [projectM-visualizer/projectm#479]
Again per title, please add the ability to 'favourite' a preset, and also to hide presets, since some are dead.
Ability to import/export/sync plugin lists would be great as well.
Cheers!

**Comment by revmischa** [comment]
I don't think any of the android apps are a part of this open source project, sorry

**Comment by SimonDedman** [comment]
Ah ok thanks

**Comment by SimonDedman** [comment]
that said, the google play website does point here...
