### ISSUE TITLE
I'm a noob who doesn't know how to install the windows standalone version

### ISSUE THREAD

**Issue by ToG-128** [projectM-visualizer/projectm#480]
pleze halp.

I downloaded projectM-3.1.12.tar.gz, but after extracting it with 7zip I get a folder with no .exe file. what is needed to actually run the program?
Any help would be greatly appreciated

**Comment by revmischa** [comment]
That's the source code to build the software. Try getting it from Steam or here https://github.com/projectM-visualizer/projectm/releases/tag/v3.1.7
