### ISSUE TITLE
segfault on archlinux with jalv.gtk3 and ProM lv2 plugin

### ISSUE THREAD

**Issue by alex-tee** [projectM-visualizer/projectm#485]
using this LV2 plugin wrapper of projectm: https://github.com/DISTRHO/ProM (`make DEBUG=true` to build with symbols)
it segfaults when pressing "R" (random)

OS: Parabola (Arch Linux based)
jalv: 1.6.6-1 from official repos
dpf-plugins: 1.4-1 from official repos
projectm: 3.1.12-1 from official repos

command: `jalv.gtk3 http://distrho.sf.net/plugins/ProM`
with gdb: `gdb --args jalv.gtk3 http://distrho.sf.net/plugins/ProM`

don't have debug builds at the moment but seems to crash inside ProjectM:
```
[Switching to Thread 0x7fffeffff640 (LWP 288503)]
0x00007ffff44c0207 in PCM::addPCMfloat(float const*, int) () from /usr/lib/libprojectM.so.3
(gdb) bt
#0  0x00007ffff44c0207 in PCM::addPCMfloat(float const*, int) () at /usr/lib/libprojectM.so.3
#1  0x00007ffff461a7f5 in  () at /usr/lib/lv2/ProM.lv2/ProM.so
#2  0x00007ffff461dcee in  () at /usr/lib/lv2/ProM.lv2/ProM.so
#3  0x000055555555bdfc in  ()
#4  0x00005555555605d8 in  ()
#5  0x00007ffff7dc2e82 in  () at /usr/lib/pipewire-0.3/jack/libjack.so.0
#6  0x00007ffff7fb41eb in  () at /usr/lib/spa-0.2/support/libspa-support.so
#7  0x00007ffff6c7f070 in  () at /usr/lib/libpipewire-0.3.so.0
#8  0x00007ffff7f85299 in start_thread () at /usr/lib/libpthread.so.0
#9  0x00007ffff6dfb053 in clone () at /usr/lib/libc.so.6
(gdb) 
```

**Comment by kblaschke** [comment]
Could you please post a backtrace from all threads at the time of crash? This will make it easier to see if there's some race condition.

**Comment by kblaschke** [comment]
No details for six months, old version and third-party code involved. Closing the issue for now.

If the crash still happens after updating the mentioned plug-in code to the latest, feel free to reopen with a new stack trace.
