### ISSUE TITLE
macOS contributions

### ISSUE THREAD

**Issue by whitslar** [projectM-visualizer/projectm#507]
Been a few 4-5 years since I've built this on OSX, but there seems to be quite a few regressions? There used to be a menu dropdown to select your preset, I kinda remember a man page, keyboard shortcuts maybe also worked?

I just installed via brew today and it doesn't seem nearly as friendly to use as it once did...

Is there a group focused on macOS I could get in touch with to help out?

**Comment by revmischa** [comment]
The brew version is SDL, maybe you used the Qt version previously? You're welcome to come chat on discord https://discord.com/invite/tpEuywB

**Comment by kblaschke** [comment]
Pull request #525 will finally reenable the missing menu.

**Comment by kblaschke** [comment]
There were numerous build and bug fixes for macOS merged into master recently, if you now try again using the CMake build system and SDL from brew, it should work fine, including the on-screen menu.
