### ISSUE TITLE
Optimization Projects

### ISSUE THREAD

**Issue by revmischa** [projectM-visualizer/projectm#51]
## Things to speed up:
* PresetOutputs::PerPixelMath - this can probably be optimized a lot. It's called frequently.
* Convert shaders to GLSL (#26)

## Methodology:
Need to pick a preset and crank the mesh size up and then optimize things until framerate goes up.

Attached is some profile data in CSV form.
[Sampler  - SDLprojectM_Run2.csv.zip](https://github.com/projectM-visualizer/projectm/files/1887833/Sampler.-.SDLprojectM_Run2.csv.zip)

**Comment by mbellew** [comment]
You saw that I have a branch with PerPixelMath speed up using SSE (about 7x?).  I will make a pull request after I add some comments.  But that mostly helps presets that are already fast (less CPU% is good). https://github.com/mbellew/projectm/tree/sse

It is still expression evaluation that's the problem for most low frame-rate presets.  I have a few ideas, but I'd like feedback before wasting too much time.  Mischa, mentioned using shader technology, but I don't know anything about that and wouldn't know where to start.

A) Use the SSE instructions, basically create a new version of eval() that does four pixels/points at a time.
B) Use a real run-time compiler, e.g. translate the expressions into javascript and use v8 to jit and evaluate.

A is more straightforward and theoretically should be about 4x faster.  If nothing else we're going through the Y loop 1/4 as many times.  B could avoid the inner expression loop all together by combining all the per pixel expressions into one compiled function.  This might benefit complicated presets, while potentially being more expensive for simple ones.

**Comment by revmischa** [comment]
@splbio suggested using luajit

I do think the best approach would be using shaders, if possible. A compute shader could theoretically process the equations, and quite possibly parts of them (say, zoom) could be implemented as a vertex shader. This would have the GPU do all the work. Possibly even massively parallellized. 

This is separate (but maybe related) to the needed work to convert the existing shaders that are in some preset files to use GLSL (openGL) instead of HLSL and Cg (DirectX and an unmaintained old nvidia shader library).

SSE is great but not going to help for things like raspis or mobile devices.

**Comment by mbellew** [comment]
It seems like under any strategy, a first step is being really super explicit about the variable/Param semantics.  Basically assigning scoping rules to them like in any programming language.  global const, pure local, global variable (e.g. output variables/matrix), etc.  That would make it easier to attempt these really different evaluation ideas.

**Comment by splbio** [comment]
As long as the optimizer is a plug-in architecture so multiple strategies for different platforms can be attempted all should be good.

**Comment by revmischa** [comment]
Done in #62 I believe?
