### ISSUE TITLE
Not working with Plex on Firestick

### ISSUE THREAD

**Issue by vaderag** [projectM-visualizer/projectm#513]
Just downloaded to use for a party but while Plex is playing fine and the visualisers cycle, but it's clearly not responding to music and track isn't playing.
 Edit: same on Amazon music... Looks like this was a waste of money...

Known issue? Workaround?

**Comment by kblaschke** [comment]
Could you please give some additional details? At least which version of projectM (Steam, Windows Store, Apple Store, Play Store) did you download and on which platform (Windows/MacOS/Linux/Android/iOS)?

**Comment by vaderag** [comment]
> Could you please give some additional details? At least which version of projectM (Steam, Windows Store, Apple Store, Play Store) did you download and on which platform (Windows/MacOS/Linux/Android/iOS)?

I ended up giving up, but it was the Amazon app store version running on firestick

**Comment by JohnsonDylan** [comment]
This fixed my issue with no response playing from native spotify app:

- Enable ADB debugging in configuration
- Use a terminal to connect to your machine tipying:
adb connect YOUR_FIRE_TV_CUBE_IP:5555
- Enable access in your device
- Grant record audio permissions using:
adb shell pm grant com.psperl.projectMTV android.permission.RECORD_AUDIO
- Problem fixed!
- Stop ADB
adb kill-server

from reddit u/robsalasco

**Comment by vaderag** [comment]
> This fixed my issue with no response playing from native spotify app:
> 
> * Enable ADB debugging in configuration
> * Use a terminal to connect to your machine tipying:
>   adb connect YOUR_FIRE_TV_CUBE_IP:5555
> * Enable access in your device
> * Grant record audio permissions using:
>   adb shell pm grant com.psperl.projectMTV android.permission.RECORD_AUDIO
> * Problem fixed!
> * Stop ADB
>   adb kill-server
> 
> from reddit u/robsalasco

I actually tried that at the time and it didn't work for me back then sadly...

**Comment by kblaschke** [comment]
Closing this issue as this is related to the closed-source Android app released by @psperl - nothing we can do about bugs with the app from here.

Please contact Peter Sperl directly to get support.
