### ISSUE TITLE
Android TV:  Audio from TV? 

### ISSUE THREAD

**Issue by stuaxo** [projectM-visualizer/projectm#514]
A limitation of ProjectM on Android TV, is that it can't see audio from TV turner.
This means it's not possible to visualise any of the radio stations broadcast in this way (in the UK, BBC radio stations appear as channels on freeview (DVB-T).

This wasn't too much of an issue: you could listen over IPlayer, however this was removed.
Later on you could listen on TuneIn, but the stations seem to have been removed from there.
Currently I can cast from my phone, and run project-m, but it increases the level of faffing around quite a bit (and it's already a bit of a faff on AndroidTV to run the vis and play music, through no fault of ProjectM).

Info on getting audio from the TV turner
https://source.android.com/devices/audio/tv

Not sure how easy this is to do, or if there would be any side effects (like audio not actually playing), hopefully once loopback audio is setup it's not so different from the existing audio capture the ProjectM does.

**Comment by kblaschke** [comment]
The whole Android integration was done by @PeterMalkin about two years ago. Not sure if he's still around to help with that.

In its core, projectM is really only the visualizer part, providing audio data is up to each integration. the projectM Android app uses [`android.media.AudioRecord`](https://developer.android.com/reference/android/media/AudioRecord) to retrieve audio data. From what I read in the docs, it is limited to capture audio from device microphones, but not audio output of other apps. To do this, the app should probably use the [`android.media.projection.MediaProjection`](https://developer.android.com/reference/android/media/projection/MediaProjection) API.

If anyone with Android/Java programming experience can take this task, please feel free!

**Comment by stuaxo** [comment]
> The whole Android integration was done by @PeterMalkin about two years ago. Not sure if he's still around to help with that.

Yep, I actually mailed him originally with info that helped him get it working on AndroidTV, glad you mentioning the name helped me find those mails.

> 
The projectM Android app uses android.media.AudioRecord to retrieve audio data. From what I read in the docs, it is limited to capture audio from device microphones, but not audio output of other apps. 

I'm not sure that's quite right (at least for my TV ) - I have no built in microphone, and ProjectM picks up audio from other Android apps, but *not* the tuner.

The TV Tuner hardware itself is a probably a bit "special", by default with audio not routed in the same way.

The example on this page still to uses `android.media.AudioRecord` - with extra audio routing via the loopback so it can be captured -

https://source.android.com/devices/audio/tv

I used to do Android dev about 10 years ago, and would love to have a go at this, but free time is not looking good for the next few years.

Edit:  I wrote all that, but since updating my TV it won't let me have the radio playing in the background while the home screen launches, which is a pain .. so I'll have to see if that's solveable first.

**Comment by kblaschke** [comment]
Also worth of note here is that there's an Android TV app in Play Store, published by Peter Sperl. This app is closed-source and only uses libprojectM for rendering the visuals, but audio recording and anything else is totally outside the scope of this repo/project.

So if that's the app you're using, please try contacting the @psperl directly on that matter.

**Comment by stuaxo** [comment]
Cheers, I'll close this - I find the google play app a little unusable at time, so didn't realise which version I was using.
