### ISSUE TITLE
Please add Qt6 support

### ISSUE THREAD

**Issue by DAP-DarkneSS** [projectM-visualizer/projectm#517]
Qt 6.2

[   36s] + ./configure --host=i586-suse-linux-gnu --build=i586-suse-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --disable-dependency-tracking --disable-sdl --enable-qt --disable-static --disable-rpath
[   36s] uname.bin: invalid option -- 'X'
[   36s] Try 'uname.bin --help' for more information.
[   36s] /usr/bin/arch: invalid option -- 'k'
[   36s] Try '/usr/bin/arch --help' for more information.
[   36s] ./configure: line 2353: /usr/convex/getsysinfo: No such file or directory
[   36s] ./configure: line 2353: /usr/bin/hostinfo: No such file or directory
[   36s] ./configure: line 2353: /bin/machine: No such file or directory
[   36s] ./configure: line 2353: /usr/bin/oslevel: No such file or directory
[   36s] ./configure: line 2353: /bin/universe: No such file or directory
[   36s] checking for a BSD-compatible install... /usr/bin/install -c
[   36s] checking whether build environment is sane... yes
[   36s] checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
[   36s] checking for gawk... gawk
[   36s] checking whether make sets $(MAKE)... yes
[   36s] checking whether make supports nested variables... yes
[   36s] ./configure: line 3196: cygpath: command not found
[   36s] checking how to create a pax tar archive... gnutar
[   36s] checking whether to enable debugging... no
[   36s] checking whether make supports the include directive... yes (GNU style)
[   36s] checking for i586-suse-linux-gnu-gcc... no
[   36s] checking for gcc... gcc
[   36s] checking whether the C compiler works... yes
[   36s] checking for C compiler default output file name... a.out
[   36s] checking for suffix of executables... 
[   37s] checking whether we are cross compiling... no
[   37s] checking for suffix of object files... o
[   37s] checking whether we are using the GNU C compiler... yes
[   37s] checking whether gcc accepts -g... yes
[   37s] checking for gcc option to accept ISO C89... none needed
[   37s] checking whether gcc understands -c and -o together... yes
[   37s] checking dependency style of gcc... none
[   37s] checking for i586-suse-linux-gnu-ar... no
[   37s] checking for i586-suse-linux-gnu-lib... no
[   37s] checking for i586-suse-linux-gnu-link... no
[   37s] checking for ar... ar
[   37s] checking the archiver (ar) interface... ar
[   37s] checking build system type... i586-suse-linux-gnu
[   37s] checking host system type... i586-suse-linux-gnu
[   37s] checking how to print strings... ./configure: line 4824: print: command not found
[   37s] printf
[   37s] checking for a sed that does not truncate output... /usr/bin/sed
[   37s] checking for grep that handles long lines and -e... /usr/bin/grep
[   37s] checking for egrep... /usr/bin/grep -E
[   37s] checking for fgrep... /usr/bin/grep -F
[   37s] checking for ld used by gcc... /usr/i586-suse-linux/bin/ld
[   37s] checking if the linker (/usr/i586-suse-linux/bin/ld) is GNU ld... yes
[   37s] checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
[   37s] checking the name lister (/usr/bin/nm -B) interface... BSD nm
[   37s] checking whether ln -s works... yes
[   37s] checking the maximum length of command line arguments... 1572864
[   37s] checking how to convert i586-suse-linux-gnu file names to i586-suse-linux-gnu format... func_convert_file_noop
[   37s] checking how to convert i586-suse-linux-gnu file names to toolchain format... func_convert_file_noop
[   37s] checking for /usr/i586-suse-linux/bin/ld option to reload object files... -r
[   37s] checking for i586-suse-linux-gnu-objdump... no
[   37s] checking for objdump... objdump
[   37s] checking how to recognize dependent libraries... pass_all
[   37s] checking for i586-suse-linux-gnu-dlltool... no
[   37s] checking for dlltool... no
[   37s] checking how to associate runtime and link libraries... printf %s\n
[   37s] checking for i586-suse-linux-gnu-ar... ar
[   37s] checking for archiver @FILE support... @
[   37s] checking for i586-suse-linux-gnu-strip... no
[   37s] checking for strip... strip
[   37s] checking for i586-suse-linux-gnu-ranlib... no
[   37s] checking for ranlib... ranlib
[   37s] checking command to parse /usr/bin/nm -B output from gcc object... ok
[   37s] checking for sysroot... no
[   37s] checking for a working dd... 1+0 records in
[   37s] 1+0 records out
[   37s] 32 bytes copied, 7.284e-05 s, 439 kB/s
[   37s] /usr/bin/dd
[   37s] checking how to truncate binary pipes... 1+0 records in
[   37s] 1+0 records out
[   37s] 32 bytes copied, 3.404e-05 s, 940 kB/s
[   37s] /usr/bin/dd bs=4096 count=1
[   37s] checking for i586-suse-linux-gnu-mt... no
[   37s] checking for mt... no
[   37s] checking if : is a manifest tool... no
[   37s] checking how to run the C preprocessor... gcc -E
[   37s] checking for ANSI C header files... yes
[   37s] checking for sys/types.h... yes
[   37s] checking for sys/stat.h... yes
[   37s] checking for stdlib.h... yes
[   37s] checking for string.h... yes
[   37s] checking for memory.h... yes
[   37s] checking for strings.h... yes
[   38s] checking for inttypes.h... yes
[   38s] checking for stdint.h... yes
[   38s] checking for unistd.h... yes
[   38s] checking for dlfcn.h... yes
[   38s] checking for objdir... .libs
[   38s] checking if gcc supports -fno-rtti -fno-exceptions... no
[   38s] checking for gcc option to produce PIC... -fPIC -DPIC
[   38s] checking if gcc PIC flag -fPIC -DPIC works... yes
[   38s] checking if gcc static flag -static works... no
[   38s] checking if gcc supports -c -o file.o... yes
[   38s] checking if gcc supports -c -o file.o... (cached) yes
[   38s] checking whether the gcc linker (/usr/i586-suse-linux/bin/ld) supports shared libraries... yes
[   38s] checking whether -lc should be explicitly linked in... no
[   38s] checking dynamic linker characteristics... cat: '/etc/ld.so.conf.d/*.conf': No such file or directory
[   38s] GNU/Linux ld.so
[   38s] checking how to hardcode library paths into programs... immediate
[   38s] checking whether stripping libraries is possible... yes
[   38s] checking if libtool supports shared libraries... yes
[   38s] checking whether to build shared libraries... yes
[   38s] checking whether to build static libraries... no
[   38s] checking whether to use rpath... no
[   38s] checking for i586-suse-linux-gnu-g++... no
[   38s] checking for i586-suse-linux-gnu-c++... no
[   38s] checking for i586-suse-linux-gnu-gpp... no
[   38s] checking for i586-suse-linux-gnu-aCC... no
[   38s] checking for i586-suse-linux-gnu-CC... no
[   38s] checking for i586-suse-linux-gnu-cxx... no
[   38s] checking for i586-suse-linux-gnu-cc++... no
[   38s] checking for i586-suse-linux-gnu-cl.exe... no
[   38s] checking for i586-suse-linux-gnu-FCC... no
[   38s] checking for i586-suse-linux-gnu-KCC... no
[   38s] checking for i586-suse-linux-gnu-RCC... no
[   38s] checking for i586-suse-linux-gnu-xlC_r... no
[   38s] checking for i586-suse-linux-gnu-xlC... no
[   38s] checking for g++... g++
[   38s] checking whether we are using the GNU C++ compiler... yes
[   38s] checking whether g++ accepts -g... yes
[   38s] checking dependency style of g++... none
[   38s] checking how to run the C++ preprocessor... g++ -E
[   38s] checking for ld used by g++... /usr/i586-suse-linux/bin/ld
[   38s] checking if the linker (/usr/i586-suse-linux/bin/ld) is GNU ld... yes
[   38s] checking whether the g++ linker (/usr/i586-suse-linux/bin/ld) supports shared libraries... yes
[   39s] checking for g++ option to produce PIC... -fPIC -DPIC
[   39s] checking if g++ PIC flag -fPIC -DPIC works... yes
[   39s] checking if g++ static flag -static works... no
[   39s] checking if g++ supports -c -o file.o... yes
[   39s] checking if g++ supports -c -o file.o... (cached) yes
[   39s] checking whether the g++ linker (/usr/i586-suse-linux/bin/ld) supports shared libraries... yes
[   39s] checking dynamic linker characteristics... (cached) cat: '/etc/ld.so.conf.d/*.conf': No such file or directory
[   39s] GNU/Linux ld.so
[   39s] checking how to hardcode library paths into programs... immediate
[   39s] checking for i586-suse-linux-gnu-pkg-config... /usr/bin/i586-suse-linux-gnu-pkg-config
[   39s] checking pkg-config is at least version 0.9.0... yes
[   39s] checking for i586-suse-linux-gnu-pkg-config... (cached) /usr/bin/i586-suse-linux-gnu-pkg-config
[   39s] checking pkg-config is at least version 0.9.0... yes
[   39s] checking for GL... yes
[   39s] checking GL/gl.h usability... yes
[   39s] checking GL/gl.h presence... yes
[   39s] checking for GL/gl.h... yes
[   39s] checking for compiling a minimal OpenGL program... yes
[   39s] checking for linking a minimal OpenGL program... yes
[   39s] checking Freedom... GNU/LINUX detected
[   39s] checking for dlopen in -lc... yes
[   39s] checking for aligned_alloc... yes
[   39s] checking for posix_memalign... yes
[   40s] checking for fts.h... yes
[   40s] checking whether gcc is Clang... no
[   40s] checking whether pthreads work with -pthread... yes
[   40s] checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
[   40s] checking whether more special flags are required for pthreads... no
[   40s] checking for PTHREAD_PRIO_INHERIT... yes
[   40s] LIBS=-lGL   -ldl  -pthread
[   40s] checking for a sed that does not truncate output... (cached) /usr/bin/sed
[   40s] checking whether C++ compiler accepts -stdlib=libc++... no
[   40s] checking whether C++ compiler accepts -std=c++11... yes
[   40s] checking for X... ./configure: line 19101: xmkmf: command not found
[   40s] libraries , headers 
[   40s] checking for gethostbyname... yes
[   41s] checking for connect... yes
[   41s] checking for remove... yes
[   41s] checking for shmat... yes
[   41s] checking for IceConnectionNumber in -lICE... no
[   41s] checking for Qt... ./configure: line 19767: qmake: command not found
[   41s] no
[   41s] configure: error: "Qt5 not found"

**Comment by kblaschke** [comment]
The autotools-based `configure` script is deprecated and will be removed in the future. Additionally, since qmake has been removed in Qt6, this check wouldn't work anymore.

projectM will only use CMake in the future, same as Qt6. As long as the headers/API didn't change, replacing `Qt5` with `Qt6` in the existing projectM CMake files should work fine as a workaround. If there are changes required to the code, it'll be a bit more work to do here to support both versions, as Qt5 will be around for some while.

Besides that, Qt6 isn't shipped by any Linux distro AFAIK, so there's no big pressure on adding support right now, but we'll definitely implement it.

**Comment by kblaschke** [comment]
There were numerous changes required, mostly stuff left over from the initial Qt 4 upgrade to Qt 5, like the need to convert QGLWidget to QOpenGLWidget.

Using CMake, you should now be able to compile and run the projectM PulseAudio and JACK UIs with Qt 6. I tested it successfully with a self-compiled Qt 6.2 on Linux.

**Comment by DAP-DarkneSS** [comment]
Qt6 is available for several rpm-based distros: https://pkgs.org/search/?q=Qt6

**Comment by kblaschke** [comment]
The pull request has been merged, so you can try again using CMake to build projectM. Configure and build the project like this on Linux:
```sh
cd /path/to/projectM
mkdir cmake-build-debug
cmake -S . -B cmake-build-debug -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/path/to/install/projectM -DENABLE_PULSEAUDIO=ON -DQT_VERSION=6 -DCMAKE_PREFIX_PATH=/path/to/qt6
cmake --build cmake-build-debug
# Only if you want to install it right away:
cmake --install cmake-build-debug
```

If you have Qt 6 installed in your system's lib dir, including the dev files, you can omit the `CMAKE_PREFIX_PATH` option. Replace "debug"/"Debug" with "release"/"Release" to build an optimized version.

**Comment by DAP-DarkneSS** [comment]
Thanks! I'll check the master.

**Comment by DAP-DarkneSS** [comment]
[   46s] + /usr/bin/cmake /home/abuild/rpmbuild/BUILD/projectm-master/. '-GUnix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DCMAKE_INSTALL_LIBDIR:PATH=lib64 -DCMAKE_INSTALL_LIBEXECDIR=/usr/libexec -DCMAKE_BUILD_TYPE=RelWithDebInfo '-DCMAKE_C_FLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -DNDEBUG' '-DCMAKE_CXX_FLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -DNDEBUG' '-DCMAKE_Fortran_FLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -DNDEBUG' '-DCMAKE_EXE_LINKER_FLAGS=-flto=auto -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now' '-DCMAKE_MODULE_LINKER_FLAGS=-flto=auto -Wl,--as-needed' '-DCMAKE_SHARED_LINKER_FLAGS=-flto=auto -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now' -DLIB_SUFFIX=64 -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_STATIC_LIBS:BOOL=OFF -DCMAKE_COLOR_MAKEFILE:BOOL=OFF -DCMAKE_INSTALL_DO_STRIP:BOOL=OFF -DCMAKE_MODULES_INSTALL_DIR=/usr/lib64/cmake/projectM -DENABLE_GLES=OFF -DENABLE_SDL=OFF -DENABLE_PULSEAUDIO=ON **-DQT_VERSION=6**

**[   55s] CMake Warning:
[   55s]   Manually-specified variables were not used by the project:**
[   55s] 
[   55s]     BUILD_STATIC_LIBS
[   55s]     CMAKE_Fortran_FLAGS
[   55s]     CMAKE_INSTALL_DO_STRIP
[   55s]     CMAKE_INSTALL_LIBDIR
[   55s]     CMAKE_INSTALL_LIBEXECDIR
[   55s]     CMAKE_MODULES_INSTALL_DIR
[   55s]     INCLUDE_INSTALL_DIR
[   55s]     LIB_INSTALL_DIR
[   55s]     LIB_SUFFIX
**[   55s]     QT_VERSION**

**Comment by DAP-DarkneSS** [comment]
And also -DENABLE_PULSEAUDIO=ON changes nothing: it isn't built. Looks the same as #524 ...

**Comment by DAP-DarkneSS** [comment]
> the full CMake configuration output
The log for #524 : https://github.com/projectM-visualizer/projectm/files/6973047/_log.txt

**Comment by DAP-DarkneSS** [comment]
Thanks, is built fine with GLES3/gl3.h installed.

**Comment by kblaschke** [comment]
I'll close this ticket for now.

There are a few issues left like the mouse pointer hiding on strange occasions, but these also happen with Qt 5 and are related to using a QWindow in widget mode as rendering target. Will fix this later.

**Comment by DAP-DarkneSS** [comment]
Thank you very much!
