### ISSUE TITLE
Mouse pointer visible on full screen SDL frontend

### ISSUE THREAD

**Issue by donny838** [projectM-visualizer/projectm#519]
**Describe the bug**
When switching the projectM SDL frontend into fullscreen mode, the mouse pointer stays visible. There is no way to hide it.

**Desktop (please complete the following information):**
 - Application: Steam, SDL
 - OS: macOS, Linux and Windows
 - Version: latest master

**Comment by donny838** [comment]
There’s no way to hide mouse when in full screen on Mac. Quite frustrating and would love to see a way to hide mouse when full screen!

**Comment by kblaschke** [comment]
As the SDL frontend application (which is the one used on macOS and published on Steam) has no interactive UI that requires the mouse, we'll simply add a call to `SDL_ShowCursor(SDL_DISABLE);` in fullscreen mode and `SDL_ShowCursor(SDL_ENABLE);` when switching back to windowed mode. That should take care of the issue on all platforms.

**Comment by kblaschke** [comment]
Testing on macOS showed that it actually works fine, but there might be some confusion regarding the "fullscreen" mode, as there are two different ways to get there:
- Using the SDL-based fullscreen mode by pressing Command+f
- Using the macOS "borderless window" fullscreen mode by clicking on the green title bar icon

The latter one isn't a real fullscreen mode, it's just resizing the window to the screen size and removing the decorations. From SDL's point of view, there is no way to distinguish "maximized" and "native fullscreen" states. We could only check if the window is filling the whole screen by comparing the sizes, and if so, hide the mouse pointer.

Another way of solving it would be adding a hotkey to toggle the mouse pointer in any mode, regardless of fulscreen or windows display.

**Comment by revmischa** [comment]
Can't we hide the cursor when they hit cmd+f?

**Comment by kblaschke** [comment]
Hiding the cursor on toggling fullscreen via the hotkey was already in the code, it just won't trigger if the user clicks on the green, macOS-native fullscreen button in the title bar. Took me a while to guess that @donny838 probably means this. There's no flag or dedicated event to detect it, and even SDL can't unset this fullscreen mode using the toggle function.

So hiding the cursor if the window fills the current screen should be a good workaround. Even if the window still has borders or the user has multiple monitors, it will only be hidden when it's inside the window area, not affecting anything outside.

**Comment by kblaschke** [comment]
the fix is now in master. Please test, if the issue persists reopen the ticket.
