### ISSUE TITLE
Cmake -DENABLE_GLES=OFF -DENABLE_SDL=OFF do nothing

### ISSUE THREAD

**Issue by DAP-DarkneSS** [projectM-visualizer/projectm#524]
**Describe the bug**
Project still tries to find sdl2 & gles if they are disabled via cmake.

**Screenshots**

**Desktop (please complete the following information):**
 - Application: n/a
 - OS: openSUSE Tumbleweed
 - Version: master.

**Additional context**

**Comment by DAP-DarkneSS** [comment]
Today's Qt6 master - only sdl2:

[  100s] + /usr/bin/cmake /home/abuild/rpmbuild/BUILD/projectm-master/. '-GUnix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DCMAKE_INSTALL_LIBDIR:PATH=lib64 -DCMAKE_INSTALL_LIBEXECDIR=/usr/libexec -DCMAKE_BUILD_TYPE=RelWithDebInfo '-DCMAKE_C_FLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -DNDEBUG' '-DCMAKE_CXX_FLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -DNDEBUG' '-DCMAKE_Fortran_FLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -DNDEBUG' '-DCMAKE_EXE_LINKER_FLAGS=-flto=auto -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now' '-DCMAKE_MODULE_LINKER_FLAGS=-flto=auto -Wl,--as-needed' '-DCMAKE_SHARED_LINKER_FLAGS=-flto=auto -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now' -DLIB_SUFFIX=64 -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_STATIC_LIBS:BOOL=OFF -DCMAKE_COLOR_MAKEFILE:BOOL=OFF -DCMAKE_INSTALL_DO_STRIP:BOOL=OFF -DCMAKE_MODULES_INSTALL_DIR=/usr/lib64/cmake/projectM -DENABLE_GLES=OFF -DENABLE_SDL=OFF -DENABLE_PULSEAUDIO=ON -DQT_VERSION=6
[  101s] -- The C compiler identification is GNU 11.1.1
[  101s] -- The CXX compiler identification is GNU 11.1.1
[  101s] -- Detecting C compiler ABI info
[  101s] -- Detecting C compiler ABI info - done
[  101s] -- Check for working C compiler: /usr/bin/cc - skipped
[  101s] -- Detecting C compile features
[  101s] -- Detecting C compile features - done
[  101s] -- Detecting CXX compiler ABI info
[  101s] -- Detecting CXX compiler ABI info - done
[  101s] -- Check for working CXX compiler: /usr/bin/c++ - skipped
[  101s] -- Detecting CXX compile features
[  101s] -- Detecting CXX compile features - done
[  101s] -- Found GLM: /usr/include/glm/glm.hpp  
[  101s] CMake Error at CMakeLists.txt:74 (find_package):
[  101s]   By not providing "FindSDL2.cmake" in CMAKE_MODULE_PATH this project has
[  101s]   asked CMake to find a package configuration file provided by "SDL2", but
[  101s]   CMake did not find one.
[  101s] 
[  101s]   Could not find a package configuration file provided by "SDL2" with any of
[  101s]   the following names:
[  101s] 
[  101s]     SDL2Config.cmake
[  101s]     sdl2-config.cmake
[  101s] 
[  101s]   Add the installation prefix of "SDL2" to CMAKE_PREFIX_PATH or set
[  101s]   "SDL2_DIR" to a directory containing one of the above files.  If "SDL2"
[  101s]   provides a separate development package or SDK, be sure it has been
[  101s]   installed.
[  101s] 
[  101s] 
[  101s] -- Configuring incomplete, errors occurred!

**Comment by DAP-DarkneSS** [comment]
ENABLE_SDL=OFF :)

**Comment by DAP-DarkneSS** [comment]
[_log.txt](https://github.com/projectM-visualizer/projectm/files/6973047/_log.txt)
Log for x64.

**Comment by kblaschke** [comment]
Thanks for testing! The `cmake_dependent_option()` syntax is quite weird, so some of the checks there were not correct.

GLES support in CMake is still ToDo, as this library is highly platform-specific and even CMake doesn't provide a good find module for it (should be part of the OpenGL module, but there's only a short passage asking for help to implement this).

Currently GLES is basically only required for embedded platforms and the Emscripten build. I've added a proper failure message that it is currently unsupported.
