### ISSUE TITLE
Cmake' LIB_INSTALL_DIR and/or CMAKE_INSTALL_LIBDIR and/or LIB_SUFFIX

### ISSUE THREAD

**Issue by DAP-DarkneSS** [projectM-visualizer/projectm#527]
**Is your feature request related to a problem? Please describe.**
Unlike deb based distributions in 64 bit rpm, libraries are installed not in lib, but in lib64.

**Describe the solution you'd like**
Please implement cmake option(s) LIB_INSTALL_DIR and/or CMAKE_INSTALL_LIBDIR and/or LIB_SUFFIX

**Describe alternatives you've considered**
Dunno.

**Additional context**
n/a

**Comment by kblaschke** [comment]
Library suffixes and prefixes are already supported by CMake, there is no need to add those. Depending on the library type you're building, use either [`CMAKE_SHARED_LIBRARY_SUFFIX`](https://cmake.org/cmake/help/v3.21/variable/CMAKE_SHARED_LIBRARY_SUFFIX.html) or [`CMAKE_STATIC_LIBRARY_SUFFIX`](https://cmake.org/cmake/help/v3.21/variable/CMAKE_STATIC_LIBRARY_SUFFIX.html). If you actually mean the architecture suffix of the library dir (lib/lib64 and lib32 on some old distros), `CMAKE_INSTALL_LIBDIR` is the one you need to set.

Platform-specific installation dirs are currently not really implemented in the new CMake build system and high up on my to-do list. Currently, only a few variables taken from the original autotools script are implemented for testing:

https://github.com/projectM-visualizer/projectm/blob/a9be845e2dc901a56c6583cce8adf154f676405c/CMakeLists.txt#L36

Here's the plan:

- Linux: Will use CMake's [GNUInstallDirs](https://cmake.org/cmake/help/v3.21/module/GNUInstallDirs.html) module to add variables for the different directories, including `CMAKE_INSTALL_LIBDIR`. Files will be installed in the POSIX-specified directories under the install prefix.
- Windows: No special directories can be configured, but there will be different packaging options to create an installer for the SDL UI or a ZIP file which contains the development files. The install prefix is only used if the developer directly installs files on the development machine, either for immediate use or external packaging.
- macOS: Will use Apple's app bundle structure, e.g. putting binaries and libs into the `MacOS` dir and presets into `Resources`. Might also consider adding a development packaging option to create a framework bundle for use in development of other applications.
- Android: Probably similar to Linux.
