### ISSUE TITLE
projectM does not provide all documented textures for preset shaders.

### ISSUE THREAD

**Issue by kblaschke** [projectM-visualizer/projectm#532]
Currently, projectM supports a subset of the officially documented set of shader features Milkdrop provides for presets. This leads to huge rendering differences between the two implementations, generally breaking preset rendering using the missing features completely. Here's a (probably incomplete) list of issues:

- The predefined 2D/3D noise textures [aren't generated correctly](https://github.com/xlimit91/MilkDrop-MusicVisualizer/blob/c7c69844d76550a85a8bee7ec8a9e3b9f31b9ab6/milkdrop_225c_src/vis_milk2/plugin.cpp#L2419). projectM uses monochrome Perlin noise without an alpha channel, while Milkdrop generates pseudorandom RGBA noise, with all channels randomized.
- Texture loading kinda works, but has a _huge_ impact on load times and GPU memory if there are many image files in the preset directories as projectM load _all_ images as textures on startup instead of [analyzing the preset and loading only required textures](https://github.com/xlimit91/MilkDrop-MusicVisualizer/blob/c7c69844d76550a85a8bee7ec8a9e3b9f31b9ab6/milkdrop_225c_src/vis_milk2/plugin.cpp#L2929) for each preset (including freeing them after unloading it).
- [Random texture selection](https://github.com/xlimit91/MilkDrop-MusicVisualizer/blob/c7c69844d76550a85a8bee7ec8a9e3b9f31b9ab6/milkdrop_225c_src/vis_milk2/plugin.cpp#L3064) (`sampler_rand00`) is implemented, but might need tweaks.

Also the already implemented shader inputs should be reviewed against the Milkdrop code to make sure the inputs are set to expected values. Some presets are highly tuned to certain parameters and might look broken even if the values are just a tiny bit off.

The original preset authoring documentation can be found here:
http://www.geisswerks.com/milkdrop/milkdrop_preset_authoring.html

**Comment by BoAC-Tech** [comment]
[failed_shader_presets.zip](https://github.com/projectM-visualizer/projectm/files/7034482/failed_shader_presets.zip)

Got these errors with these presets:
1: the whole screenbuffer is black instead of only the texture and framebuffer I supply to draw to in OpenGL
    The projectM output has to be rendered to a specific texture but the whole screen becomes black.
2: shader error:
Failed to compile shader 'Fragment: Comp'. Error: 0:95(26): error: could not implicitly convert operands to arithmetic operator
0:95(15): error: operands to arithmetic operators must be numeric
0:95(9): error: cannot construct `vec2' from a non-numeric data type

Compilation error (step3) of Comp

**Comment by kblaschke** [comment]
These presets use some undocumented functionality I've never seen anywhere. There's a `per_frame_init` section, which has an additional function `loop` and uses variables like `reg00` and `megabuf`.

Do these presets actually work in Milkdrop? Neither the authoring guide nor the released source code gives any hints on that syntax. Any sources where this is defined would be helpful. Adding additional functions to the parser isn't a big thing, but we need to know how it's supposed to work and what the additional variables contain and where they are used.

**Comment by Se7enSlasher** [comment]
I think the random texture selection is almost implemented .![Screenshot_20210828_194702_com.psperl.projectM.jpg](https://user-images.githubusercontent.com/74858188/131224937-fd35c6df-2db3-4418-8c6c-76c2b4ad3804.jpg)
By the way, I am using an Android Version of projectM.

**Comment by Se7enSlasher** [comment]
One more... I have collected some presets from martin and some preset authors that is unsupported or crashed using projectM for Android and Windows.

Here is the download link: [Unsupported or Crashing Presets for projectM](https://www.mediafire.com/download/wmlirs18195h6ur)

**Comment by kblaschke** [comment]
Went a bit deeper into the code and most of the functionality is indeed there. I think the most problematic part with most presets is the lack of proper random noise. projectM uses Perlin noise and generated a greyscale noise image which has an opaque alpha channel and the RGB values set to an identical value for each pixel.

Milkdrop instead generates pseudo-random values instead, with different values for all four color channels. The "zoom factor" value then uses bicubic interpolation to zoom into a smaller area of the noise, creating a smoothened image.

Here are the four 2D noise textures as generated by Milkdrop. Order is `noise_lq`, `noise_lq_lite`, `noise_mq` and `noise_hq`. Note these are PNGs with alpha channel, so transparency will show up as the site's background color:

![noise_lq](https://user-images.githubusercontent.com/5038276/131589295-46766591-30e5-431e-b98f-3f3c5e93cc8c.png) ![noise_lq_lite](https://user-images.githubusercontent.com/5038276/131589293-a229552e-ef28-40bc-a17d-06143b03833e.png) ![noise_mq](https://user-images.githubusercontent.com/5038276/131589297-cb4b8988-d0e6-4786-8287-b3f224bb532e.png) ![noise_hq](https://user-images.githubusercontent.com/5038276/131589291-767f6c73-9fb8-4ff1-945b-bb55cd13a2de.png)

**Comment by kblaschke** [comment]
I'd like to round up this issue for now, as all "missing" textures are now there:
- Noise textures are generated properly, using Milkdrop's algorithm.
- There were issues with wrong wrap modes being set for noise & blur texture samplers, creating weird visual artifacts or completely breaking many shaders.
- All original Milkdrop textures plus those which could be found in other packs were added to the projectM-visualizer/presets-milkdrop-texture-pack repository. Sadly, the "worms" texture is nowhere to be found. If anyone know how it looked like and can provide a replacement, please open a PR!

From the opening post, lazy texture loading and better random texture selection are still open, but these affect mostly performance, and don't break presets completely. That said, I'm closing this ticket and continue work on the remaining problems in other issues.

**Comment by OfficialIncubo** [comment]
> Sadly, the "worms" texture is nowhere to be found. If anyone know how it looked like and can provide a replacement, please open a PR!

There is no worms texture. Nitorami accidentally sampled the worms as texture that cannot be found. Ex: "martin - glassball dance". This preset uses no texture.

**Comment by kblaschke** [comment]
It's being used (without obvious negative consequences when not found) in a large number of presets.

At some point, the texture might have been around, but I've tried many times and couldn't find it anywhere. If someone knows more about it or still has a copy, please feel free to add it to the [presets-milkdrop-texture-pack repository](https://github.com/projectM-visualizer/presets-milkdrop-texture-pack).
