### ISSUE TITLE
Only cycles through a dozen different visuals (Windows, Windows Store)

### ISSUE THREAD

**Issue by kariyna** [projectM-visualizer/projectm#541]
The version from the Windows store (EyeTune) only cycles through maybe half a dozen to a dozen different visualizations, there is almost no variety for some reason. I tried letting it run for an hour, going through them randomly, etc. The latest standalone build for Windows from all the way back in July 2020 is buggy and unusable in comparison. Are there any plans for a new Windows release?

**Comment by kblaschke** [comment]
The EyeTune app is unmaintained for some time now, and was released to the Windows Store by an external developer, so the projectM team currently has no means of updating it.

For the standalone build, which uses SDL to render, we'll be releasing new versions when the next major release (4.0) is due. It'll be based on a new cross-platform system, has a new, more portable API to integrate projectM and will also come with lots of bug fixes, optimizations and possibly some new features in the frontend. 

I'm currently working my way through the installation and packaging stuff, and _when done_, you could already go to the "Actions" tab here and then download an installable Windows artifact from an automated build. It's not guaranteed to be always totally stable or even working at all, but as always, feedback and testing is highly welcome!

**Comment by kblaschke** [comment]
It seems only the "presets_eyetune" folder is bundled with the app. Some presets might not work well (slow/not rendering at all) as EyeTune is limited to OpenGL ES, so this could be a subset that was tested to be working.

The app will probably be moved into a separate repository before the 4.0 release. If anyone want to maintain the app in the future, you're welcome!

Closing this issue for now.
