### ISSUE TITLE
Bundling presets as a ZIP/TAR.ZST archive

### ISSUE THREAD

**Issue by birdie-github** [projectM-visualizer/projectm#547]
It doesn't really help that `/usr/share/projectM/presets` contains over four thousand files - no only it makes installing and deleting the application slower than necessary it also leads to an increased file fragmentation and slower application startup.

It would be great if you bundled all these files as a single archive.

`/usr/share/projectM/presets` uncompressed: >4K files, 25MB disk space.

`presets.tar.zst` (ZSTD) - 1.5MB
`presets.zip` -  8.5MB

**Comment by kblaschke** [comment]
To access the presets, they must reside on the disk uncompressed. Installing them in a ZIP or TAR archive would mean projectM cannot access them. Reading files from archives would require more dependencies in projectM and possibly slow down application start even more as projecTM would need to scan for presets _and_ archives and also read the archive's file directories to look for presets, which is very slow for .tar archives as these need to be read from start to end. ZIP is a bit better as it has a structured directory at the end, but still takes time to read & parse.

All in all, it would not give the user much of an advantage.

Besides that, on modern filesystems 4K files do not make any real difference and fragmentation isn't a big issue anymore with ext4 and NTFS.
