### ISSUE TITLE
Foobar2000 crashes instantly when adding ProjectM

### ISSUE THREAD

**Issue by IgorArnaut** [projectM-visualizer/projectm#562]
Greetings. I've installed ProjectM component in Foobar2000. When I tried adding it on GUI, Foobar2000 instantly crashes.

![image](https://user-images.githubusercontent.com/57326929/143189056-5d95e916-cf64-44cd-8065-cbbd39c9d183.png)

App: Foobar2000 v1.6.7
OS: Windows 10 Pro 64-bit
Version: 0.0.1 (ProjectM)

I've got the Steam version, but I'm not sure how to install it in Foobar2000. I have the latest versions of VC8.

**Comment by kblaschke** [comment]
Please try to contact the plug-in author (@djdron) directly on that issue.

There's nothing the projectM developers can fix as we did not create the actual plug-in. The Steam version is a completely different app that cannot simply be "installed" in Foobar2000.
