### ISSUE TITLE
cannot uninstall windows 10

### ISSUE THREAD

**Issue by sweetjones2015** [projectM-visualizer/projectm#570]
how do i uninstall on windows 10, cannot find how to even open the app unless i go thru the windows app store. i search my pc and cannot find projectM anywhere..... but it will run going thru the microsoft app store...

**Describe the bug**

**Screenshots**

**Desktop (please complete the following information):**
 - Application: [e.g. Steam, SDL, pulseaudio]
 - OS: [e.g. macOS, linux, windows]
 - Version [e.g. 3.1.12]

**Additional context**

**Comment by kblaschke** [comment]
If you've installed it via the Windows Store, I think it must be uninstalled from there as well. It might create an entry in the apps & functions page in system settings, but no guarantee.

As the windows Store version has numerous limitations, I suggest using the standalone EXE anyway. You can get it either [on Steam for free](https://store.steampowered.com/app/1358800/projectM_Music_Visualizer/) (if you've got an account), it run even without Steam in the background. Or you can try my development release here:

https://github.com/kblaschke/projectm/releases/tag/v3.1.13-9e8ab88-win64

Just unpack & run. Remember to look in the release notes on how to change the preset path so projectM can find them.

**Comment by AddisonSparks** [comment]
> how do i uninstall on windows 10, cannot find how to even open the app unless i go thru the windows app store. i search my pc and cannot find projectM anywhere..... but it will run going thru the microsoft app store...
> 
> **Describe the bug**
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * Application: [e.g. Steam, SDL, pulseaudio]
> * OS: [e.g. macOS, linux, windows]
> * Version [e.g. 3.1.12]
> 
> **Additional context** Add any other context about the problem here.

The Microsoft Store version gets installed as "Eyeview" or something like that. When you open it from the Microsoft Store it shows the name at the top of the app window. You just have to search that in the start menu to uninstall it, it won't show up anywhere in the computer as "projectM". Just in case anyone else has this issue
