### ISSUE TITLE
Just wanting to instal ProjectM for Windows.

### ISSUE THREAD

**Issue by Glabgloddy** [projectM-visualizer/projectm#577]
Hi, I would simply like to instal ProjectM on my Windows 10 laptop. I found ProjectM on the Microsoft Store, clicked to "Get" and... nothing happens. Can you please tell me, how can I instal your lovely software? I have it on my phone and like it very much! Look forward to hearing from you- Happy New Year! Mark (Glabgloddy), Scotland.

**Comment by kblaschke** [comment]
Well, the store version is quite limited in many ways. Currently, your best option is possibly using Steam and installing the free projectM version from there. Also runs without Steam as it comes DRM-free.

You can also download a Win64 development release from my fork, which has received a lot of bugfixes since the last release. Just download the ZIP and unpack it. You'll need to adapt the config.inp, see the release notes.

https://github.com/kblaschke/projectm/releases/tag/v3.1.13-9e8ab88-win64

**Comment by Glabgloddy** [comment]
Hey Kai,Thanks very much for your reply- it clarifies things and I will certainly try out your Win64 development version.When I posted my question actially I was confused as the Windows Store had said the app was 531 Mb but without delay it gave me the option to open. When I clicked, up came a thing called Eye Tune which hadn't been mentioned till then- I assumed there was either some glitch, or I downloaded the wrong software, or this was some kind of previewer. Shortly after I discovered notes that referred to Geiss, Milkdrop, etc., So I realised actiallly I had the right app- but by then I had posted my question. The Store version IS a bit limited though, as you say, and I am looking forward to following your link.Thanks so much for using your expertise to develop this software. I think a good visualisation is quite entrancing and I have enjoyed Geiss for nearly 2 decades now, so it is great to be able to keep on using it!Best wishes, kind regards and- Happy New Year!Mark-------- Original message --------From: Kai Blaschke ***@***.***>Date: Sun, 2 Jan 2022, 14:30To: projectM-visualizer/projectm ***@***.***>Cc: Glabgloddy ***@***.***>, Author ***@***.***>Subject: Re: [projectM-visualizer/projectm] Just wanting to instal ProjectM for Windows. (Issue #577)
Well, the store version is quite limited in many ways. Currently, your best option is possibly using Steam and installing the free projectM version from there. Also runs without Steam as it comes DRM-free.
You can also download a Win64 development release from my fork, which has received a lot of bugfixes since the last release. Just download the ZIP and unpack it. You'll need to adapt the config.inp, see the release notes.
https://github.com/kblaschke/projectm/releases/tag/v3.1.13-9e8ab88-win64

**Comment by kblaschke** [comment]
Probably for the best. We don't have a Windows/UWP dev in the core team, so unless someone new joins us, we'll see if we can take down the broken store link and remove it from the link lists in the readme and Wiki as suggested. The only users which might use the store version are Xbox users I suppose. Anyone else is better off with the native desktop application, as this one is being actively maintained (yet not finished).
