### ISSUE TITLE
Qt implementation

### ISSUE THREAD

**Issue by RalfVB** [projectM-visualizer/projectm#58]
Hi,

I'm glad to have stumbled upon your project.
I'd like to implement ProjectM in mine (https://github.com/RalfVB/rde), which is Qt5-based.

I'm interested in the projectm-pulseaudio example, but the code for that is pretty old since the qprojectmwidget class derives from the deprecated QGLWidget class.

Is there a better example available somewhere?

**Comment by revmischa** [comment]
Hi, glad to hear! There may be more recent examples in some other project using projectM, but I don't personally know where. Qt5 support was recently added to projectM:
https://github.com/projectM-visualizer/projectm/pull/47
https://github.com/projectM-visualizer/projectm/pull/42

**Comment by revmischa** [comment]
Let me know if you need anything further. Qt5 should be in place now.
