### ISSUE TITLE
Feature Req Android TV: Screen Resolution Selection

### ISSUE THREAD

**Issue by ninjaeon** [projectM-visualizer/projectm#582]
Hi, I have a feature request for the paid Android TV version of projectm.  Screen Resolution selection within projectm.

I run my Mibox 4s at 4k, which makes projectm run like a snail and needs every setting turned all the way down.

When I set the system resolution to 720p, projectm runs a lot better and looks much better on higher settings. But I have to constantly switch the system resolution back and forth whenever I switch apps.

**Comment by kblaschke** [comment]
As the Android/Play Store app is not being developed or supported by the projectM open-source project, we sadly cannot provide help or take requests for new features.

Please contact the author of the app (Peter Sperl) directly via the means provided in the Play Store.
