### ISSUE TITLE
Feature Request Android: Add Setting for Secondary Preset Folder

### ISSUE THREAD

**Issue by NitsujiM** [projectM-visualizer/projectm#583]
After upgrading to Android 12, users cannot access the Android/data/ directory where the preset_dir folder is located in the current version of ProjectM. To restore the ability of users to use their own Milkdrop presets in ProjectM Pro, create a Settings option to specify a secondary folder for Milkdrop presets. Alternatively, you could restore use of the PrjM folder in the main storage, like prior versions of ProjectM had. Thanks!

**Comment by kblaschke** [comment]
As the Android/Play Store app is not being developed or supported by the projectM open-source project, we sadly cannot provide help or take requests for new features.

Please contact the author of the app (Peter Sperl) directly via the means provided in the Play Store.
