### ISSUE TITLE
Windows Front-End completely unavailable?

### ISSUE THREAD

**Issue by MBYlt** [projectM-visualizer/projectm#608]
There's three bullet points in the "Windows" section:

1. Standalone (links to projectM-visualizer/frontend-sdl2 - which has no available releases!) "Latest build" (links to a seemingly-dead appveyor entry, with no available Artifact, and all attempted builds for the past 7 months failing during the compile, according to the console).
2. Steam (...well, this is technically available, but requires running Steam, so that's a bit of an issue)
3. Windows Store (dead link / 404)

**Comment by kblaschke** [comment]
We're currently in the process of getting a new major release out, with lots of bugfixes, a whole new API for the library and a rewritten standalone app, which is the frontend-sdl2 repository. The new repo still hasn't got an automated build and all the packaging stuff is missing, as the core library is currently our focus, as it'll need to be released and finalized first.

I could create a hand-built pre-release based on the latest development code, but until I can get to it and also write a proper user manual, you may want to try this Windows release with the old frontend from my fork:

https://github.com/kblaschke/projectm/releases/tag/v3.1.13-9e8ab88-win64

Steam and Windows Store releases will probably be updated by their respective maintainers if the teams deems the codebase to be stable enough.

You can follow our Kanban project for the 4.0 release here, but remember this only is about the core projectM library:

https://github.com/projectM-visualizer/projectm/projects/2
