### ISSUE TITLE
App crashes when launching settings on iPad Pro with home button.

### ISSUE THREAD

**Issue by VonDeeper** [projectM-visualizer/projectm#618]
Most recent iPadOS  update still has error. I really really want this to work again. If I can provide any more info I will soon. The app crashes when I try to get into output, general settings. It worked on this device before but an apple update broke it a couple years ago. I like this app and want to be able to use it. Thanks.

**Comment by kblaschke** [comment]
I'm very sorry, but the projectM dev team cannot provide any support for the Android (Play Store) and iOS (Apple Store) apps, as they are closed source.

Please contact the app developer (Peter Sperl) directly, his mail address is peter@sperl.com.
