### ISSUE TITLE
flatpak app doesn't load audio sources

### ISSUE THREAD

**Issue by johnny-mac** [projectM-visualizer/projectm#63]
hey, IDK if you maintain your flatpak app of projectM or not but when I get it to launch on bootup its missing all the audio sources & doesn't react to sound... if I close & re-open it the sources will be there, but I need them working at boot & compiling projectM from source only gives me segmentation faults that I cannot solve.

**Comment by johnny-mac** [comment]
I'm having trouble trying to get projectM to start 60 seconds after boot-up, any tips are appreciated... I think its because projectM starts before the sound system but IDK.

**Comment by johnny-mac** [comment]
Alright, in ~/.config/lxsession/LXDE/autostart 
I have added nohup /etc/startUP (tiny script I made)
and in /etc/startUP I have

sleep 35

flatpak run net.sourceforge.projectM

**Comment by revmischa** [comment]
Feel free to send a pr or some documentation

**Comment by revmischa** [comment]
Let us know if you have any further issues
