### ISSUE TITLE
projectm_create_settings crashes on Windows in last 2 builds

### ISSUE THREAD

**Issue by kockie69** [projectM-visualizer/projectm#634]
**Describe the bug**
Only on windows the projectm_create_settings call causes a crash. I am also running same code on Linux where it is fine. All was fine before. It is related to the change from unsigned_int_8_8_8_8 to unsigned_int.  

**Screenshots**
No screenshots

**Desktop (please complete the following information):**
 - Application: [e.g. Steam, SDL, pulseaudio]
 - OS: Windows
 - Version : commit hash 595a9a6cbf53fd6a46cf062accc9c621a0c1af84

**Additional context**
I went from the previous commit and started adding the code changes line by line (started at the top). When I added line 97
glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, 256, 256, 0, NOISE_INTERNAL_DATA_FORMAT, GL_UNSIGNED_INT, noise->noise_lq);

When I added this line the crashes started.

I am building on Windows with msys64. All previous builds are fine.

**Comment by kblaschke** [comment]
Thanks for the report!

This will be fixed with #632, I'm still waiting for a reviewer to accept the changes.
