### ISSUE TITLE
Does not compile on R-Pi

### ISSUE THREAD

**Issue by howdood** [projectM-visualizer/projectm#635]
Hi - trying to build this on a Pi 3B+ running RaspiOS legacy. I've successfully built and run the latest release, but need a version with cmake included to build the qt frontend so am trying to build the latest projectM from the repo. 

Running cmake as per documentation gives the following error (repeated about five times for different targets):

CMake Error at src/libprojectM/libprojectM_shared.cmake:1 (add_library):
  Target "projectM_shared" links to target "OpenGL::OpenGL" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

Given that the 'release' version compiles correctly and projectMSDK runs, I think this is probably not a dependency issue (unless the dependencies have changes since last release version).

Help!
h

**Comment by howdood** [comment]
So - found a way round: on Pi cmake *must* be run as 

cmake -D "ENABLE_GLES=1" ..

Have put in a pull request to add that info to building.md

**Comment by kblaschke** [comment]
Yes, RPi can only use the embedded profile. I'll have a look at the PR, thanks!

**Comment by kblaschke** [comment]
There's issue #640 opened recently with a GLES incompatibility, which possibly affects RPi as well. This issue seems to be solved, so I'm closing it for now.

**Comment by matiasw** [comment]
Hi,
`cmake -D "ENABLE_GLES=1" ..` did not enable GL ES in my build. [This issue](https://github.com/projectM-visualizer/projectm/issues/524) suggested the actual switch might be `-DENABLE_GLES=ON`, but that did not enable GL ES, either.

How do I actually get projectM to compile on Raspbian? If enabling OpenGL ES is the way, how do I do that? I am using the 62cecb36d6c796771f84511347a5772b48162960 version, by the way.

**Comment by matiasw** [comment]
Ok, I found out that the actual switch to enable GL ES is `-DENABLE_GLES=ON`, after all. Don't know why it did not work first time I tried it. 

Now, I have another problem: with `cmake --build . -- -j`, the build starts, but then gets stuck at `[56%] Building CXX object src/libprojectM/MilkdropPresetFactory/CMakeFiles/MilkdropPresetFactory.dir/CustomShape.cpp.o`.

**Comment by matiasw** [comment]
Here is the log from the build. Cmake version is `3.16.3`. 
[cmake.log](https://github.com/projectM-visualizer/projectm/files/10396363/cmake.log)

**Comment by matiasw** [comment]
I got it to compile with
`cmake .. -D BUILD_SDL_TESTUI=OFF -D ENABLE_GLES=ON
make`

**Comment by kblaschke** [comment]
Great!

Also noting here that CMake 3.20 is now the minimum version supported for new builds. Didn't bump the version yet, but will do in one of the next PRs.
