### ISSUE TITLE
Add option to select preset from a list

### ISSUE THREAD

**Issue by Rexadev** [projectM-visualizer/projectm#638]
**Is your feature request related to a problem? Please describe.**
Next, previous and random are hard to use

**Describe the solution you'd like**
right click menu with a list

**Describe alternatives you've considered**

**Additional context**

**Comment by kblaschke** [comment]
You can press "return" or "m" to search for a preset, and also use the up/down/pgup/pgdown keys to browse the list.

The selection menu is bugged/crashing in some old releases, so please make sure to use the most recent one available.

Besides that, the rewritten SDL frontend will, at some point, have a better UI with more features.
