### ISSUE TITLE
GL_BGRA is not supported on OpenGL ES but used anyway

### ISSUE THREAD

**Issue by JohannesKauffmann** [projectM-visualizer/projectm#640]
$title, see TextureManager.cpp:69

This causes a compile failure:

```
projectm/src/libprojectM/Renderer/TextureManager.cpp:69:35: error: use of undeclared identifier 'GL_BGRA'
    GLint preferredInternalFormat{GL_BGRA};
                                  ^
```

Latest master, Ubuntu 22.04 headless. Using `-DENABLE_GLES=ON` on the CMake command line.

Not sure  what to do about this. Not an OpenGL expert.

**Comment by kblaschke** [comment]
GLES was always tricky to keep around. Heavily depends on the GLES library and headers which values are there. Will have to look into the specs again to see which texture format is the right one for GLES (I suppose `GL_RGBA`), as it doesn't support the format query extension.

**Comment by JohannesKauffmann** [comment]
Yes, GCC gives a more helpfull error message suggesting GL_RGBA:
```
projectm/src/libprojectM/Renderer/TextureManager.cpp:74:35: error: ‘GL_BGRA’ was not declared in this scope; did you mean ‘GL_RGBA’?
   74 |     GLint preferredInternalFormat{GL_BGRA};
      |                                   ^~~~~~~
      |                                   GL_RGBA
```

**Comment by JohannesKauffmann** [comment]
Builds fine since 62cecb36d6c796771f84511347a5772b48162960
