### ISSUE TITLE
API/CMake and general improvements

### ISSUE THREAD

**Issue by JohannesKauffmann** [projectM-visualizer/projectm#643]
Some points of improvements I noticed:
- When building with `-DENABLE_CXX_INTERFACE=ON`, it seems like `ProjectM.hpp` includes `PipelineContext.hpp`, but does not install that header file, resulting in compilation failure.
- Related to this, `ProjectM.hpp` [includes `PipelineContext.hpp` directly](https://github.com/projectM-visualizer/projectm/blob/master/src/libprojectM/ProjectM.hpp#L25) without a relative path to the `Renderer` folder in which it resides. Assuming `PipelineContext.hpp` gets installed to `$CMAKE_INSTALL_PREFIX/include/libprojectM/Renderer`, either the `#include` statement should reflect it's location, or the extra include directory should be exposed in the public CMake/pkgconfig interface.
- `ProjectM.hpp` relies on a `USE_THREADS` define. This is fine when building ProjectM itself, but for libraries, this flag does not get propagated. _Side note: it maybe better to rename this to `PROJECTM_USE_THREADS` to prevent possible name clashes._
- Installing the static library installs `libprojectM.a` to the lib folder, but `-l:projectM.a` is added to the pkgconfig file (and thus linking fails). For shared builds, no pkgconfig file is written.
- Related: the debug prefix (`d` by default) is not propagated to the pkgconfig file.
- The OpenGL library usage requirements are not propagated to the pkgconfig file, leading to linker failures. The same goes for `omp_get_num_threads` and friends, whereever that comes from.
- Last but not least, does ProjectM provide a version define, to faciliate projects conditionally using either an older or newer version? Something like `PROJECTM_MAJOR`, `PROJECTM_MINOR` possibly.

**Comment by kblaschke** [comment]
Most API changes are finished, so I can now get into polishing all those small things. Some parts of this issue are already done, others like pkgconfig and the library version are still to do.

**Comment by kblaschke** [comment]
Everything's implemented now in master. See `version.h` and the new `projectm_get_version*()` functions in `core.h` to retrieve version numbers in code for build and runtime versions of libprojectM.
