### ISSUE TITLE
Hi, will this plugin recompile to support foobar2000 64-bit architecture?

### ISSUE THREAD

**Issue by TurnOffNOD** [projectM-visualizer/projectm#655]
**Is your feature request related to a problem? Please describe.**
The existing release is for 32-bit architecture, and it is not compatible with foobar2000 2.0 beta 64bit
.
**Describe the solution you'd like**
According to foobar2000 v2.0 release notes (https://wiki.hydrogenaud.io-/index.php?title=Foobar2000:Version_2.0_Release_Notes), the plugin should be recompiled to compatible with 64bit.

**Describe alternatives you've considered**
64-bit architecture is the future.

**Comment by kblaschke** [comment]
@djdron is the one who provides the plug-in. He's currently waiting for the next projectM release, but maybe he could just recompile the existing plug-in for 64 bit. From projectM's side, there's no issue.

**Comment by djdron** [comment]
@TurnOffNOD , I've recompiled [version 0.0.5 with latest SDK & 64 bit support](https://www.foobar2000.org/components/view/foo_vis_projectM).

**Comment by TurnOffNOD** [comment]
> @TurnOffNOD , I've recompiled [version 0.0.5 with latest SDK & 64 bit support](https://www.foobar2000.org/components/view/foo_vis_projectM).


Oh, many thanks to your efforts.

**Comment by kblaschke** [comment]
As this seems to be resolved, I'm closing the issue.
