### ISSUE TITLE
Debug image is written on each start of projectM

### ISSUE THREAD

**Issue by kblaschke** [projectM-visualizer/projectm#656]
**Describe the bug**
In most cases when projectM is started (or the library is reinitialized), a debug main texture image is written to the current user's home directory.

**Platforms affected**
All.

**Additional context**
Reason is an [uninizialized member in the Renderer class](https://github.com/projectM-visualizer/projectm/blob/ad2203f7bbd36690f93dcc7b562fd1c04668fc22/src/libprojectM/Renderer/Renderer.hpp#L105). It should be default-initialized to `false`.

**Comment by OfficialIncubo** [comment]
Silly me, it can't show the project logo on Windows. It only shows the M with Headphones only.

**Comment by OfficialIncubo** [comment]
Silly me, it can't show the project logo on Windows. It only shows the M with Headphones only.

**Comment by kblaschke** [comment]
> Silly me, it can't show the project logo on Windows. It only shows the M with Headphones only.

You mean the "idle" preset? Yes, that's correct. The "project" text was removed a good while ago from the preset, probably was too noisy, dunno. The texture is still there though.
