### ISSUE TITLE
Some of the visualizations seem to play too fast. Is this normal?

### ISSUE THREAD

**Issue by 0x199x** [projectM-visualizer/projectm#662]
**Describe the bug**
I'm not sure if this is a bug or if it is just how the visualizations were made.  Some of the effects seem to play much too fast, to the point where it's distracting and unpleasant to watch.  I thought maybe it could have something to do with my 144hz display, but I tried switching to 60hz and it had no affect. If it is normal behavior and just how they were made, then I guess just disregard and close this request.  Although, I do have an idea to discuss below

**Screenshots**
The following examples are from milkdrop.  The songs playing here are slow and relaxing downtempo, but the visualizations are running in super speed

https://user-images.githubusercontent.com/89231731/201528721-eaec3369-3d10-4f7d-b1dd-d5181073971d.mp4

https://user-images.githubusercontent.com/89231731/201528792-9358ee32-8edf-4309-bb53-f1514094b066.mp4

**Desktop (please complete the following information):**
 - Application: VLC
 - OS: Linux
 - Version 3.1.12

**Additional context**
If this is working as intended, then I have an idea to throw out there.  I'm not sure how doable this is, but if it were possible, it would be nice if the effects started out slow, and then as the audio plays, analyze the peak patterns and try to detect BPM, gradually increasing the speed of the visualization to better match the music.

**Comment by kblaschke** [comment]
VLC ships with a very old projectM version, which might have some bugs and rendering issues that make the visuals look jaggy. Also, from the video, it seems the waveform data is only updated every 200ms or so, not every frame, which will make beat detection unreliable.

Also note that the "speed" visualy are rendered has nothing really to do with the song's tempo. Presets can use the beat detection values to apply some effects such as changing movement directions, colors etc., but the general zoom/rotation speeds are hardcoded in the preset.

To actually do a proper comparison, could you please find and name some preset files that expose the described behaviour, so I can run them side by side in WinAmp/Milkdrop and our own projectM UI with the current codebase? Then I can probably anwser your issue more reliably, e.g. if that's old issues we've already fixed, an integration issue in VLC or some real issue that needs fixing.

**Comment by 0x199x** [comment]
Sure I'd be happy to.  Do you have any tips how I can determine which preset is playing?  I tried launching vlc with `--verbose 2` but it doesn't spit anything out when a new preset is loaded. That's VLC's problem of course, not yours.. just wondering if you might have a suggestion.

Thank you very much for the quick and detailed response. I've noticed in other issues that you really step up to the plate and try to help when a user reports an issue.

**Comment by 0x199x** [comment]
OK, the first one I tested dang near gave me a seizure, and it's running in super speed

`milkdrop/Aderrasi - Agitator.milk`


https://user-images.githubusercontent.com/89231731/201531616-8e7840bf-a0bd-42ee-b49f-7648c0867346.mp4

**Comment by 0x199x** [comment]
Here is another

`milkdrop/Aderrasi - Crystal Storm.milk`


https://user-images.githubusercontent.com/89231731/201532041-18083c1e-ff94-4e02-ac5f-2425ca860f13.mp4

**Comment by kblaschke** [comment]
Loaded both presets in the current projectM dev version, here's how it looks with a rather slow music track:

https://www.youtube.com/watch?v=-QBAee9rylw

So I'd say the version VLC includes (probably an old 3.x release) has a lot of rendering issues which were fixed in the meantime.

**Comment by 0x199x** [comment]
Thanks a lot. So it seems like the speed issue I reported initially is just how the presets were designed, because yours are running at hyper speed too.  I haven't used visualizations in many years and I seem to remember them being a lot more mellow and mesmerizing

Wild thought....

Do you think it might be possible that when these visualizations were first developed for Winamp, when hardware was much slower, that their playback speed was being capped by hardware.. and now that we have faster hardware, they run faster?  I know this was a thing back in the day for some games ... the developers figured that the fastest hardware available was, say, 100mhz, and when faster computers came along and emulation tools like Dosbox appeared, the games would run at super speed and had to be artificially limited to compensate.  

Classic Windows Solitaire used to have the same issue with the "winning" animation being capped by hardware.  My family used to use solitaire to test the speed of new computers :)  On a 133mhz machine, the animation looked like this:

![giphy-1028121665](https://user-images.githubusercontent.com/89231731/201535012-a6202e3d-6722-4d8d-9a33-248a3e7fff75.gif)

But by the time 800mhz machines came around, the animation looked like this:

![ezgif-2-59fa42b73b](https://user-images.githubusercontent.com/89231731/201535235-c9487bb8-fdbb-4c54-9985-a006d009cf67.gif)


This probably isn't the case, but I just remember these being a heck of a lot more mellow back then. Suddenly I am trying them for the first time in 20 years and they look **_so_** much faster.


I'd be really interested to see what milkdrop looked like on a machine from the same era when it came out
