### ISSUE TITLE
Discord link(s) provided are invalid

### ISSUE THREAD

**Issue by jimallman** [projectM-visualizer/projectm#666]
**Describe the bug**
Discord link(s) provided in the projectm README are invalid. Clicking on these gives an error page on Discord.

**Screenshots**

<img width="662" alt="Screen Shot 2022-11-20 at 9 57 07 AM" src="https://user-images.githubusercontent.com/446375/202909322-dcdb357e-79bc-4515-8216-b626eb6c4706.png">

**Desktop (please complete the following information):**
 - Application: Google Chrome.app (web browser)
 - OS: macOS
 - Version 107.0.5304.110 (Official Build) (arm64)

**Additional context**
The link provided is <https://discord.gg/gaHtkQ3v>. It appears twice in the README, possibly elsewhere..?

**Comment by kblaschke** [comment]
Thanks for the heads-up, the recently updated link seems to have expired already. Created a new one that shouldn't become invalid anytime soon.
