### ISSUE TITLE
{AUDIENCE REQUEST FOR LIVE VISUAL TESTING} alpha

### ISSUE THREAD

**Issue by shibcmemes** [projectM-visualizer/projectm#685]
# OPEN REQUEST FOR AUDIENCE AND OPEN FEEDBACK

Basic af link: https://www.youtube.com/watch?v=N67_cnXsMU4

Some basic Git commands are: Our Radio via simple YT @ stream = Copy Embed Code.
```
<iframe width="640" height="360" src="https://www.youtube.com/embed/UNIQUEidHERE" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
```

Some basic Git commands are: Our own autip play iFrame for autoplay (first for 2023, as it sucks to do).
```
<div class="video">
<iframe width="640" height="360" src="https://www.youtube.com/embed/UNIQUEidHERE" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></iframe>
</div>
```

## Lead by a .radio (Geneva, Switzerland confirmed + open confirmed) DJ = here to help you, while I do what I do in all spaces digital/web3.

I hope to see you around.
-signing in, dj danoz darekt.

**Comment by kblaschke** [comment]
This is an issue tracker, not an advertisement board.

But you're welcome to post/advertise/discuss your stream links [on our Discord server](https://discord.gg/mMrxAqaa3W).

**Comment by shibcmemes** [comment]
Fair enough - catch ya any time. You might want to make some warez, but why force people to join Discord when you can just join mine, Twitch, YouTube - etc.

If you want to call it an advertisement, that someone offers you an open round up .radio platform spread to celebrate your potential, share whatever, you need to, wherever, you need to.

Peace.

- kng.radio host @ dj danoz darekt

**Comment by shibcmemes** [comment]
![image](https://user-images.githubusercontent.com/70056410/212940059-64c634e6-599c-465a-84bf-efd7f0e9e8ba.png)
![image](https://user-images.githubusercontent.com/70056410/212940120-01dfc003-7f8b-48cd-84fa-46875ff45e1e.png)

projectM crashes more than a nightly sleep over for My Little Crybaby Festival. - good luck with whatever you want to do. I cannot even run this, without crashing my video layer. lol.

Want a log? It's on a stream somewhere scrolling by. I wouldn't want to promote my use case.

I can run on an audio layer. I've done this for longer than most of you have even known of MilkDrop and thought it needed replacing, lol. I want to help you prove out your desire and demand.

But you're right - this is just a promo board. FOSS is ded because attention seekers can't give it up when someone wants to actually use the tools. This happens a lot, especially with visualisers.

Nerds that can't create and like to "visualise" their hopes and memes.

**Comment by revmischa** [comment]
Pull requests are welcome!

**Comment by shibcmemes** [comment]
No doubt! Best of luck with that.

BSD > GNU, anyway.

You're practically just advertising for Stallman with that one.

**Comment by revmischa** [comment]
![rms_comrade](https://user-images.githubusercontent.com/245131/213024636-8ff8f4ef-a5a0-4e81-8ffe-5ef7a30c8ae9.png)

**Comment by shibcmemes** [comment]
![image](https://user-images.githubusercontent.com/70056410/213036338-9ef5a8b7-ba95-4f92-81cd-52aa365fffc9.png)

Nice.
