### ISSUE TITLE
downloads for recent stable windows

### ISSUE THREAD

**Issue by vujnovich** [projectM-visualizer/projectm#688]
on the main github page, the links for the windows download are broken or unable to be located.  i havnt checked the out of date windows store download, or the steam download.   is there an active link thats already built and executable for windows 10?

**Comment by kblaschke** [comment]
No official releases yet for the new SDL standalone application, but you can check my development releases in my fork here, for all major desktop platforms:

https://github.com/kblaschke/projectm/releases

The Steam version was recently updated to the new app, with a slightly newer build, but in general, they should both be more or less the same.

I also post new versions on the itch.io page, on which you can also download everything for free:

https://codav.itch.io/projectm

Windows Store is still a very old version, it may be updated at some point when we find someone with experience in writing/updating apps for the Universal Windows Platform.

We're nearing the final release, so all the links, release pages and the Wiki will be updated then.
