### ISSUE TITLE
the readme link to the latest windows standalone app has no downloads

### ISSUE THREAD

**Issue by philipag** [projectM-visualizer/projectm#709]
**Describe the bug**
This link opens but there are no downloads: https://ci.appveyor.com/project/revmischa/projectm/build/artifacts
The Windows store app is also 4 years old.
Is there a newer link to to the latest windows version available?

**Desktop (please complete the following information):**
 - Application: JRiver => WASAPI
 - OS: windows
 - Version NA

**Comment by kblaschke** [comment]
The Windows Store version doesn't build anymore, and unless someone with UWP dev experience steps up to help us out (team currently consists of Mac & Linux devs), there won't be an update on that front.

For the "normal" desktop application, there's also no new release as it's still in development, but our focus is currently on the core library and making it both easier to integrate and also more compatible with Milkdrop. When this work is done, there will also be a new official release of the standalone applications.

We should probably update the ReadMe and documentation accordingly to avoid this confusion - which, to be honest, happens to many people. I'll keep this ticket open and close it when the ReadMe was edited.

If you don't mind using a development version, you can try this dev release I built about half a year ago:

https://github.com/kblaschke/frontend-sdl2/releases/tag/2.0-windows-pre1

It's stable enough for everyday use, but doesn't contain any recent improvements. I'm currently rewriting a lot of internal code to fix some serious compatibility issues, and will create an updated dev build when that's done and stable enough for a broader audience to use.
