### ISSUE TITLE
Delayed beat detection

### ISSUE THREAD

**Issue by Souravgoswami** [projectM-visualizer/projectm#711]
**Describe the bug**
Whenever I run a music, the ProjectM visualization doesn't start at the exact same time.
When I start and pause a music, I see projectM updates after 5 seconds or so, and as the music is played and paused for 1 second, projectM does the same as well - but everything is delayed by like 5 seconds.

The issue is annoying because say you're playing music and it has beats, ProjectM will show each beat delayed by 5 seconds. Now when the beat stops, ProjectM will still show the beats in the visualization. So it's like a the detection has a horizontal offset of 5 seconds and not close to real time update. This becomes annoying because the visualization doesn't match closely to what is playing, because 5 seconds delay is a huge delay.

**Screenshots**
![image](https://user-images.githubusercontent.com/37468605/227661453-421230ad-e1f0-4f45-b48f-8faab43e1c3f.png)
Music running - shows black screen

Music paused but visualizer still runs:
![image](https://user-images.githubusercontent.com/37468605/227661500-6cad39a6-a920-4acf-a946-f44174a8fecb.png)

**Desktop (please complete the following information):**
 - Application: Pipewire
 - OS: Linux
 - Version: 3.1.12 (3.1.12-4 Arch linux), but past versions are affected, for many years.
- PipeWire Version:  1:0.3.67-1, same happened with pulseaudio when I started using this software few years back.

**Additional Details**
Adjusted various settings, no resolution. Can't find any setting for delayed FFT.

**Comment by xsoalokinx** [comment]
tested frontend-sdl2 and it worked fine, also experienced a delay like OP when using pipewire and its pulse backend. Fixed it by passing PULSE_LATENCY_MSEC=50.

**Comment by Souravgoswami** [comment]
Wow, I missed that comment :(

Yeah fronend-sdl2 works really great! Thank you so much!
