### ISSUE TITLE
Bundle glm with project

### ISSUE THREAD

**Issue by revmischa** [projectM-visualizer/projectm#73]
glm is just some header files. We should bundle them with the project to eliminate this dependency. Would make installing easier, especially on OSX where it's the only non-SDL2 dep.

**Comment by revmischa** [comment]
Now you need brew though. I didn't need brew to build the rest of it. Just seems like such a simple thing to bundle.

**Comment by deltaoscarmike** [comment]
It's normal for a project to evolve to the point it needs a new dependency for it's building. This is the counterpart of modern OpenGL. Most package manager provides this library so it"s trivial to fetch it along sdl2 as stated by the building documentation.

**Comment by revmischa** [comment]
Okay. Let's just make sure it's reflected in docs.
