### ISSUE TITLE
Nintendo Switch Support

### ISSUE THREAD

**Issue by OfficialIncubo** [projectM-visualizer/projectm#738]
Long time no asking for porting this open-source music visualization to the new device.
Nintendo Switch has ARM Cortex A57 processor and nVidia Tegra Video Card on it.
I think it supports OpenGL and Vulkan renderers according to [this](https://news.ycombinator.com/item?id=16478745). I wish projectM will be existed for Nintendo Switch.
Read more about the Nintendo Switch OS: https://en.m.wikipedia.org/wiki/Nintendo_Switch_system_software

Attaching the Discord Comment [here](https://discord.com/channels/737206408482914387/738468377168707634/969918759903051776).

P.S. I don't have Nintendo Switch, so if anyone has a console, you can reply here.

**Comment by kblaschke** [comment]
Even supports OpenGL 4.5, which is interesting, as most embedded devices only go with the ES API. Running on ARM isn't an issue at all, so besides getting the SDK and writing an implementation using it, I don't see any reason projectM shouldn't run on the Switch. I don't own one either, so anyone willing to do a port, please do so!

**Comment by proconsule** [comment]
projectM works on SWITCH without any changes on source code.

I get it up and running here
https://github.com/proconsule/NXMilk

**Comment by kblaschke** [comment]
Great to see! Will close this issue then.
Will also add it later to the [Applications list](https://github.com/projectM-visualizer/projectm/wiki/projectM-Applications) in the Wiki and probably also in the ReadMe.
