### ISSUE TITLE
White screen on Soft Cuts

### ISSUE THREAD

**Issue by fotofrank** [projectM-visualizer/projectm#743]
I've got a strange issue when using the Soft Cut for changing from one preset to the next.
With some presets it produces a completely white screen.
When in the .properties file projectM.transitionDuration is set to 1 second, I get a 1 second white screen. When set to 5 seconds, I get a 5 seconds white screen.

Is this some kind of bug OR might there be a setting in the .properties file that should be taking care of this?

**Comment by kblaschke** [comment]
Which version/branch of libprojectM do you use?

**Comment by OfficialIncubo** [comment]
As far as I know, he's using ver. 3.1.12. Did I guess it?

**Comment by kblaschke** [comment]
> As far as I know, he's using ver. 3.1.12. Did I guess it?

This old version did not use `.properties` files, it still had the old config.inp file. So this would be at least one of the dev pre-releases, or a custom-built executable.

**Comment by fotofrank** [comment]
projectMSDL-Windows-x64-2.0-pre1

**Comment by OfficialIncubo** [comment]
> projectMSDL-Windows-x64-2.0-pre1
> The Windows stand-alone version
> 

That's what I said too.
I knew that you use the pre1, but I forgot to comment 2 days ago.

**Comment by kblaschke** [comment]
This pre-release still has broken preset transitions. Should be fixed in current master with the new renderer and smooth transitions.

**Comment by kblaschke** [comment]
I'll just close this issue, as it's about an old version and with release 4.1, libprojectM will ship with proper transitions again.
