### ISSUE TITLE
Qt build fails on linux

### ISSUE THREAD

**Issue by luigino** [projectM-visualizer/projectm#76]
There's a linking problem with projectm-pulseaudio; it disappears if I set LDFLAGS="-lQt5OpenGL".
Not sure where's the cleanest spot to add it in the Makefile.am though.

See [log snippet](https://github.com/projectM-visualizer/projectm/files/2127349/projectM-3.0.0_Qt5OpenGL.txt).

**Comment by deltaoscarmike** [comment]
Qt5OpenGL is already in the linking flags. The issue must be the library order.
Could you try this [patch](https://gist.github.com/deltaoscarmike/b60d6bbed5b0d9e8717e7b479f3bb7cc)

**Comment by luigino** [comment]
Works for me.

**Comment by aots-aots** [comment]
I had to make this change to compile on Ubuntu 16.04 (gcc  v5.4, ldd 2.23), but not on Arch Linux (gcc v8.1.1, ldd v2.27).
