### ISSUE TITLE
Foobar2000 visualization plugin

### ISSUE THREAD

**Issue by Kappa971** [projectM-visualizer/projectm#802]
**Is your feature request related to a problem? Please describe.**

Hi, it would be great if projectM is released as a visualization plugin for Foobar2000.

There is already a plugin https://github.com/djdron/foo_vis_projectM, but it is based on an old version of projectM and it is a bit buggy/it works bad.

**Comment by kblaschke** [comment]
We can't do much here, but @djdron is on our Discord and the repo also has an issue tracker. I'll ping him, and close the issue here.

You can watch this one here, which I've just bumped: https://github.com/djdron/foo_vis_projectM/issues/5
