### ISSUE TITLE
I can't find the binary or executable called projectMSDL anywhere

### ISSUE THREAD

**Issue by GittyMejorado** [projectM-visualizer/projectm#808]
### Please confirm the following points:

- [X] This question is NOT about the Android apps in the Play Store
- [X] I have [searched the project page](https://github.com/search?q=org%3AprojectM-visualizer+type%3Aissue+&type=issues) to check if the question was already asked elsewhere

### Topic

General Request

### Your Request

I have compiled Github version 4.11 of ProjectM on Ubuntu 24.04, it seems to compile without errors, but the projectMSDL executable or binary is nowhere to be found.

**Comment by kblaschke** [comment]
Hi,

the main projectm repository now only contains the projectM development library. The SDL frontend has been rewritten and moved to its own repository:

https://github.com/projectM-visualizer/frontend-sdl2

This application uses the library from this repository. Please refer to the build instructions in the main directory. If you have questions, you can visit our discord server, there's always someone who can help you out building the app.
