### ISSUE TITLE
cannot get projectm to build on Fedora 40. can't locate OpenGL libraries[DEV BUG] 

### ISSUE THREAD

**Issue by loveless-codr** [projectM-visualizer/projectm#809]
### Please confirm the following points:

- [X] This report is NOT about the Android apps in the Play Store
- [X] I have [searched the project page](https://github.com/search?q=org%3AprojectM-visualizer+type%3Aissue+&type=issues) to check if the issue was already reported

### Affected Project

libprojectM (including the playlist library)

### Affected Version

03aa8a7

### Operating Systems and Architectures

Linux (x86_64)

### Build Tools

Compiler: GNU GCC, Build Tool: CMake, Dependency Manager: pkgconfig

### Additional Project, OS and Toolset Details

Fedora 40

### Type of Defect

Build failure (compiler/linker or toolset error)

### Log Output

```shell
-- Building for OpenGL Core Profile
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_glx_LIBRARY
  OPENGL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindOpenGL.cmake:545 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:153 (find_package)
```

### Describe the Issue

hangs at finding the OpenGL library. I attempted to create a symbolic link in the build directory for libGLX but that was also unsuccessful

**Comment by kblaschke** [comment]
It looks like the GL development packages aren't installed, which contain the headers and development libraries required to build projectM. Try installing these packages (as user root), Fedora seemingly split all the files into many packages:

`yum install mesa-libGL-devel mesa-libGLU-devel mesa-libGLw-devel mesa-libOSMesa-devel`

**Comment by loveless-codr** [comment]
my woes are no more, thank you.
