### ISSUE TITLE
Why did you delete my question?

### ISSUE THREAD

**Issue by GittyMejorado** [projectM-visualizer/projectm#810]
### Please confirm the following points:

- [X] This question is NOT about the Android apps in the Play Store
- [X] I have [searched the project page](https://github.com/search?q=org%3AprojectM-visualizer+type%3Aissue+&type=issues) to check if the question was already asked elsewhere

### Topic

General Request

### Your Request

Why did you delete my question?

Your damn program is as shitty and mediocre in the same way as Olaf Scholtz and your Nazi whore Annalena Baerbock is driving to your country.
Fucking European third world mediocre pretentious asshole.
Damn pretentious idiot, shove your fart software up your ass.

**Comment by revmischa** [comment]
Güten tag @GittyMejorado, welkommen to the issue tracker.
If you are dissatisfied with your level service here, you may be entitled to a full refund!

**Comment by GittyMejorado** [comment]
revmischa you are the trouble-seeking idiot, you delete a correctly asked question, but you keep this question and take the time and trouble to answer it hahahaha.
You love problems, you love the bad life, in the same way that your government makes with allyours like a puppet hahahahaha.
Oh, your country is an invaded country with Yankee military bases everywhere, surely you're not puppets, right?
You are not in full decline.
Being pretentious, narcissistic and believing yourself to be the best in the world just because you are a native of a certain country is retarded people.
I already said it and I stand by it, fuck your fucking software, fuck you, fuck any pretentious asshole equals you.
When your flesh gets sick you will need me or someone with my profession and I will send you to hell for being an asshole fart programmer asshole.

**Comment by kblaschke** [comment]
Closing due to abusive behavior against our and GitHub's community standards. User has been blocked from the projectM org.
