### ISSUE TITLE
GL_INVALID_ENUM error on transition to the first preset

### ISSUE THREAD

**Issue by hack-s** [projectM-visualizer/projectm#823]
### Please confirm the following points:

- [X] This report is NOT about the Android apps in the Play Store
- [X] I have [searched the project page](https://github.com/search?q=org%3AprojectM-visualizer+type%3Aissue+&type=issues) to check if the issue was already reported

### Affected Project

libprojectM (including the playlist library)

### Affected Version

master branch

### Operating Systems and Architectures

Linux (x86_64)

### Build Tools

Compiler: GNU GCC

### Additional Project, OS and Toolset Details

c++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

### Type of Defect

Specific bug in projectM code (please link the code in question)

### Describe the Issue

`GL_INVALID_ENUM` error present in OpenGL context via `glGetError()` on transition to the first/initial preset when the output texture from the current preset (initialized empty at that point) is attempted to being copied.

The error is caused by this line when `m_target = 0`:
https://github.com/projectM-visualizer/projectm/blob/master/src/libprojectM/Renderer/Texture.cpp#L58

The error does not cause any functional issue as far as I can tell, it just trips my error handler.

**Comment by hack-s** [comment]
Here is my workaround for this issue, not sure if that is the preferred way to fix it though.
https://github.com/projectM-visualizer/projectm/pull/824

**Comment by kblaschke** [comment]
This error is almost always happening because the OpenGL context isn't properly set up, as these OpenGL calls are the first ones being executed when initializjng projectM.

To make sure this doesn't happen because of such an issue, please check:
- You have set up an OpenGL context with a _minimum_ GL Core Profile version of 3.3, not a lower compatibility profile.
- You are using GLX, not EGL.
- The created context is active and properly initialized when you call `projectm_create()`.

**Comment by hack-s** [comment]
To be more precise, the issue is happening when transitioning from the idle preset `idle://Geiss & Sperl - Feedback (projectM idle HDR mix).milk` to the first actual file based preset.

I confirmed this issue is present (on my system) when using the latest `frontend-sdl2` from master, tested both, X11 and Wayland on Ubuntu 22.04. OpenGL context setup looks good to me. Detection of the bug is easy to reproduce by adding a minimal GL error handler like the following to the `RenderLoop.cpp` `Run()` method, e.g. L51:
```
    while (true)
    {
        auto error = glGetError();

        switch (error)
        {
            case GL_NO_ERROR:
                break;
            case GL_INVALID_ENUM:
                std::cerr << "OpenGL Error: GL_INVALID_ENUM - Enumeration parameter is not legal" << std::endl;
                exit(1);
            default:
                std::cerr << "OpenGL Error: Error code - 0x" << error << std::endl;
        }
    }
```

Note requires and additional include: `#include <GL/gl.h>`

**Comment by hack-s** [comment]
I have a hard time verifying that it is in fact using GLX on X11. It links the right libs, and the only EGL lib is for Wayland I believe. 
```
libOpenGL.so.0 => /lib/x86_64-linux-gnu/libOpenGL.so.0 (0x000079224c061000)
libwayland-egl.so.1 => /lib/x86_64-linux-gnu/libwayland-egl.so.1 (0x000079224b71b000)
libGLX.so.0 => /lib/x86_64-linux-gnu/libGLX.so.0 (0x000079224b59e000)
libGLdispatch.so.0 => /lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x000079224b4e6000)
```
Looking at `strace` is somewhat inconclusive, but it does look like it's is using GLX.

**Comment by kblaschke** [comment]
Thanks for the information! Found and fixed the issue adding proper emptiness checks to CopyTexture, as presets don't have an output texture allocated before rendering the first frame. This may happen to other copy operations in future additions, so having this in the CopyTexture class made more sense to me.

This will also fix issues seen with other integrations, which probably suffered from this bug as well.

We'll push out a 4.1.2 bugfix release for this one, as this is an important fix.
