### ISSUE TITLE
[OTHER] [LITERALLY USING THIS FOR MY WORLD RECORD ATTEMPT]

### ISSUE THREAD

**Issue by kryptoklob** [projectM-visualizer/projectm#843]
### Please confirm the following points:

- [X] This question is NOT about the Android apps in the Play Store
- [X] I have [searched the project page](https://github.com/search?q=org%3AprojectM-visualizer+type%3Aissue+&type=issues) to check if the question was already asked elsewhere

### Topic

Development and Contributing

### Your Request

Unsure of what category to pick here. Just wanted to note that this is currently live on my streams:

- x/twitter
- facebook
- youtube
- twitch

via restream.io for my "quickest to 1-million-followers" and "longest-uptime-stream" dual attempts.

...also, to raise money, I need help paying rent. Sigh.

Cheers, and here's to FOSS!

**Comment by kryptoklob** [comment]
> random mega.nz link

Nothanks.

**Comment by kryptoklob** [comment]
(I absolutely have the c compiler installed lol)

**Comment by kryptoklob** [comment]
> [kryptoklob](https://github.com/kryptoklob) added [question](https://github.com/projectM-visualizer/projectm/labels/question) [triage](https://github.com/projectM-visualizer/projectm/labels/triage) labels [1 hour ago](https://github.com/projectM-visualizer/projectm/issues/843#event-14321543937)

Wasn't me, perhaps check the bot config?

Will PR if/when I have time.

**Comment by kblaschke** [comment]
Please do not abuse the issue tracker to advertise.

You can either join our Discord or post a thread on the discussion board instead!

**Comment by kryptoklob** [comment]
This isn't advertising. 

I'm CREDITING you guys.
