### ISSUE TITLE
CONGRATS UR NOW CAMPAIGNING FOR KAMALA HARRIS 2024 NO TAKEBACKSIES MWHAHAHAHA see twitch.tv/kryptoklob lmfao

### ISSUE THREAD

**Issue by kryptoklob** [projectM-visualizer/projectm#847]
### Please confirm the following points:

- [X] This question is NOT about the Android apps in the Play Store
- [X] I have [searched the project page](https://github.com/search?q=org%3AprojectM-visualizer+type%3Aissue+&type=issues) to check if the question was already asked elsewhere

### Topic

General Request

### Your Request

CONGRATS UR NOW CAMPAIGNING FOR KAMALA HARRIS 2024 NO TAKEBACKSIES MWHAHAHAHA see twitch.tv/kryptoklob lmfao

**Comment by kryptoklob** [comment]
WHACHA GONNA DO

BAN ME FROM OPEN SOURCE SOFTWARE LOOOOOOOOOOOOOOOOOOOL

**Comment by kblaschke** [comment]
> WHACHA GONNA DO
> 
> BAN ME FROM OPEN SOURCE SOFTWARE LOOOOOOOOOOOOOOOOOOOL

Actually - yes.

At least from this project.
