### ISSUE TITLE
projectM_resetGL not resizing as expected

### ISSUE THREAD

**Issue by aots-aots** [projectM-visualizer/projectm#85]
Hi,

I've been learning how to use libprojectM, and thought this issue was due to my misunderstanding of the library, but noticed the exact same problem occurs for the SDL and Qt/pulseaudio versions compiled from the current git master.

It appears that something goes wrong during the resize of the GL viewport or similar (the call to projectM_resetGL does not seem to resize as expected). It seems the correct window size is being passed to libprojectM, stored in the settings struct and passed on to the Renderer, but from there I can't see what is going wrong.

This can easily be seen by running the SDL or Qt version, and then resizing the window. If shrinking the window, the rendering gets cropped, like only part of the image is copied onto the window surface. If enlarging the window, the resolution does not increase, and instead the original size image is stretched/scaled to fill the window (if the code is modified to start with a small window size, this effect is more noticeable). A screenshot is attached, showing artefacts from the partial rendering only into the upper-left corner after shrinking of the window.

I've reproduced this on both Ubuntu 16.04 and Arch Linux (both x86_64).

![screenshot from 2018-07-03 11-05-20](https://user-images.githubusercontent.com/25150348/42194277-4bd857c8-7eb2-11e8-8cea-143f607502d9.png)

**Comment by revmischa** [comment]
Thanks for the info! 
Any ideas for solutions?

**Comment by deltaoscarmike** [comment]
The RenderTarget is not updated with the new display size.
Try this [patch](https://gist.github.com/deltaoscarmike/08118b1c42b737528a725d3b2c0166e6)

**Comment by aots-aots** [comment]
Initial test looks good! I've only done a quick check, but will do some further testing and let you know if there's still an issue.
Cheers!

**Comment by deltaoscarmike** [comment]
Travis build error is not due to this commit: 
> apt-get install failed

Issue is fixed, closing it
