### ISSUE TITLE
Upgrade libreelec projectm version

### ISSUE THREAD

**Issue by jobevers** [projectM-visualizer/projectm#86]
Libreelec is currently using projectm 2.0 from sourceforge, with a handful of patches applied:
https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/graphics/libprojectM/package.mk

With the effort to modernize projectm, it might be worth seeing if the work y'all are doing here can be incorporated into libreelec.

Also, with GL ES - it might be possible to run libreelec + projectm on a raspberry pi, which would be really awesome.

**Comment by revmischa** [comment]
Cool, let us know if we can help! Biggest change is now it's autotools instead of cmake. Moving the shaders to use GLSL is still a work in progress (#26) but you shouldn't see a regression unless you were building with the Cg framework before, which I highly doubt.

**Comment by jobevers** [comment]
One potential difficulty: it looks like there is some issue with GLEW and EGL.

https://forum.kodi.tv/showthread.php?tid=305558&pid=2514147#pid2514147

The build process has a patch that removes GLEW:

https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/graphics/libprojectM/patches/libprojectM-hacky-removal-of-glew-spiff.patch

It looks like GLEW 2.0 added EGL support: http://glew.sourceforge.net/index.html, but I'm not really sure what all is going on here.

**Comment by CvH** [comment]
sadly it crashs when switching from background to foreground - yet no idea why this happen (didn't tried too much yet)

**Comment by revmischa** [comment]
I think we got rid of GLEW

**Comment by revmischa** [comment]
We've removed GLEW entirely #106

**Comment by jobevers** [comment]
Awesome! I ended up deciding to user the raspberry pi for another use and used an old x86 computer for libreelec so I cant really test if it works on an ARM.

**Comment by CvH** [comment]
@jobevers last version is sadly not working properly https://github.com/projectM-visualizer/projectm/issues/111 but besides that it looks okay.

**Comment by revmischa** [comment]
Any help needed here?

**Comment by CvH** [comment]
>Any help needed here?

https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/graphics/libprojectM/package.mk#L6
we are already at some recent version that works :)

**Comment by revmischa** [comment]
Hope everything is working! Feel free to open a new ticket if you have problems
I hope we can get things working on a raspi soon. There is a relevant ticket: #168
