### ISSUE TITLE
Are preset ratings persisted?

### ISSUE THREAD

**Issue by jobevers** [projectM-visualizer/projectm#87]
In the presetloader, there is code in rate a preset and in the preset chooser there is code to use that rating to do a weighted random selection of a preset

But, it looks like the rating is set to 3 each time:
https://github.com/projectM-visualizer/projectm/blob/5792fb33d99e06cdd2c5ec51b3e1bcfd4abab740/src/libprojectM/PresetLoader.cpp#L122

Is there code to persist the ratings?

**Comment by revmischa** [comment]
Not anywhere that I'm aware of

**Comment by revmischa** [comment]
If you'd like libprojectM to persist ratings, feel free to send a PR! Or such things can be left up to the host application.
