### ISSUE TITLE
Scope Update Rate Incredibly Slow

### ISSUE THREAD

**Issue by knappador** [projectM-visualizer/projectm#9]
Seems like the last several versions, the rate of drawing new waveforms is barely 1/s whereas it was always much faster in Milkdrop.  I'm interested in fixing this if you know what might control it for PulseAudio.

**Comment by knappador** [comment]
Using pulse audio volume control, I'm able  to get some decent scope response, but it's nowhere near as pretty as it was in earlier versions.  I believe some kind of dynamic volume filtering is missing to scale the waveform up to a relevant amplitude and using PAVC to achieve the affect results in a very spiky appearance and can create cutoff.  Maybe newer resolutions are resulting in relatively smaller renders of the waveform?  Dynamic volume scaling would be nice to have (so I don't have to open PAVC) even if there is also a scale issue.

**Comment by revmischa** [comment]
I'm sorry I don't know anything about the specifics of the pulseaudio version, although I would imagine the drawing of the waveform would be the same in every version as long as the PCM data is being fed in at the same rates. I suggest looking for `addPCMfloat`
