### ISSUE TITLE
Native preset disable config flag

### ISSUE THREAD

**Issue by revmischa** [projectM-visualizer/projectm#99]
I think the native presets are not very interesting and should be disabled by default. If someone wants to make some cool native presets they can enable it, but normal users have no need for this functionality.

**Comment by Chinmaygoyal** [comment]
Can I work on this issue?

**Comment by revmischa** [comment]
@Chinmaygoyal go for it!

**Comment by Chinmaygoyal** [comment]
I am new to open source and have never made a PR before so can you help me by providing a start?

**Comment by revmischa** [comment]
Sure, there are lots of helpful articles if you click "Help" at the bottom of this page
Like this one: https://help.github.com/en/articles/fork-a-repo

**Comment by Purukitto** [comment]
Has this been solved?

**Comment by revmischa** [comment]
Nope

**Comment by AdityaC45** [comment]
Has this been solved? If not then I would like to help

**Comment by AdityaC45** [comment]
I am new to open source so can you help me to how to submit my first PR

**Comment by revmischa** [comment]
Please feel free

**Comment by RebuzZz** [comment]
Hi, I'd like to contribute to this project, I've forked this already and I'd like to know where I should start working and get some assistance.

**Comment by revmischa** [comment]
> Hi, I'd like to contribute to this project, I've forked this already and I'd like to know where I should start working and get some assistance.

Great! Join the discord! Look through open issues or fix something that bothers you. Documentation needs improving, downstream packages need maintaining.

**Comment by kblaschke** [comment]
Native presets can now be enabled via a CMake parameter and are disabled by default, but there's still no config setting to prevent them from being loaded if they are installed.

**Comment by kblaschke** [comment]
With disabled native preset support in the CMake build (which is the default), the whole native preset loading code won't be compiled into the library at all. As these presets have numerous issues with stability, security and portability, this issue should be fixed in the next release.
